### ISSUE TITLE
Enviromental problems

### ISSUE THREAD

**Issue by bremenpl** [OpenEtherCATsociety/SOEM#10]
Hello there,
I still havent solved my problem with building the library under windows- for the time being I have build it on another computer and copied the results to my pc. The problem is I cannot find the connected slaves, and they are working. For now here is the status:

- 2 slaves connected to beaglebone black running Debian. I can run slaveinfo demo and identify both slaves.
- 2 slaves connected to windows pc. I can run slaveinfo but cant find 2 slaves.
- 2 slaves connected to a linux virtual machine. I have connected a usb->ethernet dongle and shared it for the VM. In the linux VM i see the additional interface as eth1. I can run slaveinfo but like on windows, I cannot find the 2 slaves...

Could you please advice me some troubleshooting? I would really apreciate it.

**Comment by mheden** [comment]
Run Wireshark and look for EtherCAT frames (ethertype 0x88a4). The workingcounter should be `>0` in incoming frames if the slaves have accepted the command.

**Comment by bremenpl** [comment]
I ahve checked that. I also see on the slaves status leds that in the moment I run the app, the leds blink as if they received something. Here is the log from wireshark:

https://dl.dropboxusercontent.com/u/14154631/ethercat.pcapng

**Comment by bremenpl** [comment]
I have solved the problem under windows, I can not connect with slaves. Solution to this, was disabling all unnecessary services under network card settings. I only left topolygy driver and responder on:

![zrzut ekranu 2015-10-14 12 36 28](https://cloud.githubusercontent.com/assets/1183500/10481347/504a9a9c-7270-11e5-8d6d-e43013ec1f28.png)

Hope it helps someone :)!
