### ISSUE TITLE
FoE operational state

### ISSUE THREAD

**Issue by lukasfolle** [OpenEtherCATsociety/SOEM#100]
Hi,

Is it possible to use the FileoverEtherCAT protocol in different modes than Boot-Mode?
Because at the Beckhoff website they say 

> In the Boot state mailbox communication via the file access over EtherCAT (FoE) protocol is possible
[(Beckhoff Information System)](https://infosys.beckhoff.com/english.php?content=../content/1033/ax2000-b110/html/bt_ecbasics_ecstatemachine.htm&id=14011)

Best regards,
Lukas Folle

**Comment by nakarlsson** [comment]
I'd say it depends on slave, we use FoE in OP in some projects.

**Comment by lukasfolle** [comment]
Thank you.
