### ISSUE TITLE
ec_send_processdata()

### ISSUE THREAD

**Issue by AndyElogic** [OpenEtherCATsociety/SOEM#101]
According to the literal meaning,This function can send a data,But what does it send?,How do i now that?
Suppose I want to send data "a",How can I do?

**Comment by nakarlsson** [comment]
Start by reading the tutorial, it will give a hint. 
https://openethercatsociety.github.io/doc/soem/tutorial_8txt.html

**Comment by nakarlsson** [comment]
I think that should be enough to get started

**Comment by Newbotics** [comment]
@AndyElogic, Did you figure out how to send data?  If so, could you please share with me what you have learned? I am having the same problem right now.
