### ISSUE TITLE
Disable Sync manager watchdog

### ISSUE THREAD

**Issue by Zago86** [OpenEtherCATsociety/SOEM#104]
Hi,
I would like to know if there is a way to disable Sync manager watchdog, and possibly how to do it.

Thank

**Comment by Zago86** [comment]
Can anyone help me?

**Comment by nakarlsson** [comment]
You can try to disable it via the Sync Manager Control Byte, check the RM for ET1100 for example

**Comment by nakarlsson** [comment]
No update so fixed I guess
