### ISSUE TITLE
Add official support for Xenomai

### ISSUE THREAD

**Issue by zchen24** [OpenEtherCATsociety/SOEM#108]
I was wondering if there is a plan to add official support for Xeonmai + RTNet.

**Comment by nakarlsson** [comment]
No, most of what you see in todays SOEM are based on customer driven development. So if s customer project would require support for Xenomai we would add it.
That said I'm sure there already exist ports out there.

**Comment by zchen24** [comment]
Hi Andreas, 

If I have a "port" that works on Xenomai and would like to contribute back, are you open to this? 

Thanks,
Zihan

**Comment by nakarlsson** [comment]
yes

First step is to sign Contributor License Agreement: https://openethercatsociety.github.io/cla/cla_soem_soes.pdf

Second step is to create a pull request for review

**Comment by zchen24** [comment]
Thanks for the information.

**Comment by zchen24** [comment]
Just sent the signed Contributor License Agreement to openethercatsociety@rt-labs.com.
Will send a pull request late next month. 

Thanks,
Zihan

**Comment by zchen24** [comment]
Just sent a pull request. 

Thank you,
Zihan

**Comment by roboticsai** [comment]
where can i find the soem integrated with rtnet and xenomai? if it is not their, how can i do it myself?
