### ISSUE TITLE
Does not install to CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by hauptmech** [OpenEtherCATsociety/SOEM#109]
A CMAKE_INSTALL_PREFIX defaulted to ` ${CMAKE_SOURCE_DIR}/install` is preferable to an undocumented and non-standard HOST_INSTALL variable.

**Comment by hefloryd** [comment]
That should be the default, see CMakeLists.txt

```
if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
   # Default to installing in SOEM source directory
   set(CMAKE_INSTALL_PREFIX ${CMAKE_SOURCE_DIR}/install)
endif()

```

Does it not work for you?

**Comment by hefloryd** [comment]
Closing due to no response. Note that HOST_INSTALL was removed in commit fb975cb.
