### ISSUE TITLE
does the SOEM do the DC Synchronization of all slaves?

### ISSUE THREAD

**Issue by yuz835** [OpenEtherCATsociety/SOEM#113]
if so, how does it check if all slaves DC are synchronized?
and also how to handle the clock drift issue?

thanks

**Comment by nakarlsson** [comment]
This Issue contain most of the info.

Summary
1.  Check for the local sync diff register, when the slave clocks are with an acceptabel limit.
2. If you configure DC SOEM will add driftcontrol, red_test.c show how you sync the the master clock.

**Comment by yuz835** [comment]
thanks

**Comment by nakarlsson** [comment]
Forgot to past the ref: issue

https://github.com/OpenEtherCATsociety/SOEM/issues/105

It re-ref another good issue
