### ISSUE TITLE
Nevermind! Problem is solved. Thanks.

### ISSUE THREAD

**Issue by dan-choe** [OpenEtherCATsociety/SOEM#114]
Nevermind! Problem is solved. Thanks.

**Comment by nakarlsson** [comment]
Nope, I think you need to consult the manual, something isn't configured correct preventing you from entering safe-op & op.

**Comment by dan-choe** [comment]
When one of TX and RX is empty, I couldn't change the state of slave from Pre-OP to OP.
Is there any idea how to change state to OP if one of them is empty?

**Comment by nakarlsson** [comment]
If all refeences is empty, make sure you clear the SM object read from the EEPROM.

**Comment by dan-choe** [comment]
hum... I update SM assignment after removing all objects of one of 0x1A00 and 0x1600.
I still can't change Pre-OP to OP. How do I check SM object read from the EEPROM is cleared?
Sorry, I'm new to EtherCAT and SOEM.

**Comment by nakarlsson** [comment]
Run slaveinfo and and switch -map and -sdo and post the result. There you see how SOEM interpret the slave Online data including EEPROM data.
