### ISSUE TITLE
Makefiles in osal and oshw folders

### ISSUE THREAD

**Issue by zchen24** [OpenEtherCATsociety/SOEM#115]
There is an identical Makefile in ```osal/linux```, ```osal/rtk```, ```oshw/linux/``` and ```osal/win32```. 
The file includes a ```mk``` file ```$(PRJ_ROOT)/make/lib.mk```, which does not exist. 

Are these Makefiles used anywhere? If not, does it make sense to delete them?

**Comment by nakarlsson** [comment]
They should be deleted, they we're used before cmake

**Comment by nakarlsson** [comment]
I'll take care of that
