### ISSUE TITLE
Problem in the state machine

### ISSUE THREAD

**Issue by MrArdilla** [OpenEtherCATsociety/SOEM#134]
Good morning.

I own a Pluto servodrive, the protocol i am using is CoE. The current problem I have is that I can't change between the states "Ready to switch on" and "Switch on enable", whenever I send the controlword 7 or F the servodrive returns to the state "Switch On disabled".

I have read the documentation of my controler and it doesn't have any useful information about this error, I have tried with Twincat but when i try to online write the controlword it doesn't change, I mean i write 7 and it stays at 6, and the same happens when i try to wirte it with SDO instead of PDO.

I have tried forcing the enable of the motors with the program that ingenia provides the motion lab. The problem is that yes the motor is enabled but whenever i send a command to move it returns to the state "Switch on disabled".

Any help is welcome.

Thanks for your time.

**Comment by nakarlsson** [comment]
What does your PDO mappings look like, try running slaveinfo -map

You should do the following according to the ESI, have you done that? I can't find out exactly what it does but it might be mandatory stuff.
            <InitCmd>
              <Transition>PS</Transition>
              <Index>#x60C2</Index>
              <SubIndex>1</SubIndex>
              <Data>01</Data>
              <Comment>Interpolation time period</Comment>
            </InitCmd>
            <InitCmd>
              <Transition>PS</Transition>
              <Index>#x60C2</Index>
              <SubIndex>2</SubIndex>
              <Data>FD</Data>
              <Comment>Interpolation time index</Comment>
            </InitCmd>

**Comment by MrArdilla** [comment]
Hey, thanks for replying.

I have attached the map, if you could take a look at it. But i think it is okay, besides the normal parameters i have added the DC link circuit voltage to monitor. Because sometimes Twincat has given me an error related to voltage, but it stays stable and in the interval it is supposed to be.
*Don't mind the spaces, it is something i used to check the wkc.*
![mapa_pluto](https://user-images.githubusercontent.com/16540239/32437944-280e875c-c2e9-11e7-866e-931bb4620d22.png)

Besides, i have checked the parameters you told me with the MotionLab and SOEM, and the values i got are in line with the manual, there's a photo with the values as well.


![issue_ethercat](https://user-images.githubusercontent.com/16540239/32437983-45eefc34-c2e9-11e7-94cb-2ff864bb4a34.png)

What do you mean with doing the following according to the ESI? Ingenia has given me a .xml file and the parameters i get match the control position and the paramater i have added, but I think I haven't done a configuration related to the ESI,

Any is welcome, thank you so much.

**Comment by nakarlsson** [comment]
Can you reach OPERATIONAL? 
If then I think you got some non EtherCAT related issue
If not what is the ALStatusCode.

**Comment by MrArdilla** [comment]
Yes, I can reach OPERATIONAL with no problem, i run the simple_test and it works perfectly.
Okay thanks for your time, i will take a look at it.

Thank you so much.

**Comment by nakarlsson** [comment]
No SOEM or EtherCAT issue, maybe commisioning issue
