### ISSUE TITLE
Connot compile on Linux4.9 PREEMPT RT

### ISSUE THREAD

**Issue by muttistefano** [OpenEtherCATsociety/SOEM#136]
The cmake file won't recognize the rt kernel and if i force rtk as the os variable in CMakeList it complains abut kern.h not found.
Any workaround?
Thanks in advance

**Comment by nakarlsson** [comment]
You must use the wrong target, rt-kernel isn’t linux, it’s our RTOS. Build for linux?

**Comment by muttistefano** [comment]
Well, i didn't think of that.
Thanks

**Comment by nakarlsson** [comment]
Should work with linux
