### ISSUE TITLE
enable sm2 and sm3

### ISSUE THREAD

**Issue by satishdamo** [OpenEtherCATsociety/SOEM#140]
Dear sir,
Pls guide me to enable sm2 and sm3 of an ethercat slave through soem api functions, 

Please note below, enable is 0 for both sm2 as well as sm2, how to make enable 1 for both, if it is not by default.
SM2: PhysAddr 0x1800, DefaultSize   12, ControlRegister 0x64, Enable 0
SM3: PhysAddr 0x1c00, DefaultSize   20, ControlRegister 0x20, Enable 0

**Comment by nakarlsson** [comment]
You can re-use the example for how the mailboxes are re-programed in https://github.com/OpenEtherCATsociety/SOEM/blob/master/test/linux/firm_update/firm_update.c

**Comment by nakarlsson** [comment]
Should be straight forward.
