### ISSUE TITLE
Motivate Linux kernel 2.6 requirement? 

### ISSUE THREAD

**Issue by 5frank** [OpenEtherCATsociety/SOEM#145]
Could you please add a short note on why the 2.6 kernel is required? It is listed as a precondition in doc/soem.dox and it is unclear (at least to me) why.  I'm on the 3.14 kernel and would really like to know what issues this might cause.

**Comment by nakarlsson** [comment]
None, it should say minimum 2.6, I believe it has to do with PF_PACKET not being present in earlier version, if I remember correct.

**Comment by nakarlsson** [comment]
Seems PF_PACKETS came in 2.2 so there has to be something else, never the less it should imply 2.6 and later.
