### ISSUE TITLE
Is anyone working on an EoE (ethernet over ethercat) support ?

### ISSUE THREAD

**Issue by leolchat** [OpenEtherCATsociety/SOEM#153]
Seems like the new Kollmorgen drives are using that as the main configuration interface to their devices (AKD-N).

PS: Etherlab used to provide that, not sure how well it is working.

**Comment by nakarlsson** [comment]
Not that I'm aware off, most of the functions rt-labs and smfk add are driven by customer  projects.

**Comment by nakarlsson** [comment]
No-one else either I guess
