### ISSUE TITLE
WinPcap alternative

### ISSUE THREAD

**Issue by Cifi79** [OpenEtherCATsociety/SOEM#154]
Have you ever consider to try an alternative to WinPcap library?
I see that there are some example here:
https://docs.microsoft.com/it-it/windows-hardware/drivers/network/ndis-core-functionality2

Do you think it could be useful for SOEM?

Thanks

**Comment by nakarlsson** [comment]
It would be useful indeed, at least as an alternative,given that there are benefits from using? Interested to help out and add it to SOEM? Or anyone else?

**Comment by Cifi79** [comment]
Unfortunately I am not very experienced to do this kind of modification. It could be a tip for more experienced users. I also saw that a user that fork SOEM uses NPcap instead of WinPcap, you or someone else has ever tried it?

**Comment by nakarlsson** [comment]
Not that I’m aware of, the beuty with WinPCAP/Wireshark is tjatig works well on any Windows machine, if we can get that and better performance it is very interesting. Have/Can you try NPcap?

What issues do you have with winpcap?

**Comment by Cifi79** [comment]
Well, I will try NPcap ( as I understood it’s compatible with WinPcap so inside SOME I don’t have to change nothing) then I’ll write to tell if is working.
With Win10 we notice two strange issue:

  1.  We have to disable “Intel Access Filter” inside network properties
  2.  If we access to the Network properties page, the SOME stop to work.

Da: nakarlsson [mailto:notifications@github.com]
Inviato: giovedì 8 febbraio 2018 19:41
A: OpenEtherCATsociety/SOEM <SOEM@noreply.github.com>
Cc: Cifi79 <cifi79@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [OpenEtherCATsociety/SOEM] WinPcap alternative (#154)


Not that I’m aware of, the beuty with WinPCAP/Wireshark is tjatig works well on any Windows machine, if we can get that and better performance it is very interesting. Have/Can you try NPcap?

What issues do you have with winpcap?

**Comment by Cifi79** [comment]
Hi nakarlsson, I'm working with NPcap installed in my pc and all is working well.
Regarding the use of NDIS functionality in Micorsoft library, I think that before is better to skill myself on SOEM and after, maybe, I'll try that library.
So if you want you can close this issue.
Thanks
