### ISSUE TITLE
Incomplete/incorrect information on how to setup in Windows

### ISSUE THREAD

**Issue by tacarrie** [OpenEtherCATsociety/SOEM#16]
On the page SOEM/doc/soem.dox the information on how to setup the project for making it running in Visual Studio are incomplete and incorrect. The mentioned file vcvarsall.bat doesn't exist in the project directory.

**Comment by mheden** [comment]
Ok, `vcvarsall.bat` is included in Visual studio.

See this instruction instead: https://github.com/OpenEtherCATsociety/SOEM/blob/master/README.md

**Comment by mheden** [comment]
Fix in #31
