### ISSUE TITLE
Cannot compile with library libsoem.a

### ISSUE THREAD

**Issue by accrea** [OpenEtherCATsociety/SOEM#169]
Dear Developers,
I've successfully compiled the SOEM and I want to use the libsoem.a in my project but I got this error during compilation of my project:
`....../SOEM/build/libsoem.a(osal.c.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'`
I would appreciate any ideas.

**Comment by accrea** [comment]
I'm using: ubuntu-16.04.4-desktop-amd64, Eclipse for C project.
I think the pthread is available becouse all SOEM source compiles just fine on the same system environment.
The problem arises when I want to compile my project with soem static library. I've configured my project so it links soem and pthread library but it still makes the error:
![project properties](https://user-images.githubusercontent.com/7223980/38718450-7ef5c7b2-3eed-11e8-8ec5-61fcb91dedc9.png)

**Comment by nakarlsson** [comment]
Can it have to do with link order? seems soem link after pthread, it don't know it should add the missing symbol?

**Comment by nakarlsson** [comment]
It should be OK, to solve it you could add an ifndef handler in your osal.h.

**Comment by accrea** [comment]
Thank you for your kind help!

Honestly I don't understand what causes the "undefined reference" error. It is possible I lack some knowledge. I'm including my findings, maybe someone will find them useful.

**1. Libraries link order riddle.**

What compiles fine:
```
#include "ethercat.h"
int main (int argc, char *argv[]) {
	// static libraries link order: -lsoem -lpthread // <--NOTE
	//pthread_create(0, 0, 0, 0); // <--NOTE
	ec_init("");
	return 0;
}
```
```
#include "ethercat.h"
int main (int argc, char *argv[]) {
	// static libraries link order: -lsoem -lpthread // <--NOTE
	pthread_create(0, 0, 0, 0); // <--NOTE
	ec_init("");
	return 0;
}
```
```
#include "ethercat.h"
int main (int argc, char *argv[]) {
	// static libraries link order: -lpthread -lsoem // <--NOTE
	pthread_create(0, 0, 0, 0); // <--NOTE
	ec_init("");
	return 0;
}
```

What makes errors:
```
#include "ethercat.h"
int main (int argc, char *argv[]) {
	// static libraries link order: -lpthread -lsoem // <--NOTE
	//pthread_create(0, 0, 0, 0); // <--NOTE
	ec_init("");
	return 0;
}
```
I got errors like this one:
```
libsoem.a(osal.c.o): In function `osal_thread_create':
osal.c:(.text+0x3c7): undefined reference to `pthread_attr_setstacksize'
```

**2. Solution for the TRUE/FALSE redefinition warning.**

The includes order causes the redefinition warning of TRUE/FALSE defines (osal.h:19:0: warning: "TRUE" redefined ... gmacros.h:284:0: note: this is the location of the previous definition):
```
#include <gtk/gtk.h>
#include "ethercat.h"
```
The warning is caused by osal.h and gmacros.h. The osal.h doesn't use ifndef around TRUE/FALSE definitions. The gmacros.h utilizes ifndef. So simply changing the include order helps to get rid of the warning:
```
#include "ethercat.h"
#include <gtk/gtk.h>
```
Now osal.h defines the TRUE/FALSE symbols, whereas gmacros.h notices the symbols are already defined.
The osal.h definition of TRUE is 1 and gmacros.h definition of TRUE is !FALSE producing 1 too.

**Comment by nakarlsson** [comment]
1. Yes it has to do with how the linker resolve dependencies. All your findings make sense if you study linking. 
You can also add a behaviour that it resolve dependencies in a circular fashion that would make all the above work. But this is off the topic for SOEM and EtherCAT.

2. We’ll look into if that can be improved.

**Comment by accrea** [comment]
1. After all I use the "-lsoem -lpthread" library link order. Unfortunately Eclipse cannot handle circular dependencies and doesn't allow multiple entries of the same library eg. "-la -lb -la" (at least in an easy and neat way).
