### ISSUE TITLE
cannot find salve

### ISSUE THREAD

**Issue by JianchengYang** [OpenEtherCATsociety/SOEM#175]
run the soem cannot find slave and add information to detect whether the program is running correctly and the information cannot be printed out，but the original information of the program can be printed out normally

**Comment by nakarlsson** [comment]
Please search the Issues for similar entries, for example already open https://github.com/OpenEtherCATsociety/SOEM/issues/172.

**Comment by JianchengYang** [comment]
Hello, I have checked #172， then I tried to use another computer to do the same operation, and I found the slave station. Is it related to the network card of the computer?

**Comment by nakarlsson** [comment]
Seems so, you need to provide SOEM with the abillity to send layer 2 frames , the reference use WinPCAP. If that don’t work you can use another layer 2 solution.
