### ISSUE TITLE
Investigate options to WinPCAP

### ISSUE THREAD

**Issue by nakarlsson** [OpenEtherCATsociety/SOEM#186]

**Comment by nakarlsson** [comment]
It's unclear of the WinPCAP status, officially Win10 is not supported?

Options:
https://nmap.org/npcap/

**Comment by ArthurKetels** [comment]
Using npcap on my laptop for over half a year now. Works fine. Issue is the license, only free for personal use.

**Comment by nakarlsson** [comment]
Ok, good to know. I persume you run in WinPCAP compatible mode?
