### ISSUE TITLE
SOEM can't output data with simple_test

### ISSUE THREAD

**Issue by TroyChu** [OpenEtherCATsociety/SOEM#192]
A few days ago, my SOEM works well, but today when I try the simple_test, it can not output data. It will either keep outputting "OK : all slaves resumed OPERATIONAL" or stuck at "Calculated workcounter 3". What wrong with the SOEM? What should I do?
![img_1891](https://user-images.githubusercontent.com/32088110/43741899-edd40792-999d-11e8-8c6f-508a83d3350f.JPG)
![img_6356](https://user-images.githubusercontent.com/32088110/43741900-ede2c2a0-999d-11e8-8ce8-e6bb6a6473e0.JPG)

**Comment by ArthurKetels** [comment]
The last screen shows slave state 0x14 (Pre operational + error) and the error status code is 0x001a (Sync error). Clearly your timing is not set-up correctly for your slave. Check the slave requirements and compare against the real timing as captured by wireshark.

Some slaves for example require a constant PDO update with fixed time interval during the PreOp To OP transition. Some even require the maximum deviation to be within strict bounds.

**Comment by nakarlsson** [comment]
@TroyChu , can we close this issue?

**Comment by nakarlsson** [comment]
We'll close
