### ISSUE TITLE
Set priority inheritance for mutex in oshw/linux/nicdrv.c

### ISSUE THREAD

**Issue by Wanga** [OpenEtherCATsociety/SOEM#193]
The application with all thread in RT might uses a high priority thread for process data updating, and many low priority threads use PDO data and call SDO read/write sometimes (e.g., read exception status). 

A low priority thread might be preempted by a medium priority thread while holding the mutex in oshw/linux/nicdrv.c. This could create a priority inversion and block PDO updating thread for a long time.

Is that possible to set those mutex to PTHREAD_PRIO_INHERIT?
https://linux.die.net/man/3/pthread_mutexattr_setprotocol

**Comment by nakarlsson** [comment]
It makes sense to protect against priority inversion, could you submit a PR?
