### ISSUE TITLE
how to find slave number 

### ISSUE THREAD

**Issue by messiah1376** [OpenEtherCATsociety/SOEM#197]
How can I find the slave number in order to use ec_SDOwrite?
`int ec_SDOwrite(slaveNumber,...)`

**Comment by nakarlsson** [comment]
You can check how this sample, it expects an ebox as slave number 1, that it will program via SDOs.
https://github.com/OpenEtherCATsociety/SOEM/blob/master/test/linux/ebox/ebox.cide
