### ISSUE TITLE
Can't write to subindexes of 0x1600 using ec_SDOwrite

### ISSUE THREAD

**Issue by mohse-n** [OpenEtherCATsociety/SOEM#202]
I would like to modify the PDO mapping by changing the value of entries under 0x1600 (1st RPDO mapping).
For some reason, I can't write to subindexes of 0x1600 with `ec_SDOwrite` (the drive is in PRE_OP state). I should also mention that `ec_SDOread` for reading the same address has been pretty inconsistent (some times it work and the other times it fails)
For example:
```
void initialize (char* ifname)
{
	if (ec_init(ifname))
	{
		printf("ec_init on %s succeeded. \n",ifname);

		if (ec_config_init(FALSE) > 0)
		{		
			printf("%d slaves found and PRE_OP state requested\n", ec_slavecount);
				if (ec_statecheck(0, EC_STATE_PRE_OP, EC_TIMEOUTSTATE) == EC_STATE_PRE_OP)
					printf("All slaves reached PRE_OP state\n");
	
		}
	}
}

int main(int argc, char* argv[])
{
initialize(argv[1])
int result;
uint32 objectValue= 0x60c10120;
objectSize = sizeof(objectValue);
result = ec_SDOwrite(1, 0x1600, 0x02, FALSE, objectSize, &objectValue, EC_TIMOUTRXM);
if (result == 0)
      printf("SDO write unsuccessful");
}
```
The output is always `SDO write unsuccessful`.
One other question related to EtherCAT in general: what is the goal of assigning Sync Manager PDOs? For instance, in ebox.c we have:
```
os=sizeof(ob2); ob2 = 0x1601;
ec_SDOwrite(1,0x1c12,01,FALSE,os,&ob2,EC_TIMEOUTRXM);
os=sizeof(ob2); ob2 = 0x1a01;
ec_SDOwrite(1,0x1c13,01,FALSE,os,&ob2,EC_TIMEOUTRXM);
```

**Comment by ArthurKetels** [comment]
You can not simply write subindexes of PDO assignment objects, they need special care as stated in the EtherCAT standard.

First the slave must allow changes in it's PDO mapping. You can check for the write bit in the objects (f.e. with slaveinfo -map).
Change is only possible in pre-op.
First set subindex 0 to 0 (zero)
Then modify subindexes 1..n
Last set subindex 0 to the proper number of subindexes n

PDO assignment is a common way of changing PDO mappings. For a lot of slaves it makes sense to limit the users options to what PDO combinations are allowed. So instead of changing the PDO entries directly you can only choose out of a defined set of combinations.

**Comment by mohse-n** [comment]
Thank you. 
1- The procedure that you have described worked. The issue I'm currently having is, after successfully setting the 0x1600_sub2 to my desired value (`0x60c10120`), it seems that according to `./slaveinfo -map`, PDO mapping hasn't changed at all.
PDO mapping according to CoE :
```
  SM2 outputs
     addr b   index: sub bitl data_type    name
  [0x0000.0] 0x6040:0x00 0x10 UNSIGNED16   Controlword
  [0x0002.0] 0x607A:0x00 0x20 INTEGER32    Target Position
  SM3 inputs
     addr b   index: sub bitl data_type    name
  [0x0006.0] 0x6041:0x00 0x10 UNSIGNED16   Statusword
  [0x0008.0] 0x6064:0x00 0x20 INTEGER32    Position Actual Value 
```
The output above is exactly as it was prior to writing to 0x1600_sub2. But I expected the second SM2 output to be set to index `0x60C1`. I wonder, is there a step (e.g. for saving the PDO mapping) that I'm missing here?

> PDO assignment is a common way of changing PDO mappings. For a lot of slaves it makes sense to limit the users options to what PDO combinations are allowed. So instead of changing the PDO entries directly you can only choose out of a defined set of combinations.

2- Does that mean I don't have to bother with sync manager PDO's at all when I'm manually mapping PDOs?

3- I'm sorry if my questions seem obvious. Is there an EtherCAT document that explains, for example, the procedure that you mentioned for PDO mapping?

**Comment by ArthurKetels** [comment]
You could actually look up the slave mapping CoE capabilities with slaveinfo. The bitmap will tell you if and how the PDO mapping can be changed. 

Documentation is available at the ETG when you are a member. Unfortunately it is not allowed to share those documents with non-members. Membership is free so nothing withholds you from becoming a member. The other option is to get the documents from IEC, but that will cost money.

I guess that for your slave it is not possible to change the PDO mapping directly but you would only be able to select the SM mapping. The solution is the same as with the ebox example you topposted.

If you have some more info about your slave I could confirm this. So slave type and manufacturer or link to the XML ESI file of the slave.

**Comment by mohse-n** [comment]
The slave is L7N servo drive by Mecapion. [Here's the XML file](http://www.lsmecapion.com/board/download.php?file=userfile%2F1372293986%40LS+Mecapion+L7N_V0.02e.xml&file_name=LS%20Mecapion%20L7N_V0.02e.xml).

**Comment by ArthurKetels** [comment]
Uhm, yes, this slave has both PDOconfig and PDOassign set to true, And at the PDO mapping Fixed=0. This would meand that you can both reprogram The Tx- and Rx-PDO's as well as change the SM mapping. But clearly the first fails.

So this is a fairly standard DS402 slave that only allows PDO assign in the SM. The PDOconfig is bogus and a bug in the firmware. I guess when this slave is tested with the latest conformance test it will fail. But what is new.....

Ask the supplier for a firmware update or work around it.
