### ISSUE TITLE
PDO output always automatically change the value itself.

### ISSUE THREAD

**Issue by PaninP** [OpenEtherCATsociety/SOEM#205]
Dear Sir,

I'm a newbie for SOEM which I am using servo amplifier as the slave.
I run slaveinfo with -map option that was working well which I can see all mapping PDO data.

![image](https://user-images.githubusercontent.com/42864707/44907522-647a8d00-ad42-11e8-9e0f-2e5418e1669f.png)

Then I run simple_test that I can get the servo position data and everything seems very well.
However, The first 2Byte of PDO outputs which mapped to ControlWord of servo amplifier is always change itself even the source code has not been changed yet as I attached the picture.

![image](https://user-images.githubusercontent.com/42864707/44907430-15345c80-ad42-11e8-9b7a-c270e4077954.png)

I could not control my servo amplifier if the control word is running strangely.
Could anyone suggest me what happen is it and is there any solution to fix it out?

**Comment by nakarlsson** [comment]
Can you post the simple_test file you are running?

**Comment by PaninP** [comment]
Thank you your response.
Actually, I was running with the original example file in test/win32/simple_test folder.
I just doubt this is normal output of this example code or there is something wrong.
However, It was attached.
[simple_test.zip](https://github.com/OpenEtherCATsociety/SOEM/files/2340552/simple_test.zip)

**Comment by nakarlsson** [comment]
That sample cnt in the first byte, kind of alive cnt.

/* most basic RT thread for process data, just does IO transfer */
void CALLBACK RTthread(UINT uTimerID, UINT uMsg, DWORD_PTR dwUser, DWORD_PTR dw1,  DWORD_PTR dw2)
{
    **IOmap[0]++;**

    ec_send_processdata();
    wkc = ec_receive_processdata(EC_TIMEOUTRET);
    rtcnt++;
    /* do RT control stuff here */
}

**Comment by PaninP** [comment]
I try studying and playing a lot on above suggestion.
Just comment out the IOmap[0]++; 
I really understood on it.
Thank you very much

**Comment by nakarlsson** [comment]
good, I'll close this then.
