### ISSUE TITLE
Possibility of master missing EtherCAT frames with ec_receive_processdata?

### ISSUE THREAD

**Issue by mohse-n** [OpenEtherCATsociety/SOEM#209]
Hi. I want to know whether there is the possibility of master missing frames when using 
```
   ec_send_processdata();
   wkc = ec_receive_processdata(EC_TIMEOUTRET);
```
If, after `ec_send_processdata`, there is a context switch for some reason, will I still receive the frame after returning to this thread of execution (maybe it's stored in a low-level buffer?), or is it lost?

**Comment by nakarlsson** [comment]
Yes, you will still receive the frame, it will be stored in lower levels, where exactly depends on your software.

**Comment by nakarlsson** [comment]
Should be OK
