### ISSUE TITLE
Linux: libsoem.a is installed in bin/

### ISSUE THREAD

**Issue by ShabbyX** [OpenEtherCATsociety/SOEM#21]
`libsoem.a` should be installed in a `lib/` directory. Is there a reason it is put in `bin/` now? Or should I send a PR that fixes it?

**Comment by hefloryd** [comment]
The reason was that it was a somewhat simpler layout for other tools that consumed the build result (to make bindings for other languages for instance). But we can change it, please send a PR if you like.
