### ISSUE TITLE
Issue with Kernel 4.15.0-34-generic

### ISSUE THREAD

**Issue by stefanpoeter** [OpenEtherCATsociety/SOEM#211]
Trying the slaveinfo on this kernel gives me nothing on the PDO Mapping with complex slaves. When I use other systems with other kernels 4.17+ or 4.4.0-21-generic everything works fine. Any ideas?

**Comment by nakarlsson** [comment]
Related to https://github.com/OpenEtherCATsociety/SOEM/issues/203?

**Comment by ArthurKetels** [comment]
Yes, I can confirm ubuntu 4.15.0-34 does not apply the patch mentioned in #203.

**Comment by jmFernandezMola** [comment]
Same problem here, I have no issues with Kernel 4.13, but the same program in the same machine fails when running the Kernel 4.15.0-34.

**Comment by nakarlsson** [comment]
#203 related
