### ISSUE TITLE
Linux: CMAKE_INSTALL_PREFIX overriden in CMakeLists.txt

### ISSUE THREAD

**Issue by ShabbyX** [OpenEtherCATsociety/SOEM#22]
`CMAKE_INSTALL_PREFIX` being set to `source/install`, it is impossible to override this in command line to actually install the library in the system. Would you mind if I remove it and send a PR?

**Comment by hefloryd** [comment]
Our main use-case is to cross-compile SOEM for other architectures, where it makes little sense to install it in the host system. But it would be easy enough to explicitly configure it that way if that is required. Please send a PR if you like, possibly defaulting to not install in the host system.

**Comment by ShabbyX** [comment]
Ok, I see. I'd do that, so you wouldn't have to change anything, but it would also be possible to install to host!

**Comment by hefloryd** [comment]
Sounds good.
