### ISSUE TITLE
include ec_mbxerror2string in the header

### ISSUE THREAD

**Issue by nicolapedrocchi** [OpenEtherCATsociety/SOEM#232]
Hi, 
just as very small enhancement of the project, is it possible to include the declaration of ec_mbxerror2string in ethercatprint.h ? 
Just to improve the user-diagnostic when the raised error is of type EC_ERR_TYPE_MBX_ERROR

Thanks
n.

**Comment by nakarlsson** [comment]
what is the use-case? How do you use? It should go into the header or turned static.

**Comment by nicolapedrocchi** [comment]
Hi, thanks for the prompt answer
I am using SOEM build libraries in a ROS application.
I push all the errors in a diagnostic message, to ease the user comprehension of what is happening. 

Actually, it's never happen that a EC_ERR_TYPE_MBX_ERROR is caught, but it is a pity not having the description of the error available at user level when is already implemented in the cpp file.
 
I guess that just having the declaration in the header is ok.

Many thanks
Nicola
