### ISSUE TITLE
I can't compile it at vxWorks Workbench 3.3

### ISSUE THREAD

**Issue by liuzq71** [OpenEtherCATsociety/SOEM#238]
![image](https://user-images.githubusercontent.com/24559775/50051051-675c8a80-0145-11e9-9b8f-b4be4c599e3e.png)

**Comment by nakarlsson** [comment]
Yes, thats a known issue, copy past bug introduced recently. 4 lines above you’ll find the proper variable.

**Comment by nakarlsson** [comment]
should be fixed by https://github.com/OpenEtherCATsociety/SOEM/pull/275
