### ISSUE TITLE
connect coupler ek1818 to pc 

### ISSUE THREAD

**Issue by radwa4** [OpenEtherCATsociety/SOEM#274]
after downloading soem and following  steps .i connect pc with coupler ek1818 beckhoff  by ethernat cable  only and run simple test by write in terminal (./simple_test) print in terminal name of simple test .i don't know how check pc run as master and connect by coupler ?and do you must connect power to coupler or only ethernet cable by pc?

**Comment by nakarlsson** [comment]
You need power

**Comment by radwa4** [comment]
i connect pc by ek1818 coupler by ethernet and connect coupler by power 24
volt and when run code slave info  this what happened what i should do to
see slave coupler??

‫في السبت، 30 مارس 2019 في 6:40 م تمت كتابة ما يلي بواسطة ‪nakarlsson‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Tugev** [comment]
Hi, you should run the code as a root (sudo) and also include the coupler socket name (usually eth0) in your terminal. For example:

`sudo ./simple_test eth0`
If it is not eth0, then use `ifconfig` to get the right coupler socket name.

**Comment by radwa4** [comment]
can you tell me how turn on led on ethercat ?and how connect circuit on
output and input pins?

‫في الجمعة، 5 أبريل 2019 في 7:59 م تمت كتابة ما يلي بواسطة ‪Tugev‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Tugev** [comment]
Hi , actually I have no much experience in etherCats but the input module is for reading and the output one is for writing. 
There is a function in the main.c file called:
 `void set_output_bit (uint16 slave_no, uint8 module_index, uint8 value)`  use it to write the channels in the output module.

For connecting the circuit, you should refer to the manual.

**Comment by nakarlsson** [comment]
There are examples online, please read them

**Comment by radwa4** [comment]
can you help me with links of this online examples?
