### ISSUE TITLE
SOEM on Linux Mint

### ISSUE THREAD

**Issue by if2s** [OpenEtherCATsociety/SOEM#278]
Hello,
is there a step-by-step manual for SOEM installation on a PC Linux distribution like mint? For first I do not need a realtime property. For first experiments, there is no RT_Preempt kernel patch nessesary.
I need a Tipp how to start installation on PC.
Thank you!

**Comment by ArthurKetels** [comment]
What is wrong with the readme.md? You want to do c program compilation so you need build-essentials and cmake. That is it.

**Comment by nakarlsson** [comment]
read the info first as suggested by Arthur
