### ISSUE TITLE
Input Configuration Error

### ISSUE THREAD

**Issue by KleveJ** [OpenEtherCATsociety/SOEM#298]
Hi everyone, I new to SOEM and I am running into an issue during the configuring stage.
Slaveinfo eth0 -map provides the following info

![image](https://user-images.githubusercontent.com/10470625/57798103-cf1cfe80-7700-11e9-9021-6cced95992cf.png)

I have also had a look at [https://github.com/hefloryd/SOEM/commit/22d8f5d](url) but I am a little confused about the values on lines 64 through 72 for simple_test.

Any help setting this up would be appreciated. Ive included the ESI file and communication manual to provide as much info as I can.

ESI file

[P0012817-01082019.txt](https://github.com/OpenEtherCATsociety/SOEM/files/3183762/P0012817-01082019.txt)

Drive Manual
[SANMOTION_R_3E_M0011697.pdf](https://github.com/OpenEtherCATsociety/SOEM/files/3183765/SANMOTION_R_3E_M0011697.pdf)

**Comment by ArthurKetels** [comment]
According to ESI the default configuration should work. Slaveinfo can not read the mapping for one reason or the other. So please post a wireshark capture .pcap file.

**Comment by KleveJ** [comment]
I tried the example that I linked above but swapped my SM2 and SM3 registers for the ones in the example and I wound up with this result after running slaveinfo.c

![Screenshot from 2019-05-15 12-32-27](https://user-images.githubusercontent.com/10470625/57803574-9a637400-770d-11e9-83af-2035b36f26e5.png)


Here is the file from pcap from wireshark.

[RS3_pcap.zip](https://github.com/OpenEtherCATsociety/SOEM/files/3184176/RS3_pcap.zip)

**Comment by ArthurKetels** [comment]
I think you have to read from 5-6 onward in the manual. The manual is very precise in how the master should engage with the drive. Just follow the steps. When that works see how much you can change before the drive starts complaining.

**Comment by KleveJ** [comment]
Ive read through most of it but it doesnt really tell me what I need to change to get into Safe-OP or if it does I dont know what to look for.

**Comment by ArthurKetels** [comment]
Looks like you want to bake cake and don't know how to read the recipe. 

I give you two examples from 5-8

Is ESM in "Pre-Operational" state? R 0x0130 - : AL Status 0x0002)
Register read : here you (or SOEM) has to read register 0x0130 of the slave  to check pre-op state. You use ec_FPRD().

･ Sets PDO Object Index to be assigned in SM2 W 0x1C12.0=0x01 : SM2 RxPDO Entry
SDO write : here you (or SOEM) has to write SDO object 0x1c12:00 with value 0x01. You use ec_SDOwrite().

How much cleared do you want it? And if you do not understand the basic principles of EtherCAT first read up on it. There is lots of documentation available on www.ethercat,org.

**Comment by KleveJ** [comment]
Thank you. Ive read what is available on the public facing part of ETC and ive applied for membership so I can get access to the knowledgebase and forums there but I havnt heard back yet.

**Comment by ArthurKetels** [comment]
Hmm, trying to get a complex slave configuration done without the support of the member documentation is hard indeed. SOEM assumes you have proper knowledge of the inner EtherCAT workings. It is a lib, not a complete packaged solution.

**Comment by KleveJ** [comment]
I agree with you there. I understand the basics but Im probably missing a few key details here and there which doesnt help. Ive been able to get into the OP state consistently but Im running into a issue where when I write the setup for the slave I get a watchdog configuration error. Immediately after I commented out the setup related code and it goes into OP mode as expected. Running it a second time results in an inconsistent settings error. 

so the order goes some like this"
1) Run with modified slave setup --> output Watchdog Configuration error
2) Run without modified slave setup --> output OP state Process data as normal
3) Run again without modified slave setup --> out inconsistent settings error
4) see step 1

The modified file looks like this:
`/** \file
 * \brief Example code for Simple Open EtherCAT master
 *
 * Usage : simple_test [ifname1]
 * ifname is NIC interface, f.e. eth0
 *
 * This is a minimal test.
 *
 * (c)Arthur Ketels 2010 - 2011
 */

#include <stdio.h>
#include <string.h>
#include <inttypes.h>

#include "ethercat.h"

#define EC_TIMEOUTMON 500

char IOmap[4096];
OSAL_THREAD_HANDLE thread1;
int expectedWKC;
boolean needlf;
volatile int wkc;
boolean inOP;
uint8 currentgroup = 0;

static int RS3_write8(uint16 slave, uint16 index, uint8 subindex, uint8 value)
{
    int wkc;
    wkc += ec_SDOwrite(slave, index, subindex, FALSE, sizeof(value), &value, EC_TIMEOUTRXM);
    return wkc;
}

static int RS3_write16(uint16 slave, uint16 index, uint8 subindex, uint16 value)
{
    int wkc;
    wkc += ec_SDOwrite(slave, index, subindex, FALSE, sizeof(value), &value, EC_TIMEOUTRXM);
    return wkc;
}

static int RS3_write8(uint16 slave, uint16 index, uint8 subindex, uint32 value)
{
    int wkc;
    wkc += ec_SDOwrite(slave, index, subindex, FALSE, sizeof(value), &value, EC_TIMEOUTRXM);
    return wkc;
}

static int RS3_setup(uint16 slave)
{
    int wkc;
    printf("RS3 drive setup\n");

    wkc += RS3_write8(slave, 0x1C12, 0, 0);
    wkc += RS3_write8(slave, 0x1C13, 0 , 0);
    
    wkc += RS3_write8(slave, 0x1702, 0 , 0);
    wkc += RS3_write32(slave, 0x1702, 1, 0x607A0020);
    wkc += RS3_write32(slave, 0x1702, 2, 0x60600000);
    wkc += RS3_write32(slave, 0x1702, 3, 0x00000008);
    wkc += RS3_write32(slave, 0x1702, 4, 0x60400010);
    wkc += RS3_write8(slave, 0x1702, 0, 4);

    wkc += RS3_write8(slave, 0x1B03, 0, 0);
    wkc += RS3_write32(slave, 0x1B03, 1, 0x60640020);
    wkc += RS3_write32(slave, 0x1B03, 2, 0x60770010);
    wkc += RS3_write32(slave, 0x1B03, 3, 0x60610000);
    wkc += RS3_write32(slave, 0x1B03, 4, 0x00000008);
    wkc += RS3_write32(slave, 0x1B03, 5, 0x60410010)
    wkc += RS3_write8(slave, 0x1B03, 0, 5);
    
    wkc += RS3_write16(slave, 0x1C12, 1, 0x1702);
    wkc += RS3_write16(slave, 0x1C12, 0, 1);

    wkc += RS3_write16(slave, 0x1C13, 1, 0x1B03);
    wkc += RS3_write16(slave, 0x1C13, 0, 1);

    wkc += RS3_write8(slave, 0x6060, 0 , 0);
    
    wkc += RS3_write8(slave, 0x1C32, 1, 0x0);
    wkc += RS3_write8(slave, 0x1C33, 1, 0x0);

    //Explicitly set flags that are (probably) invalid in EEPROM
    ec_slave[slave].SM[2].SMflags = 0x10024'

    //Explicitly disable sync managers that are activated by EEPROM
    ec_slave[slave].SM[4].startAddr = 0;
    ec_slave[slave].SM[5].startAddr = 0;

    //set a slave name
    strncpy(ec_slave[slave].name, "RS3", EC_MAXNAME);

    if(wkc != 22)
    {
        printf("RS3 setup failed\n");
        return -1;
    }
    return 0;
}

void simpletest(char *ifname)
{
    int i, j, oloop, iloop, chk, slave_ix;
    needlf = FALSE;
    inOP = FALSE;

   printf("Starting simple test\n");

   /* initialise SOEM, bind socket to ifname */
   if (ec_init(ifname))
   {
      printf("ec_init on %s succeeded.\n",ifname);
      /* find and auto-config slaves */


       if ( ec_config_init(FALSE) > 0 )
      {
         printf("%d slaves found and configured.\n",ec_slavecount);
         if(ec_slavecount > 0)
         {
             for(slave_ix = 1; slave_ix <= ec_slavecount; slave_ix++)
             {
                 ec_slavet* slave = &ec_slave[slave_ix];
                //RS3 drive
                if(slave->eep_man == 0x1B9 && slave->eep_id == 0xB)
                {
                    slave->PO2S0config = RS3_setup;
                }
             }
         }
         
         ec_config_map(&IOmap);

         ec_configdc();

         printf("Slaves mapped, state to SAFE_OP.\n");
         /* wait for all slaves to reach SAFE_OP state */
         ec_statecheck(0, EC_STATE_SAFE_OP,  EC_TIMEOUTSTATE * 4);

         oloop = ec_slave[0].Obytes;
         if ((oloop == 0) && (ec_slave[0].Obits > 0)) oloop = 1;
         if (oloop > 8) oloop = 8;
         iloop = ec_slave[0].Ibytes;
         if ((iloop == 0) && (ec_slave[0].Ibits > 0)) iloop = 1;
         if (iloop > 8) iloop = 8;

         printf("segments : %d : %d %d %d %d\n",ec_group[0].nsegments ,ec_group[0].IOsegment[0],ec_group[0].IOsegment[1],ec_group[0].IOsegment[2],ec_group[0].IOsegment[3]);

         printf("Request operational state for all slaves\n");
         expectedWKC = (ec_group[0].outputsWKC * 2) + ec_group[0].inputsWKC;
         printf("Calculated workcounter %d\n", expectedWKC);
         ec_slave[0].state = EC_STATE_OPERATIONAL;
         /* send one valid process data to make outputs in slaves happy*/
         ec_send_processdata();
         ec_receive_processdata(EC_TIMEOUTRET);
         /* request OP state for all slaves */
         ec_writestate(0);
         chk = 40;
         /* wait for all slaves to reach OP state */
         do
         {
            ec_send_processdata();
            ec_receive_processdata(EC_TIMEOUTRET);
            ec_statecheck(0, EC_STATE_OPERATIONAL, 50000);
         }
         while (chk-- && (ec_slave[0].state != EC_STATE_OPERATIONAL));
         if (ec_slave[0].state == EC_STATE_OPERATIONAL )
         {
            printf("Operational state reached for all slaves.\n");
            inOP = TRUE;
                /* cyclic loop */
            for(i = 1; i <= 10000; i++)
            {
               ec_send_processdata();
               wkc = ec_receive_processdata(EC_TIMEOUTRET);

                    if(wkc >= expectedWKC)
                    {
                        printf("Processdata cycle %4d, WKC %d , O:", i, wkc);

                        for(j = 0 ; j < oloop; j++)
                        {
                            printf(" %2.2x", *(ec_slave[0].outputs + j));
                        }

                        printf(" I:");
                        for(j = 0 ; j < iloop; j++)
                        {
                            printf(" %2.2x", *(ec_slave[0].inputs + j));
                        }
                        printf(" T:%"PRId64"\r",ec_DCtime);
                        needlf = TRUE;
                    }
                    osal_usleep(5000);

                }
                inOP = FALSE;
            }
            else
            {
                printf("Not all slaves reached operational state.\n");
                ec_readstate();
                for(i = 1; i<=ec_slavecount ; i++)
                {
                    if(ec_slave[i].state != EC_STATE_OPERATIONAL)
                    {
                        printf("Slave %d State=0x%2.2x StatusCode=0x%4.4x : %s\n",
                            i, ec_slave[i].state, ec_slave[i].ALstatuscode, ec_ALstatuscode2string(ec_slave[i].ALstatuscode));
                    }
                }
            }
            printf("\nRequest init state for all slaves\n");
            ec_slave[0].state = EC_STATE_INIT;
            /* request INIT state for all slaves */
            ec_writestate(0);
        }
        else
        {
            printf("No slaves found!\n");
        }
        printf("End simple test, close socket\n");
        /* stop SOEM, close socket */
        ec_close();
    }
    else
    {
        printf("No socket connection on %s\nExcecute as root\n",ifname);
    }
}

OSAL_THREAD_FUNC ecatcheck( void *ptr )
{
    int slave;
    (void)ptr;                  /* Not used */

    while(1)
    {
        if( inOP && ((wkc < expectedWKC) || ec_group[currentgroup].docheckstate))
        {
            if (needlf)
            {
               needlf = FALSE;
               printf("\n");
            }
            /* one ore more slaves are not responding */
            ec_group[currentgroup].docheckstate = FALSE;
            ec_readstate();
            for (slave = 1; slave <= ec_slavecount; slave++)
            {
               if ((ec_slave[slave].group == currentgroup) && (ec_slave[slave].state != EC_STATE_OPERATIONAL))
               {
                  ec_group[currentgroup].docheckstate = TRUE;
                  if (ec_slave[slave].state == (EC_STATE_SAFE_OP + EC_STATE_ERROR))
                  {
                     printf("ERROR : slave %d is in SAFE_OP + ERROR, attempting ack.\n", slave);
                     ec_slave[slave].state = (EC_STATE_SAFE_OP + EC_STATE_ACK);
                     ec_writestate(slave);
                  }
                  else if(ec_slave[slave].state == EC_STATE_SAFE_OP)
                  {
                     printf("WARNING : slave %d is in SAFE_OP, change to OPERATIONAL.\n", slave);
                     ec_slave[slave].state = EC_STATE_OPERATIONAL;
                     ec_writestate(slave);
                  }
                  else if(ec_slave[slave].state > EC_STATE_NONE)
                  {
                     if (ec_reconfig_slave(slave, EC_TIMEOUTMON))
                     {
                        ec_slave[slave].islost = FALSE;
                        printf("MESSAGE : slave %d reconfigured\n",slave);
                     }
                  }
                  else if(!ec_slave[slave].islost)
                  {
                     /* re-check state */
                     ec_statecheck(slave, EC_STATE_OPERATIONAL, EC_TIMEOUTRET);
                     if (ec_slave[slave].state == EC_STATE_NONE)
                     {
                        ec_slave[slave].islost = TRUE;
                        printf("ERROR : slave %d lost\n",slave);
                     }
                  }
               }
               if (ec_slave[slave].islost)
               {
                  if(ec_slave[slave].state == EC_STATE_NONE)
                  {
                     if (ec_recover_slave(slave, EC_TIMEOUTMON))
                     {
                        ec_slave[slave].islost = FALSE;
                        printf("MESSAGE : slave %d recovered\n",slave);
                     }
                  }
                  else
                  {
                     ec_slave[slave].islost = FALSE;
                     printf("MESSAGE : slave %d found\n",slave);
                  }
               }
            }
            if(!ec_group[currentgroup].docheckstate)
               printf("OK : all slaves resumed OPERATIONAL.\n");
        }
        osal_usleep(10000);
    }
}

int main(int argc, char *argv[])
{
   printf("SOEM (Simple Open EtherCAT Master)\nSimple test\n");

   if (argc > 1)
   {
      /* create thread to handle slave error handling in OP */
//      pthread_create( &thread1, NULL, (void *) &ecatcheck, (void*) &ctime);
      osal_thread_create(&thread1, 128000, &ecatcheck, (void*) &ctime);
      /* start cyclic part */
      simpletest(argv[1]);
   }
   else
   {
      printf("Usage: simple_test ifname1\nifname = eth0 for example\n");
   }

   printf("End program\n");
   return (0);
}`

**Comment by nakarlsson** [comment]
I think you've copy'n'pasted something not applicable for your use-case? 

//Explicitly set flags that are (probably) invalid in EEPROM
ec_slave[slave].SM[2].SMflags = 0x10024'

**Comment by KleveJ** [comment]
Thanks, that did fix the issue
