### ISSUE TITLE
How to use SOEM to parse ENI files

### ISSUE THREAD

**Issue by farawayfromhome** [OpenEtherCATsociety/SOEM#305]
According to the title, how do I use the ENI file to configure the master and slaves in soem?

**Comment by nakarlsson** [comment]
SOEM don't include support for XML or ENI parser. If you would add/implement that part you would be able to perform some of the requested operations like InitCmds and similar.

**Comment by farawayfromhome** [comment]
Thanks for your help.

**Comment by nakarlsson** [comment]
I think a xml component would be needed to make it possible to use different XML libraries implementing an ENI parsing API

**Comment by farawayfromhome** [comment]
Thank you very much for your answer. I also created a question in SOES society, and I would be very grateful if you can answer it.
