### ISSUE TITLE
SDO Error Code issues

### ISSUE THREAD

**Issue by farawayfromhome** [OpenEtherCATsociety/SOEM#306]
Hi All.
I am sorting out all the exceptions to EtherCAT. I don't know much about some error codes. For example, error code 0x05030000(the trigger bits not changed), is this error existed in COE? What is the reason for this errror? And how can I handle this error?

**Comment by ArthurKetels** [comment]
Please google first. You will get your info there. In short, this is CAN legacy, hard to find this message in the wild for EtherCAT.

**Comment by farawayfromhome** [comment]
Problem solved
