### ISSUE TITLE
Slaves lost in operational state

### ISSUE THREAD

**Issue by farawayfromhome** [OpenEtherCATsociety/SOEM#308]
Hi.
I've been fighting with the simple_test example.All the slaves can reach to OP, but when several cycles of process data are sent, all slaves are lost, which is a must. I don't know what caused it. Whether there are replies from the slaves station but the master does not receive them or the slaves do not reply at all.
![image](https://user-images.githubusercontent.com/49431284/59189252-32893780-8bac-11e9-9b5a-4e2524c482a2.png)
[ecat_capture.zip](https://github.com/OpenEtherCATsociety/SOEM/files/3271622/ecat_capture.zip)

**Comment by ArthurKetels** [comment]
All slaves are and remain in OP. All packets look ok. For some reason the simple_test loop does no longer see a correct working counter (=18). The recovery routine kicks in and restores all slaves (no need but anyway). This loop keeps running because the wkc remains not ok.

You could print the actual wkc to see what is being returned.

What OS and cpu are you using?

**Comment by farawayfromhome** [comment]
Thank you for your reply.
I did as you say to print the the actual wkc out.And I found that wkc suddenly became -1.
I use RTEMS 4.11 and Zynq7020.

![image](https://user-images.githubusercontent.com/49431284/59239360-c6eaad00-8c33-11e9-9d28-e9ded4041f17.png)

**Comment by ArthurKetels** [comment]
WKC -1 means that no valid frame was received. And from the wireshark trace we can see all frames have returned normal. So you will have to instrument nicdrv.c with debug info to trace down the issue. The routine in question is : int ecx_inframe(ecx_portt *port, int idx, int stacknumber)

**Comment by farawayfromhome** [comment]
Thanks.
As you suggested, I found that the program could not run into the ether isr_handler in freebsd when the data was not received. I will continue to trace this problem.

I have another problem, after I used ec_slave[slave_num].blockLRW = 1
The code:
expectedWKC = (ec_group[0].outputsWKC * 2) + ec_group[0].inputsWKC; 
should be changed to :
expectedWKC = ec_group[0].inputsWKC  ?

**Comment by farawayfromhome** [comment]
Problem solved
