### ISSUE TITLE
Problem with PDO Cycle

### ISSUE THREAD

**Issue by farawayfromhome** [OpenEtherCATsociety/SOEM#318]
When I debugged my code using RTEMS, I found that I sent the process data in a 1ms cycle, but the DC time interval actually read back was about 6ms. I used wireshark to capture data and found that the interval between each time I sent the data was really about 6ms. The same after I used simple_test.c.

![image](https://user-images.githubusercontent.com/49431284/60670977-97326c00-9ea4-11e9-878f-00d46eee3578.png)

[wireshark_capture.zip](https://github.com/OpenEtherCATsociety/SOEM/files/3359526/wireshark_capture.zip)

**Comment by ArthurKetels** [comment]
Looks like a granularity issue with your RTEMS scheduler. Can you test outside SOEM to see if you can make a task that runs 1ms? And what happens if you change your SOEM task to 2ms?

**Comment by farawayfromhome** [comment]
It's ‘printf’ cost too much time.Now I delete printf the interval is normal.

**Comment by nakarlsson** [comment]
Guess this is no issue anymore.

@farawayfromhome , please close not active Issues when they’ve been sorted out.
