### ISSUE TITLE
I think I broke settings the working slave device.

### ISSUE THREAD

**Issue by rasimckc** [OpenEtherCATsociety/SOEM#326]
Hi all,
I was connected to a 'Selema drive' before and did a 'simple test'.I didn't have a problem.I didn't run into a problem, but I couldn't test later when I connected.I may have written the wrong address when I first connected. So I think I've corrupted some settings.I reset the parameters from the drive, but it hasn't improved.

When I first connected to the drive with ethercat explorer, the name I saw was 'Selema_Device-1001'.In this case I could communicate and there was no problem.
![WhatsApp Image 2019-07-31 at 11 12 24 (1)](https://user-images.githubusercontent.com/43168362/62350481-83157500-b50b-11e9-9f9b-e422e0238a31.jpeg)
But now when I connect, the result is a complex name.
![WhatsApp Image 2019-07-31 at 11 17 26 (2)](https://user-images.githubusercontent.com/43168362/62350829-96751000-b50c-11e9-8b1e-d4af9be678da.jpeg)
The photo was taken from simple ethercat explorer.When I searched with 'Soem' I got the same result.
This is the name of the network when I searched.
![slaveinfo](https://user-images.githubusercontent.com/43168362/62352482-ece44d80-b510-11e9-8f1c-1a01d4f72480.PNG)
I can't test.
![Simple test](https://user-images.githubusercontent.com/43168362/62352524-04233b00-b511-11e9-917a-7ba52fa75984.PNG)
How do you think that happened?How do I fix it?
Thank you from now.

**Comment by nakarlsson** [comment]
Have you written the EEPROM? Eg filled it with a bad EEPROM data?

**Comment by rasimckc** [comment]
yes i wrote.I think I  filled eeprom with bad data.

**Comment by nakarlsson** [comment]
Then you need to reprogram it with correct data. Either with the actual EEPROM image via eepromtool or similar Or TwinCAT with help of the ESI.

**Comment by rasimckc** [comment]
@nakarlsson I fixed it through twincat as you said.Thank you

**Comment by rasimckc** [comment]
@yusufselimkaratas   Would you send Turkish mail to? :D cekic36@gmail.com
