### ISSUE TITLE
ALL_BUILD Unable to start program

### ISSUE THREAD

**Issue by yusufselimkaratas** [OpenEtherCATsociety/SOEM#327]
Hello everyone,

I have used cmake GUI and got output files and opened directly with VS 2017. Without any change I tried to use Local Windows Debugger and I got an error like  "Unable to start program ' C.\users\yusufSelim\Desktop\OUT\Debug\ALL_Build'" . It says that System can not find the file. Also I observed that Debug does not have any All Build. How can I solve this?

Thanks.

**Comment by rasimckc** [comment]
He,
right click then set as startUp project
![Untitled](https://user-images.githubusercontent.com/43168362/62358363-3a66b780-b51d-11e9-8fa4-6593b0300a61.png)
Will you try that?

**Comment by yusufselimkaratas** [comment]
Amazing. It works. If you come to Turkey, just write me. I own you a lunch. Thanks.

**Comment by rasimckc** [comment]
rica ederim Yusuf.
