### ISSUE TITLE
Constantly Changing 0x6040

### ISSUE THREAD

**Issue by yusufselimkaratas** [OpenEtherCATsociety/SOEM#332]
Hello,

I am trying to set 0x6040 - 0x0F and 0x60FF->0x250. But they are continuously changing. Even if I delete parameter setting codes, they are continuously changing. I am not usre about the PACK code. Results and relevant code is given below.

Thanks.

`typedef struct pdo
{
	uint16 value_6040;
	int32 value_60FF;

} out_pdo;

typedef struct in_pdo
{
	uint16 value_6041;
	int32 value_6064;
	int32 value_606C;
}in_pdo;

out_pdo *p;
	in_pdo *pin;

	uint16 index = 0x6040, data;
	uint8 subindex = 0x00;
	int counter = 0;

	init(argv[1]);
	while (TRUE)
	{
		ec_send_processdata();
		ec_receive_processdata(EC_TIMEOUTRXM);

		//OUTPUT SIDE

		p = (out_pdo*)ec_slave[1].outputs;
		p->value_6040 = 0x0F;
		p->value_60FF = 0xAAAA;

		int len = sizeof(data); data = 0;
		counter += ec_SDOread(1, 0x6040, subindex, FALSE, &len, &data, EC_TIMEOUTRXM);
		printf("Ind: %X ; Data : %X----", 0x6040, data);
		printf("PDO_O1: %X\n", p->value_6040);
		len = sizeof(data); data = 0;
		counter += ec_SDOread(1, 0x60FF, subindex, FALSE, &len, &data, EC_TIMEOUTRXM);
		printf("Ind: %X ; Data : %X----", 0x60FF, data);
		printf("PDO_O2: %X\n", p->value_60FF);

		//INPUT SIDE

		pin = (in_pdo*)ec_slave[1].inputs;
		

		len = sizeof(data); data = 0;
		counter += ec_SDOread(1, 0x6041, subindex, FALSE, &len, &data, EC_TIMEOUTRXM);
		printf("Ind: %X ; Data : %X----", 0x6041, data);
		printf("PDO_IN1: %X\n", pin->value_6041);
		len = sizeof(data); data = 0;
		counter += ec_SDOread(1, 0x6064, subindex, FALSE, &len, &data, EC_TIMEOUTRXM);
		printf("Ind: %X ; Data : %X----", 0x6064, data);
		printf("PDO_IN4: %X\n", pin->value_6064);
		len = sizeof(data); data = 0;
		counter += ec_SDOread(1, 0x606C, subindex, FALSE, &len, &data, EC_TIMEOUTRXM);
		printf("Ind: %X ; Data : %X----", 0x606C, data);
		printf("PDO_INC: %X\n", pin->value_606C);

`

![image](https://user-images.githubusercontent.com/25983571/62709573-4dd2c080-b9fe-11e9-8a6d-edc2c7abe7ce.png)

**Comment by AlSa-91** [comment]
Hey @yusufselimkaratas 
It seems I have the same issue at the moment. When I use the packed attribute my code doesn't run, but without packed it seems to change values which doesn't belong to the variable.
Long story short, how did you solved your problem?
Thank you ;)
