### ISSUE TITLE
SOEM + RTnet 

### ISSUE THREAD

**Issue by roboticsai** [OpenEtherCATsociety/SOEM#335]
Can anyone help me to integrate SOEM with RTnet xenomai? How do i use soem with rtnet. do anyone have source code of this implementation?

**Comment by ArthurKetels** [comment]
Why would you need xenomai? Mostly preemt-rt on Linux will do the job just as well.

**Comment by oPiZiL** [comment]
firstly you should  Build and install kernel with xenomai (propper rtnet driver of your NIC)

**Comment by oPiZiL** [comment]
https://github.com/orocos/rtt_soem

**Comment by nakarlsson** [comment]
seems to be inactive so we'll close it
