### ISSUE TITLE
Config of multiple slaves devices

### ISSUE THREAD

**Issue by ypearson** [OpenEtherCATsociety/SOEM#342]
I'm able to configuration two (identical) slaves on two different network interfaces using the hooking

ec_slave[1].PO2SOconfig = &akd_config;

However, when I daisy chain the slaves SOEM does recognize 2 slaves on the bus, but I get a Invalid Output Configuration on the second slave device and it never gets to OPERATIONAL. The code below is how I think you should configure the 1st and 2nd slave device. The configuration should be OK since it works individually. 

ec_slave[1].PO2SOconfig = &akd_config1;
ec_slave[2].PO2SOconfig = &akd_config1;

thanks,

**Comment by ArthurKetels** [comment]
Post a wireshark dump (zipped) of the configuration process with the invalid output configuration error. I have a look on what goes wrong. A listing of the akd_config1 function would also help.
