### ISSUE TITLE
SYNC telegram

### ISSUE THREAD

**Issue by ypearson** [OpenEtherCATsociety/SOEM#356]
Basic question: How does one send a SYNC telegram using the SOEM library?

Background: I'm sync cyclic position mode to move around servo.

thanks!

**Comment by ArthurKetels** [comment]
SYNC telegrams are for CANopen. EtherCAT does not use those but relies on Distributed Clocks. And those are handled automatically with SOEM. It is up to your application, on top of SOEM, to do something with it. Have a look at the red_test sample program. Further I suggest you read up on the basic functioning of EtherCAT. See : www.ethercat.org

**Comment by nakarlsson** [comment]
The purpose of ec_sync is to sync and keep it in sync, it can been i several ways and this is one way.
