### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by JulianSchneider** [OpenEtherCATsociety/SOEM#363]
Is there any further documentation and explanation to the library then just the tutorials.txt?

**Comment by nakarlsson** [comment]
This is it, please feel free to help out and improve the documentation.

**Comment by JulianSchneider** [comment]
I would love to! First I need to grasp the concepts though, before I can explain it to others :) 
Is it okay to setup a instance of https://readthedocs.org/ for SOEM, so we can work on improving the documentation?

**Comment by nakarlsson** [comment]
It is in progress
