### ISSUE TITLE
Does soem support Nuttx RTOS?

### ISSUE THREAD

**Issue by KevinHwangAi** [OpenEtherCATsociety/SOEM#365]
If nuttx can be supported, how can I migrate soem to nuttx?

**Comment by nakarlsson** [comment]
use an existing port that seems to fit nuttex, modify for nuttex.

You need a time reference, you need a way to send/recv layer 2 frames, you might need mutex support if you need threading support.
Look in the different ports, pick the one that seems to match nuttex the best, port it to nuttex.

Or you you can contact sales[a]rt-labs.com to get help as "professional services" package.

**Comment by KevinHwangAi** [comment]
@nakarlsson Thanks.I'll try.
