### ISSUE TITLE
PDO mapping 

### ISSUE THREAD

**Issue by KhloodAmin** [OpenEtherCATsociety/SOEM#369]
Hello , i have a basic question about EtherCAT slave , How i make sure that SOEM has made the right mapping for PDOS ? 
Here is the output from slaveInfo - sdo - map 
![Screenshot from 2020-02-16 10-27-13](https://user-images.githubusercontent.com/40704304/74601559-3872d900-50a8-11ea-841b-9642bdca6a6a.png)
![Screenshot from 2020-02-16 10-27-31](https://user-images.githubusercontent.com/40704304/74601560-39a40600-50a8-11ea-9541-3170d9aefc4e.png)
![Screenshot from 2020-02-16 10-27-40](https://user-images.githubusercontent.com/40704304/74601561-39a40600-50a8-11ea-82ac-0b3577ff1c55.png)
![Screenshot from 2020-02-16 10-28-25](https://user-images.githubusercontent.com/40704304/74601562-3a3c9c80-50a8-11ea-9eb0-8ad848773914.png)
![Screenshot from 2020-02-16 10-28-49](https://user-images.githubusercontent.com/40704304/74601563-3a3c9c80-50a8-11ea-8089-4112f4048ed3.png)

**Comment by nakarlsson** [comment]
It looks OK, if you can enter OP it also is a proof it is OK.

**Comment by KhloodAmin** [comment]
thank you for your response , i had another question regarding to this point , in the screens above it's mentioned that outputs are mapped to the address 0x000000 and inputs 0x0004 , when i run the simple test with wireshark the captured packets were logical read write from address 0x000000 and there is no mention to the input addresses, how ethercat get the inputs data ? 
[packets.txt](https://github.com/OpenEtherCATsociety/SOEM/files/4213167/packets.txt)

**Comment by nakarlsson** [comment]
Its in the same read/write frame, hence the name LRW that combine read/write, the length of the data should be 8 and start at 0x000000.

**Comment by KhloodAmin** [comment]
but inputs are mapped to 0x0004 according to - map output so to read inputs state LRD command must be executed at the address 0x0004 , am i wrong ? 
![Screenshot from 2020-02-16 10-27-13](https://user-images.githubusercontent.com/40704304/74654735-a811c280-5193-11ea-91e4-64ed0bd25a6b.png)

**Comment by nakarlsson** [comment]
You can read inputs with LRD at 0x0004 with length 4

or

You can perform a read & write action with LRW at 0x0000 with length 8

Both will update the inputs

**Comment by KhloodAmin** [comment]
got it , thank you
