### ISSUE TITLE
Custom PDO mapping for elmo twitters

### ISSUE THREAD

**Issue by muenchenstrasse** [OpenEtherCATsociety/SOEM#371]
Hello,

I am trying to create my own PDO mapping using SOEM. I have experience in using TwinCAT to do that and i must say, using twincat to do pdo mapping was very easy. You just need to click on the list of PDOs you want to map and the twincat does everything for you.

So usually my txpdo would consist of 0x1a04 and 0x1a13. I saw that from some other posts that 0x1a02 is fixed on sm2. Is there anyway that i can change it? I mean if twincat can change it, we can as well. :)

I have went through the tutorials, however i did not manage to get information out of it.

A short and brief example could help me a long mile! Thank you!

Mav

**Comment by nakarlsson** [comment]
Search for Elmo in Issues and you’ll find examples.

**Comment by muenchenstrasse** [comment]
> Search for Elmo in Issues and you’ll find examples.

Hello nakarlsson,
I did exactly that before i started the thread. Unfortunately i do not know which one to start because they are not want i would want.

**Comment by nakarlsson** [comment]
https://github.com/OpenEtherCATsociety/SOEM/issues/300 re-configure a drive.

**Comment by muenchenstrasse** [comment]
I have tried the example that you sent. In fact, i am trying to change the slaveinfo from the SOEM to see if my PDO mapping is successful.


void slaveinfo(char *ifname)
{
    int cnt, i, j, nSM;
    uint16 ssigen;
    int expectedWKC;


    //int32 ob2;int os;



    printf("Starting slaveinfo\n");

    /* initialise SOEM, bind socket to ifname */
    if (ec_init(ifname))
    {

        printf("ec_init on %s succeeded.\n",ifname);
        /* find and auto-config slaves */
        if ( ec_config_init(FALSE) > 0 )
        {
            for(i=1; i<=ec_slavecount;i++){
                printf("Slave %d has CA? %s\n", i,ec_slave[i].CoEdetails & ECT_COEDET_SDOCA ? "true":"false");
                ec_slave[i].CoEdetails ^= ECT_COEDET_SDOCA;
                printf("New slave %d has CA? %s\n",i, ec_slave[i].CoEdetails & ECT_COEDET_SDOCA ? "true":"false");
            }


            for( int cnt = 1 ; cnt <= ec_slavecount ; cnt++)
            {

                int ret = 0;
                int os;

                uint32 idx_rxpdo = 0x16010001;
                os=sizeof (idx_rxpdo);
                ret += ec_SDOwrite(cnt, 0x1c12, 0, TRUE, os, &idx_rxpdo, EC_TIMEOUTRXM);
                printf("RxPDO mapping object index %d = %04x ret=%d\n", cnt, idx_rxpdo, ret);

                uint32 idx_txpdo = 0x1a020001;
                os=sizeof (idx_txpdo);
                ret += ec_SDOwrite(cnt, 0x1c13, 0, TRUE, os, &idx_txpdo, EC_TIMEOUTRXM);
                printf("TxPDO mapping object index %d = %04x ret=%d\n", cnt, idx_txpdo, ret);

            }
            ec_config_map(&IOmap);

            ec_configdc();
            while(EcatError) printf("%s", ec_elist2string());
            printf("%d slaves found and configured.\n",ec_slavecount);
            expectedWKC = (ec_group[0].outputsWKC * 2) + ec_group[0].inputsWKC;
            printf("Calculated workcounter %d\n", expectedWKC);
            /* wait for all slaves to reach SAFE_OP state */
            ec_statecheck(0, EC_STATE_SAFE_OP,  EC_TIMEOUTSTATE * 3);
            if (ec_slave[0].state != EC_STATE_SAFE_OP )
            {
                printf("Not all slaves reached safe operational state.\n");
                ec_readstate();
                for(i = 1; i<=ec_slavecount ; i++)
                {
                    if(ec_slave[i].state != EC_STATE_SAFE_OP)
                    {
                        printf("Slave %d State=%2x StatusCode=%4x : %s\n",
                               i, ec_slave[i].state, ec_slave[i].ALstatuscode, ec_ALstatuscode2string(ec_slave[i].ALstatuscode));
                    }
                }
            }


            ec_readstate();
            for( cnt = 1 ; cnt <= ec_slavecount ; cnt++)
            {
                printf("\nSlave:%d\n Name:%s\n Output size: %dbits\n Input size: %dbits\n State: %d\n Delay: %d[ns]\n Has DC: %d\n",
                       cnt, ec_slave[cnt].name, ec_slave[cnt].Obits, ec_slave[cnt].Ibits,
                       ec_slave[cnt].state, ec_slave[cnt].pdelay, ec_slave[cnt].hasdc);
                if (ec_slave[cnt].hasdc) printf(" DCParentport:%d\n", ec_slave[cnt].parentport);
                printf(" Activeports:%d.%d.%d.%d\n", (ec_slave[cnt].activeports & 0x01) > 0 ,
                       (ec_slave[cnt].activeports & 0x02) > 0 ,
                       (ec_slave[cnt].activeports & 0x04) > 0 ,
                       (ec_slave[cnt].activeports & 0x08) > 0 );
                printf(" Configured address: %4.4x\n", ec_slave[cnt].configadr);
                printf(" Man: %8.8x ID: %8.8x Rev: %8.8x\n", (int)ec_slave[cnt].eep_man, (int)ec_slave[cnt].eep_id, (int)ec_slave[cnt].eep_rev);
                for(nSM = 0 ; nSM < EC_MAXSM ; nSM++)
                {
                    if(ec_slave[cnt].SM[nSM].StartAddr > 0)
                        printf(" SM%1d A:%4.4x L:%4d F:%8.8x Type:%d\n",nSM, etohs(ec_slave[cnt].SM[nSM].StartAddr), etohs(ec_slave[cnt].SM[nSM].SMlength),
                               etohl(ec_slave[cnt].SM[nSM].SMflags), ec_slave[cnt].SMtype[nSM]);
                }
                for(j = 0 ; j < ec_slave[cnt].FMMUunused ; j++)
                {
                    printf(" FMMU%1d Ls:%8.8x Ll:%4d Lsb:%d Leb:%d Ps:%4.4x Psb:%d Ty:%2.2x Act:%2.2x\n", j,
                           etohl(ec_slave[cnt].FMMU[j].LogStart), etohs(ec_slave[cnt].FMMU[j].LogLength), ec_slave[cnt].FMMU[j].LogStartbit,
                           ec_slave[cnt].FMMU[j].LogEndbit, etohs(ec_slave[cnt].FMMU[j].PhysStart), ec_slave[cnt].FMMU[j].PhysStartBit,
                           ec_slave[cnt].FMMU[j].FMMUtype, ec_slave[cnt].FMMU[j].FMMUactive);
                }
                printf(" FMMUfunc 0:%d 1:%d 2:%d 3:%d\n",
                       ec_slave[cnt].FMMU0func, ec_slave[cnt].FMMU1func, ec_slave[cnt].FMMU2func, ec_slave[cnt].FMMU3func);
                printf(" MBX length wr: %d rd: %d MBX protocols : %2.2x\n", ec_slave[cnt].mbx_l, ec_slave[cnt].mbx_rl, ec_slave[cnt].mbx_proto);
                ssigen = ec_siifind(cnt, ECT_SII_GENERAL);
                /* SII general section */
                if (ssigen)
                {
                    ec_slave[cnt].CoEdetails = ec_siigetbyte(cnt, ssigen + 0x07);
                    ec_slave[cnt].FoEdetails = ec_siigetbyte(cnt, ssigen + 0x08);
                    ec_slave[cnt].EoEdetails = ec_siigetbyte(cnt, ssigen + 0x09);
                    ec_slave[cnt].SoEdetails = ec_siigetbyte(cnt, ssigen + 0x0a);
                    if((ec_siigetbyte(cnt, ssigen + 0x0d) & 0x02) > 0)
                    {
                        ec_slave[cnt].blockLRW = 1;
                        ec_slave[0].blockLRW++;
                    }
                    ec_slave[cnt].Ebuscurrent = ec_siigetbyte(cnt, ssigen + 0x0e);
                    ec_slave[cnt].Ebuscurrent += ec_siigetbyte(cnt, ssigen + 0x0f) << 8;
                    ec_slave[0].Ebuscurrent += ec_slave[cnt].Ebuscurrent;
                }
                printf(" CoE details: %2.2x FoE details: %2.2x EoE details: %2.2x SoE details: %2.2x\n",
                       ec_slave[cnt].CoEdetails, ec_slave[cnt].FoEdetails, ec_slave[cnt].EoEdetails, ec_slave[cnt].SoEdetails);
                printf(" Ebus current: %d[mA]\n only LRD/LWR:%d\n",
                       ec_slave[cnt].Ebuscurrent, ec_slave[cnt].blockLRW);
                if ((ec_slave[cnt].mbx_proto & ECT_MBXPROT_COE) && printSDO)
                    si_sdo(cnt);
                if(printMAP)
                {
                    if (ec_slave[cnt].mbx_proto & ECT_MBXPROT_COE)
                        si_map_sdo(cnt);
                    else
                        si_map_sii(cnt);
                }
            }
        }
        else
        {
            printf("No slaves found!\n");
        }
        printf("End slaveinfo, close socket\n");
        /* stop SOEM, close socket */
        ec_close();
    }
    else
    {
        printf("No socket connection on %s\nExcecute as root\n",ifname);
    }
}

This is the information that i got back from the slaveinfo with -map on:

SOEM (Simple Open EtherCAT Master)
Slaveinfo
Starting slaveinfo
ec_init on enp0s31f6 succeeded.
Slave 1 has CA? true
New slave 1 has CA? false
RxPDO mapping object index 1 = 16040001 ret=0
TxPDO mapping object index 1 = 1a020001 ret=1
Time:  115014.424 SDO slave:1 index:1c12.00 error:08000000 General error
Time:  115014.433 SDO slave:1 index:1604.00 error:06020000 The object does not exist in the object directory
1 slaves found and configured.
Calculated workcounter 0
Not all slaves reached safe operational state.
Slave 1 State=12 StatusCode=  1e : Invalid input configuration

Slave:1
 Name:ModuleSlotsDrive
 Output size: 0bits
 Input size: 0bits
 State: 18
 Delay: 0[ns]
 Has DC: 1
 DCParentport:0
 Activeports:1.0.0.0
 Configured address: 1001
 Man: 0000009a ID: 01100002 Rev: 00120025
 SM0 A:1000 L: 256 F:00010026 Type:1
 SM1 A:1400 L: 256 F:00010022 Type:2
 SM2 A:1800 L: 256 F:00010064 Type:3
 SM3 A:1c00 L: 256 F:00010020 Type:4
 FMMUfunc 0:1 1:2 2:3 3:0
 MBX length wr: 256 rd: 256 MBX protocols : 0e
 CoE details: 2f FoE details: 01 EoE details: 01 SoE details: 00
 Ebus current: 0[mA]
 only LRD/LWR:0
PDO mapping according to CoE :
nSM value = 4
rdl value = 1
tSM value = 3
  SM2 outputs
     addr b   index: sub bitl data_type    name
rdl value = 1
tSM value = 4
  SM3 inputs
     addr b   index: sub bitl data_type    name
End slaveinfo, close socket
End program


Maybe I am doing something wrong but could you help me with this?


Mavarick
