### ISSUE TITLE
Slave firmware update

### ISSUE THREAD

**Issue by casinia** [OpenEtherCATsociety/SOEM#376]
Hi, all.
I recently read the code of firm_update.c and found it to be really useful to me.
I recently need to update the firmware of the slave through EtherCAT. After the master sends the firmware program to the slave, how does the slave update this program? I don't know much about the operation of the slave.
Thanks.

**Comment by nakarlsson** [comment]
If you're an ETG member you can get info from this FW upgrade guide.

https://www.ethercat.org/memberarea/download/ETG5003_2_V1i0i0_S_D_FwUpdate.pdf

**Comment by casinia** [comment]
Thanks.
I can close now.
