### ISSUE TITLE
COE Test file for SOEM

### ISSUE THREAD

**Issue by nshubham5741** [OpenEtherCATsociety/SOEM#380]
I am new to EtherCAT & CAN over Ethernet. I am trying to implement EtherCAT master on a ARM processor with linux booted on it. The Slave is a drive unit for motors and implements COE for communication.. Can someone please provide COE test example to get started...

**Comment by nakarlsson** [comment]
The method is generic but the data to uses is drive specific.

Check #379 for the method.

**Comment by nshubham5741** [comment]
Thank you.. I now got a better idea about SOEM library.. 

I am referring Erika documentation : http://www.erika-enterprise.com/wiki/index.php?title=EtherCAT_Master for controlling a drive.

Can you please let me know the correct general procedure for PDO mapping with SDO, and sending/ getting the input & output parameters to the drive?

**Comment by nakarlsson** [comment]
I guess you can combine the ERIKA documentation with #379 and you'll get close enough.
In the end SOEM is just  a library, you write the EtherCAT Master when it come to executing the controller loops and tasks.

**Comment by nakarlsson** [comment]
I'll close it
