### ISSUE TITLE
Using SOEM on Arduino Due

### ISSUE THREAD

**Issue by robin843** [OpenEtherCATsociety/SOEM#394]
Hi,

does somebody know if it is possible to use SOEM on an Arduino Due with an Ethernet Shield? I already tried to write osal/oshw/nicdrv files. When using **ec_config_init()** to detect all slaves it somehow run into problems. It detects all slaves but never finishes this method. It stucks at random positions in code after detecting slaves with **ecx_detect_slaves()** .

So I'm asking myself if it is in general possible to run SOEM on Arduino?

Thank you for your help!

Best regards,

Robin

**Comment by ArthurKetels** [comment]
512K Flash and 100K RAM are enough for SOEM, also the CortexM3 is more than powerful enough. But you should reduce the structure size a bit. This means less slaves and less deep buffers. For the rest there are no reasons why it should not work.

**Comment by nakarlsson** [comment]
Can we close this?

**Comment by robin843** [comment]
yes! Thank you very much!
