### ISSUE TITLE
has anyone run SOEM with lowlatency kernel 5.4.x?

### ISSUE THREAD

**Issue by tianshiz** [OpenEtherCATsociety/SOEM#411]
I'm investigating using SOEM over Etherlab on an Ubuntu 20.04 lowlatency kernel machine. From my exp with Etherlab, kernel updates severely impacts the build. my issue with etherlab was that due to limited support whenver the kernel updated, there was a chance that it would not work anymore without some patching/workaround.

Will SOEM be a much better experience?

**Comment by ArthurKetels** [comment]
In genral SOEM does not depend on the kernel version of Linux. It works just as well with other OS or even on bare-metal. As long there is a mechanism to read and write packets on a network interface SOEM is happy.

When you want real-time performance the general rule is "less OS is better". Bare-metal SOEM handles 50Khz easily with jitter <1us. Linux handles 5Khz when you know how and jitter around 10us. Windows does 500Hz with difficulty and jitter >1ms.

As on terminology from Linux,  vanilla kernel -> crazy high latency, "low latency" kernel -> very high latency, preempt-rt kernel -> high latency. Relative to hardware performance of course.
