### ISSUE TITLE
Unable to read and write SDO with CTB servo driver

### ISSUE THREAD

**Issue by joserubenh** [OpenEtherCATsociety/SOEM#416]
This post could be related to #178 and #203 

Symptoms:
1.- slaveinfo correctly retrieves the name of the device.
2.- slaveinfo -sdo does not retrieve the names of the objects and throws an error (see attached)
3.- simpletest: keeps cycling stating "ALL SLAVES RESUMED OPERATIONAL" (see attached)

Tried so far:
1.- Trying several versions of the kernel going back to 3.19 (vanilla and preempt_rt)
2.- Trying several versions of ubuntu (20,18,16 and 14)
3.- Tyring a different system (Acer Laptop with realtek card)
4.- Tried using a usb-c adapter with chip AX88179 (much simpler stack) 

Current System:
ThinkPad P52 XeonM 
5.4.47-rt28 GNU/Linux
SOEM: git master branch: (from ChangeLog file) Version 1.3.3 : 2018-02-02

Installed NIC.
[    1.492775] e1000e 0000:00:1f.6 eth0: (PCI Express:2.5GT/s:Width x1) e8:6a:64:b2:d6:ac
[    1.492792] e1000e 0000:00:1f.6 eth0: Intel(R) PRO/1000 Network Connection
[    1.492861] e1000e 0000:00:1f.6 eth0: MAC: 13, PHY: 12, PBA No: FFFFFF-0FF
[ 5124.054080] e1000e: eth0 NIC Link is Up 100 Mbps Half Duplex, Flow Control: None
[ 5124.054084] e1000e 0000:00:1f.6 eth0: 10/100 speed: disabling TSO

==>>> wireshark captures attached are using this NIC (eth1)
[    7.032804] ax88179_178a 4-1:1.0 eth1: register 'ax88179_178a'  ASIX AX88179 USB 3.0 Gigabit Ethernet, 
00:0e:c6:5f:67:ef
[   67.771791] ax88179_178a 4-1:1.0 eth1: ax88179 - Link status is: 1
[  429.512259] device eth1 entered promiscuous mode

Regarding #203 the reference code on /net/packet/af_packet.c   appears on my build as:
it appars that the patch is applied 
`
2930 if (sock->type == SOCK_DGRAM) {
2931                 offset = dev_hard_header(skb, dev, ntohs(proto), addr, NULL, len);
2932                 if (unlikely(offset < 0))
2933                         goto out_free;
2934         } else if (reserve) {
2935                 skb_reserve(skb, -reserve);
2936                 if (len < reserve + sizeof(struct ipv6hdr) &&
2937                     dev->min_header_len != dev->hard_header_len)
2938                         skb_reset_network_header(skb);
2939         }
The patch referenced by @ArthurKetels is applied. 

Note: on a note posted on #178 I stated that soem works with realtek NIC. It's not true. I was mistaken.

Attachments: wireshark captures along with the terminal output during those tests.
Thank you very much

[wireshark_captures.tar.gz](https://github.com/OpenEtherCATsociety/SOEM/files/4909142/wireshark_captures.tar.gz)

**Comment by ArthurKetels** [comment]
Looking at the wireshark traces there is nothing wrong with your master NIC or SOEM.

The slave however behaves less nicely. It states it supports CoE, but the first CoE request of object 0x1c00:00 gives the wrong answer, It should return the number of subindexes available for object 0x1c00 (and answer should be 0x04 (uint8_t)) but it responds with uint32 with value 0x00001c04. SOEM then stops the CoE mapping request (and should do so).

The slave states it does not support the object dictionary, so trying to do so anyway by slaveinfo -sdo will fail.

Via the eeprom SII interface SOEM manages to set-up the slave and bring it to OP state. But then the slave working counter is off by one. We expect 3 (one write FMMU with value 2 and one read FMMU with value 1), we see 2. Therefore the recovery function of SOEM kicks in and checks the slave application state (register 0x130). The result is that the slave is in OP and SOEM thinks all is OK again.

The slave firmware is clearly faulty and I would suggest to contact the slave manufacturer and ask for a firmware update to solve the issues. This slave is clearly not conformant to the EtherCAT standards.

**Comment by joserubenh** [comment]
Thank you.
