### ISSUE TITLE
Question about master transition to OP when some devices doesn't support OP state

### ISSUE THREAD

**Issue by asor** [OpenEtherCATsociety/SOEM#417]
Hello, 

I have one principal question about SOEM master. If there are slave devices on the bus which could not switch its state to SAFE_OP and OP is it possible master to go to OP state without error leaving these devices in PRE_OP and switching other to OP?

Thank you in advance!

**Comment by nakarlsson** [comment]
Sure, the master can continue to run with other slaves in OP. How to handle the ”error” is up to you, the expected working counter would be lower than expected, still up to you what is expected. The simple_test would try to act on this scenario as an error, but thats how it is written.

**Comment by asor** [comment]
Thank you for the answer.

**Comment by nakarlsson** [comment]
I'll close , write a new issue if you got more questions
