### ISSUE TITLE
Difference between ec_SDOwrite and ec_SDOxwrite?

### ISSUE THREAD

**Issue by stevedanomodolor** [OpenEtherCATsociety/SOEM#418]
I am trying to use setup some of the parameters for the Pdo mapping but cannot see the main difference between the ec_SDOwrite and ec_SDOxwrite, does the first map objects from the CoE object dictinary?, what difference does it make using the other one?

**Comment by nakarlsson** [comment]
Do you mean ecx_SDOwrite? Instead of ec_SDOxwrite. 

If, they do the same, the ecx_ version make use of the SOEM ver 2 API using a user instatiated context.

Either of the SDOWrite should work to write PDO config data.

**Comment by stevedanomodolor** [comment]
Yes, the ecx_sdowrite, please what do you mean by user instantiated context?

**Comment by stevedanomodolor** [comment]
Are there any examples of how to implement that context?

**Comment by nakarlsson** [comment]
You can check the SOEM ver 1 API instance in ethercatmain.c
Look for ecx_contextt  ecx_context and how it is setup.

Or

This FSoE sample, https://github.com/rtlabs-com/fsoe-soem-demo/tree/master/test/linux/fsoe_sample

**Comment by stevedanomodolor** [comment]
Thank you
