### ISSUE TITLE
Separate threads for SDO and state control

### ISSUE THREAD

**Issue by jespersmith** [OpenEtherCATsociety/SOEM#42]
On a general purpose CPU (Intel x86), is it recommended to do state control (PRE-OP -> .. -> OP) in a separate thread?

Also, because SDO requests are blocking, would those also be called from a separate thread and if yes, would this affect the main PDO communication?

**Comment by ArthurKetels** [comment]
Yes on both. On production code I use two threads, one for PDO communication with lowest latency, and one on lower priority that handles SDO, state machines, recovery and hot-plug.

SOEM is reentrant safe and has the right locks on the lowest network socket level. However do not split PDO transmissions of the same group in multiple threads.

**Comment by jespersmith** [comment]
Going to do that. Thanks.
