### ISSUE TITLE
Any plan to support EoE?

### ISSUE THREAD

**Issue by Helvethor** [OpenEtherCATsociety/SOEM#43]
Hi there,

are there any plans to support Ethernet over Ethercat in the futur ?
If not, do you have a link to the specs of the protocol. This would help me understand the code and maybe try to implement it if nobody wants to do it.

Have a nice day

**Comment by mheden** [comment]
We have it in the long time roadmap but when it will be implemented is dependent on the requirements of the projects we are working on.

You can find the specification in ETG1000/6.

**Comment by matwey** [comment]
I also would like to have EoE. But unfortunately, I don't access to the specs so even cannot try to implement it myself.
