### ISSUE TITLE
SOEM on control servo(IS620N), Can't change servo from SafeOP to OP

### ISSUE THREAD

**Issue by summerlotus513** [OpenEtherCATsociety/SOEM#442]
I'm trying to use SOEM to control the servo(IS620N), but when I set the servo to OP, It couldn't set the servo to the OP state. The servo is in safeop and program exit with "No error".
Is there something wrong with my process,? Can someone give me a code reference that can completely enable servo? 
Be deeply grateful!
[my slaveinfo]
![2020-08-31 17-40-33屏幕截图](https://user-images.githubusercontent.com/39475631/91707502-781b9100-ebb2-11ea-87a8-5a1d261b0492.png)
[my program print]
![2020-08-31 17-40-59屏幕截图](https://user-images.githubusercontent.com/39475631/91707569-97b2b980-ebb2-11ea-98dd-d7ff86c1add0.png)

**Comment by ArthurKetels** [comment]
Simple_test is not a good program to control servo slaves. I would suggest to read the tutorial. Also read the slave manual to see the exact requirements to enable operation. Some slaves need the sync0/1 pulses to be active and a master that send PDO packets synchronized with the sync pulses.

Where you able to control simpler slaves like digital I/O or analog outputs with success?

**Comment by summerlotus513** [comment]
> Simple_test is not a good program to control servo slaves. I would suggest to read the tutorial. Also read the slave manual to see the exact requirements to enable operation. Some slaves need the sync0/1 pulses to be active and a master that send PDO packets synchronized with the sync pulses.
> 
> Where you able to control simpler slaves like digital I/O or analog outputs with success?

Yes, I try update the simple_test to control the slave(AX58100 & LAN9252) in IO,it work.
But when I refer to some programs on the network to guide my servo(IS620N) ，it didn't work. I tried a lot of programming，but failed.
Somebody tell me when servo in safeop, I should enable the servo, then change to OP.
My servo follow the standard cia402 protocol. (The slave manual say: Boot the servo driver according to the standard cia402 protocol).
![企业微信截图_20200901105651](https://user-images.githubusercontent.com/39475631/91789768-de032980-ec41-11ea-96a1-3f315a3ad9b3.png)
I tried, but faild. servo can't be enabled in safeOP. 
So, I want konw, how to change servo(CiA402) to OP,or how to enable the servo.....Are there any procedures or information that I can refer to...
Thank you so much.

**Comment by toshisanro** [comment]
You need to change the   ecx_context.manualstatechange  value  from  0 to 1.  
![image](https://user-images.githubusercontent.com/43719517/128313364-20917562-e329-4518-854d-9090e87b90d4.png)

**Comment by toshisanro** [comment]
@summerlotus513   I have been engaged in the development of EtherCAT master （SOEM） for more than two years.Based on soem, I have realized multiple master , and I  can control Panasonic （A6B），elmo，STEP，inovance (IS620N)，tsino-dynatron（cooldrive  rc)  servo driver ,and beckhoff  IOs ( EK1100 ,EL1008,EL2008 etc). If you have technical requirements, please contact me.

**Comment by gvcode1** [comment]
@toshisanro Hi, how to contact you? Do you have email?

**Comment by toshisanro** [comment]
@gvcode1 my  email : toshisanro@163.com

**Comment by nakarlsson** [comment]
close due to inactivity

**Comment by brunogold** [comment]
@summerlotus513  were you able to get this resolved. I use the same AC drive and I believe I am in the same state :) Appreciate any help on this.
