### ISSUE TITLE
In red_test: add_timespec i.c.w. clock_nanosleep

### ISSUE THREAD

**Issue by jeroenbest** [OpenEtherCATsociety/SOEM#458]
Hi,

In SOEM/test/linux/red_test/red_test.c a function add_timespec is defined. The line

`if ( ts->tv_nsec > NSEC_PER_SEC )`

should be

`if ( ts->tv_nsec >= NSEC_PER_SEC )`

because later on, the clock_nanosleep uses this struct timespec ts. But according to the Linux man pages (https://man7.org/linux/man-pages/man2/clock_nanosleep.2.html) the nsec cannot be larger than 999999999.

BR,
Jeroen

**Comment by ArthurKetels** [comment]
Thanks, obviously correct.

**Comment by jeroenbest** [comment]
Same function is also used in ebox.c. Similar correction there is needed.

**Comment by nakarlsson** [comment]
Was addressed in #460
