### ISSUE TITLE
Setting digital Outputs with PDOs

### ISSUE THREAD

**Issue by joseyy** [OpenEtherCATsociety/SOEM#464]
Hi, I have a scope connected to my CoE Slave (Servo Controller), and I am toggling the digital outputs using SDOwrite. However, I would like to do this using the IOmap (PDOs), but I haven't had any luck. I set the .outputs with the value to turn the pins on and off and then use send_processdata and receive_process_data. I can verify that the values are being written with an SDOread but the outputs do not change. Any suggestions? 
The ethercat state machine is in OP, but the CiA DS402 state machine is in Switch ON Disabled (I am not sure if I need to get it to Operation Enabled in order to toggle the Digital Ouputs using PDOs)

**Comment by ArthurKetels** [comment]
I guess you answered your own question. Often DS402 slaves need to have the local state machine in an OP state in order to set digital outputs. But strictly it is undefined behavior and can change between different vendors.

**Comment by joseyy** [comment]
Thanks for replying back. As you said it might be undefined behavior but I thought since I am able to toggle the digital outputs using SDOwrite it wouldn't be a problem doing so using the IOmap. 

The problem is that I haven't been able to make the slave switch to Operation Enabled (which is the last state). I can, however, switch the slave all the way to Switch ON (the state before Operation Enabled) but when I send the command to switch to "Operation Enabled" it goes into the "Fault" state (this is more of a DS402 question than SOEM), **what are some of the things I should look at to find a solution to this problem?**

Note: The motor is connected to the slave and we are able to send commands to it using the software supplied by the vendor.

**Comment by ArthurKetels** [comment]
A bit more info could help to understand your problems. What slave? Post, ESI file of the slave, your code to bring the slave to OP and command the DS402 state machine, Wireshark dump of your last attempt.

As always, when something does not work, simplify. Try to set outputs on a simple slave with only digital outputs.

**Comment by nakarlsson** [comment]
Can we close this issue?

**Comment by joseyy** [comment]
Yes you can close it
