### ISSUE TITLE
Include problems when installing SOEM to /usr/local

### ISSUE THREAD

**Issue by jorritolthuis** [OpenEtherCATsociety/SOEM#470]
When SOEM is installed to `/usr/local` (but I assume this happens for any location), the installed header files are placed in `./include/soem/`. There seems to be a problem when including these header files in a C file.
I have tested this with version 1.4.0.

**Steps to reproduce**
1. Build SOEM and install it to `/usr/local`
```
$ mkdir build
$ cd build
$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
$ make
# make install
```
2. Create a C program (`/usr/local/include` is automatically searched by GCC)
```
#include <soem/ethercat.h>
int main()
{ return 0; }
```
3. Build the C program
```
$ gcc file.c -o program
In file included from /usr/local/include/soem/ethercat.h:22,
                 from file.c:1:
/usr/local/include/soem/ethercateoe.h:19:10: fatal error: ethercattype.h: No such file or directory
   19 | #include <ethercattype.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

The problem is that there is no `ethercattype.h` in `/usr/local/include` (or any other default include path).
I have temporarily resolved the issue by adding the `-I/usr/local/include/soem` flag to GCC, but I prefer a more permanent solution that does not pollute my build commands.

I think there are two possible solutions:
* Not placing the header files in a `soem/` subdirectory
* Prefixing `soem/` in the header file of the library

**Comment by ArthurKetels** [comment]
There is nothing stopping you to copy the header files in /usr/local/include. Or as an alternative fix the cmake and post the patch ;-)
