### ISSUE TITLE
NIC Flags Question

### ISSUE THREAD

**Issue by FraserG01** [OpenEtherCATsociety/SOEM#478]
Hello I was just wondering why these flags are required when configuring the network interface:
https://github.com/OpenEtherCATsociety/SOEM/blob/master/oshw/linux/nicdrv.c#L163

**Comment by ArthurKetels** [comment]
`ifr.ifr_flags = ifr.ifr_flags | IFF_PROMISC | IFF_BROADCAST;`
It is always a compromise how to set the network driver flags. It depends on the hardware layout and all kinds of network filters/firewalls. 

Promiscuous setting means that all network packets are allowed to pass. Some stacks filter out non IP packets (like EtherCAT). 

Broadcast setting means broadcast packets are allowed to pass. SOEM uses broadcast for destination MAC. This allows one to put a switch in-between and still have communication. However this is only for debugging. In production systems it is not recommended to have switches in-between the master and slaves. Another feature is that you could send EtherCAT over WiFi (totally not real-time).

**Comment by FraserG01** [comment]
Thanks the explanation Arthur!
