### ISSUE TITLE
Slave 1 State=0x04 StatusCode=0x0000 : No error

### ISSUE THREAD

**Issue by orivesky** [OpenEtherCATsociety/SOEM#485]
Hello!

I am trying to use the simple_test program on a servomotor. I have used another model of the same manufacturer and SOEM works pretty fine. However, on the new model it seems that it the conexion doesn't work, so I tried the simple_test and It gives me the error after some time: Slave 1 State=0x04 StatusCode=0x0000 : No error. 

I am attaching the wireshark just in case

[simple_test.zip](https://github.com/OpenEtherCATsociety/SOEM/files/6036074/simple_test.zip)

Do you know the reason? I thought that it would be the watchdog (0x0400, 0x0420), but nothing.

I am attaching the ESI just in case.

[ESI.zip](https://github.com/OpenEtherCATsociety/SOEM/files/6036087/ESI.zip)

Thanks!

**Comment by nakarlsson** [comment]
Run test slaveinfo with the -map option included to print som more stats

Have you tried running for a longer period, to see if it eventually report an actual error? 10s should be enough but you never know.
