### ISSUE TITLE
How to write octostring via ec_sdowrite?

### ISSUE THREAD

**Issue by kunijiwa03** [OpenEtherCATsociety/SOEM#488]
Hello, I am new to EtherCat and SOEM, and I am confused. I encountered a problem when using ec_SDOWrite. I don't know how to write octetstring to a subindex. For example, 0x8006:0x02 of EL6751 requires octetstring(12). Unfortunately, I did not find a corresponding solution.
My data is 00 81 01 00 00 FF 02 00 00 00 00 00, I am trying to deal with it this way:
     uint8 txpdo1[12] = {0x00,0x81, 0x01, 0x00, 0x00 ,0xFF, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00};
     int val = ec_SDOwrite(2, 0x8006, 0x01, FALSE, sizeof(txpdo1), &txpdo1, EC_TIMEOUTRXM);
What should I do?
good luck!

**Comment by ArthurKetels** [comment]
Looks OK. What is your response? Anything written in the error list? Please post a Wireshark trace. Sometimes the SDO write is only possible in specific states of the slave (f.e. pre-OP). Did you check the slave manual?

**Comment by kunijiwa03** [comment]
yeah, I wrote the SDO in the state of pre-OP just like the manual asked. And I tried to start the setup of EL6751 before  ec_config_map(), in this way the sampletest will end with "Slave 2 State=0x12 StatusCode=0x0025 : Invalid output mapping
". When I started the setup of EL6751 after the ec_configdc(), the sample will be executed but the PDOs is empty, and the can node status is incorrect. The slave address 0f EL6751 is 0x1002
 if (ec_init(ifname))


[wire.zip](https://github.com/OpenEtherCATsociety/SOEM/files/6060686/wire.zip)


   {
      printf("ec_init on %s succeeded.\n",ifname);
      /* find and auto-config slaves */


       if ( ec_config_init(FALSE) > 0 )
      {
         printf("%d slaves found and configured.\n",ec_slavecount);
         //

         ec_config_map(&IOmap);
         ec_configdc();
         EL6751setup();
         printf("Slaves mapped, state to SAFE_OP.\n");
         /* wait for all slaves to reach SAFE_OP state */
         ec_slave[2].state = EC_STATE_SAFE_OP;
         ec_writestate(2);
         ec_statecheck(0, EC_STATE_SAFE_OP,  EC_TIMEOUTSTATE * 4);
[wire.zip](https://github.com/OpenEtherCATsociety/SOEM/files/6060689/wire.zip)

**Comment by kunijiwa03** [comment]
Hi, Artur, I've tried to configure the EL6751 as you said, and now my question is the simpletest will end with "State=0x12 StatusCode=0x001e : Invalid input configuration".  Here is my configure codes: int EL6751setup(uint16 slave)
{
    uint8 ubuf8;
    uint16 ubuf16;
    uint32 ubuf32;


    ECAT_WRITE(2, 0x1C12, 0x00, ubuf8, 0x00, "disable entry");
    ECAT_WRITE(2, 0x1C13, 0x00, ubuf8, 0x00, "");
    //sync//
    ECAT_WRITE(2, 0x1C32, 0x02,  ubuf32, 0x003D0900, "set to Cycle time");
    ECAT_WRITE(2, 0x1C33, 0x03,  ubuf32, 0x00249F00, "set to Shift time");
    //start the el6751//
    ec_SDOwrite(2, 0xF800, 0x00, TRUE, sizeof(map_xf800), &map_xf800, EC_TIMEOUTRXM);
    //printf(ec_elist2string());

    CanOpenSlave(1);//0x8000,0x8006,0x8008,0x8003
[wire.zip](https://github.com/OpenEtherCATsociety/SOEM/files/6073781/wire.zip)



    //download txpdo//

    ECAT_WRITE(2, 0x1C12, 0x01, ubuf16, 0x1600,"");
    ECAT_WRITE(2, 0x1C12, 0x00, ubuf8, 0x01,"set 1");

    //download rxpdo//

    ECAT_WRITE(2, 0x1C13, 0x01, ubuf16, 0x1A00, "");
    ECAT_WRITE(2, 0x1C13, 0x02, ubuf16, 0x1A82, "");
    ECAT_WRITE(2, 0x1C13, 0x03, ubuf16, 0x1A83, "");
    ECAT_WRITE(2, 0x1C13, 0x04, ubuf16, 0x1A84, "");
    ECAT_WRITE(2, 0x1C13, 0x00, ubuf8, 0x04, "set 4");

    return 0;


       if ( ec_config_init(FALSE) > 0 )
      {
         printf("%d slaves found and configured.\n",ec_slavecount);
         //
         if(ec_slave[2].state != EC_STATE_PRE_OP)
         {
             ec_slave[2].state = EC_STATE_PRE_OP;
             ec_writestate(2);
         }
         printf("slave 2 state= 0x%2.2x\n",ec_slave[2].state);


         ec_slave[2].PO2SOconfig = &EL6751setup;
         ec_config_map(&IOmap);
         ec_configdc();

         ECAT_READ(2,0x1A8A,0x00,ubuf8,"");
         ECAT_READ(2,0x8008,0x00,ubuf8,"");
         printf("Slaves mapped, state to SAFE_OP.\n");
         /* wait for all slaves to reach SAFE_OP state */
         ec_slave[2].state = EC_STATE_SAFE_OP;
         ec_writestate(2);
         ec_statecheck(0, EC_STATE_SAFE_OP,  EC_TIMEOUTSTATE * 4);

         slaveinfo();//print slaveinfo
SOEM (Simple Open EtherCAT Master)
Simple test
Starting simple test
ec_init on ens33 succeeded.
2 slaves found and configured.
slave 2 state= 0x02
Slave: 2 - Read at 0x1a8a:0 => wkc: 1; data: 0x0 (0)	[]
Slave: 2 - Read at 0x8008:0 => wkc: 1; data: 0x4 (4)	[]
Slaves mapped, state to SAFE_OP.

Slave:1
 Name:EK1814
 Output size: 4bits
 Input size: 4bits
 State: 4
 Delay: 0[ns]
 Has DC: 1
 DCParentport:0
 Activeports:1.1.0.0
 Configured address: 1001
 Man: 00000002 ID: 07162c52 Rev: 00120000
 SM0 A:0f01 L:   1 F:00090044 Type:3
 SM1 A:1000 L:   1 F:00010000 Type:4
 FMMU0 Ls:00000000 Ll:   1 Lsb:0 Leb:3 Ps:0f01 Psb:0 Ty:02 Act:01
 FMMU1 Ls:00000012 Ll:   1 Lsb:0 Leb:3 Ps:1000 Psb:0 Ty:01 Act:01
 FMMUfunc 0:1 1:0 2:0 3:0
 MBX length wr: 0 rd: 0 MBX protocols : 00
 CoE details: 00 FoE details: 00 EoE details: 00 SoE details: 00
 Ebus current: -1000[mA]
 only LRD/LWR:0
PDO mapping according to SII :
  SM0 RXPDO 0x1608 Channel 5
     addr b   index: sub bitl data_type    name
  [0x0000.0] 0x7080:0x01 0x01 BOOLEAN      Output
  SM0 RXPDO 0x1609 Channel 6
     addr b   index: sub bitl data_type    name
  [0x0000.1] 0x7090:0x01 0x01 BOOLEAN      Output
  SM0 RXPDO 0x160A Channel 7
     addr b   index: sub bitl data_type    name
  [0x0000.2] 0x70A0:0x01 0x01 BOOLEAN      Output
  SM0 RXPDO 0x160B Channel 8
     addr b   index: sub bitl data_type    name
  [0x0000.3] 0x70B0:0x01 0x01 BOOLEAN      Output
  SM1 TXPDO 0x1A00 Channel 1
     addr b   index: sub bitl data_type    name
  [0x0012.0] 0x6000:0x01 0x01 BOOLEAN      Input
  SM1 TXPDO 0x1A01 Channel 2
     addr b   index: sub bitl data_type    name
  [0x0012.1] 0x6010:0x01 0x01 BOOLEAN      Input
  SM1 TXPDO 0x1A02 Channel 3
     addr b   index: sub bitl data_type    name
  [0x0012.2] 0x6020:0x01 0x01 BOOLEAN      Input
  SM1 TXPDO 0x1A03 Channel 4
     addr b   index: sub bitl data_type    name
  [0x0012.3] 0x6030:0x01 0x01 BOOLEAN      Input

Slave:2
 Name:EL6751
 Output size: 136bits
 Input size: 264bits
 State: 18
 Delay: 155[ns]
 Has DC: 1
 DCParentport:1
 Activeports:1.0.0.0
 Configured address: 1002
 Man: 00000002 ID: 1a5f3052 Rev: 00120000
 SM0 A:1800 L: 558 F:00010026 Type:1
 SM1 A:1a2e L: 558 F:00010022 Type:2
 SM2 A:1000 L:  17 F:00010026 Type:3
 SM3 A:1400 L:  33 F:00010022 Type:4
 FMMU0 Ls:00000001 Ll:  17 Lsb:0 Leb:7 Ps:1000 Psb:0 Ty:02 Act:01
 FMMU1 Ls:00000013 Ll:  33 Lsb:0 Leb:7 Ps:1400 Psb:0 Ty:01 Act:01
 FMMUfunc 0:1 1:3 2:3 3:0
 MBX length wr: 558 rd: 558 MBX protocols : 0d
 CoE details: 23 FoE details: 01 EoE details: 00 SoE details: 00
 Ebus current: 300[mA]
 only LRD/LWR:0
PDO mapping according to CoE :
  SM2 outputs
     addr b   index: sub bitl data_type    name
  [0x0001.0] 0x7000:0x01 0x10 OCTET_STRING CAN RxPDO 001
  [0x0003.0] 0x7000:0x02 0x18 OCTET_STRING CAN RxPDO 002
  [0x0006.0] 0x7000:0x03 0x30 OCTET_STRING CAN RxPDO 003
  [0x000C.0] 0x7000:0x04 0x30 OCTET_STRING CAN RxPDO 004
  SM3 inputs
     addr b   index: sub bitl data_type    name
  [0x0013.0] 0x6000:0x01 0x10 OCTET_STRING CAN TxPDO 001
  [0x0015.0] 0x6000:0x02 0x18 OCTET_STRING CAN TxPDO 002
  [0x0018.0] 0x6000:0x03 0x30 OCTET_STRING CAN TxPDO 003
  [0x001E.0] 0x6000:0x04 0x30 OCTET_STRING CAN TxPDO 004
  [0x0024.0] 0x0000:0x00 0x0B
  [0x0025.3] 0xF101:0x0C 0x01 BOOLEAN      SYNC Toggle
  [0x0025.4] 0xF101:0x0D 0x01 BOOLEAN      Device Diag
  [0x0025.5] 0x0000:0x00 0x01
  [0x0025.6] 0xF101:0x0F 0x01 BOOLEAN      PDO Toggle
  [0x0025.7] 0xF101:0x10 0x01 BOOLEAN      PDO State
  [0x0026.0] 0xF101:0x11 0x10 UNSIGNED16   Cycle Counter
  [0x0028.0] 0xF101:0x12 0x08 UNSIGNED8    Slave Status Counter
  [0x0029.0] 0x0000:0x00 0x08
  [0x002A.0] 0xF101:0x14 0x10 UNSIGNED16   Cycle Time
  [0x002C.0] 0x0000:0x00 0x10
  [0x002E.0] 0xF108:0x21 0x08 UNSIGNED8    RX error counter
  [0x002F.0] 0xF108:0x22 0x08 UNSIGNED8    TX error counter
  [0x0030.0] 0xF108:0x01 0x01 BOOLEAN      Bus-Off
  [0x0030.1] 0xF108:0x02 0x01 BOOLEAN      warning limit reached
  [0x0030.2] 0xF108:0x03 0x01 BOOLEAN      RX overflow
  [0x0030.3] 0x0000:0x00 0x01
  [0x0030.4] 0xF108:0x05 0x01 BOOLEAN      TX overflow
  [0x0030.5] 0xF108:0x06 0x01 BOOLEAN      Ack error
  [0x0030.6] 0x0000:0x00 0x02
  [0x0031.0] 0x0000:0x00 0x08
  [0x0032.0] 0x0000:0x00 0x10
segments : 1 : 52 0 0 0
Request operational state for all slaves
Calculated workcounter 6
slave 2 state= 0x04
slave 2 state= 0x04
Not all slaves reached operational state.
Slave 2 State=0x12 StatusCode=0x001e : Invalid input configuration

Request init state for all slaves
End simple test, close socket
End program

And I faild to find out the difference between SOEM and Twincat, here is the wireshark.

**Comment by ArthurKetels** [comment]
Your Wireshark files are filtered. Please do not do that. To be useful I need all data captured.

**Comment by kunijiwa03** [comment]
[wire.zip](https://github.com/OpenEtherCATsociety/SOEM/files/6074648/wire.zip)
Thank you for your reply, it's a complete Wireshark file including SOEM and twincat.

**Comment by ArthurKetels** [comment]
There is something wrong with SM3 size calculation. SOEM reads the mapping with CA (complete access). TwinCAT calculates 35 bytes correct and SOEM only 33 bytes. I have to dig deeper why, but for now disable CA.

After ec_config_init() but before ex_config_map() you can do
ec_slave[n].CoEdetails &= ~ECT_COEDET_SDOCA;
to clear the Complete Access bit in the CoE capabilities list for slave n.

**Comment by nakarlsson** [comment]
The SM2,3 flags don't look to be correct. All is configured in one buffer mode?

**Comment by ArthurKetels** [comment]
Actually slaves often use 1 buffer mode when in DC sync mode. There is no need for a triple buffer, master and slave are in sync after all :-)

**Comment by kunijiwa03** [comment]
Hi Arthur, I tried the code as you said, it didn't fix this problem.

**Comment by ArthurKetels** [comment]
Can you post a Wireshark trace? Perhaps one problem is solved and now we have another one.

**Comment by kunijiwa03** [comment]
Hi Arthur, Inspired by the different sizes of SM3 you said, I fixed this problem. I checked the process Data in twincat and the pdo map in SOEM, found that 0x1A82 and 0x1A83 are not in the map list of SOEM. So I delete the "ECAT_WRITE(2, 0x1C13, 0x02, ubuf16, 0x1A82, "");
ECAT_WRITE(2, 0x1C13, 0x03, ubuf16, 0x1A83, "");".Since it's not key information in my system, I choose to give up.
Thank you a lot!

**Comment by kunijiwa03** [comment]
Hi Arthur, recently, I encountered a new problem. After running for a period of time, my program will enter a strange state: using ec_ slave [3]. state reads that the slave status is op, but the slave LED indicates that the slave is in safe-OP. Do you know what happened? Thank you for any improvement!

**Comment by ArthurKetels** [comment]
Did you first issue a ec_readstate(3) for the slave? Otherwise the state is not updated in SOEM.

**Comment by kunijiwa03** [comment]
Thank you! I've fixed this problem.
