### ISSUE TITLE
Safe Op success but Work Counter is 0 on one particular drive

### ISSUE THREAD

**Issue by VitalSys** [OpenEtherCATsociety/SOEM#502]
We have yet another obscure error and are forced to ask for help. Spent quite a few weeks trying to diagnose the problem that happens on a particular drive. We have so far been able to run SOEM on multiple brands.

Posting the Wireshark for both SOEM(not working) and Twin CAT ( working ) [WireShark.zip](https://github.com/OpenEtherCATsociety/SOEM/files/6354205/WireShark.zip)

The drive goes into safe op but errors out immediately due to work counter being 0. 

Any advice is much appreciated.

**Comment by ArthurKetels** [comment]
Your slave is using 1-buffer system for PDO. Therefore it must be used in DC sync mode. You have to prepare the master to cope with this. There are strict rules to work by. Your test code is not going to work. Read https://github.com/OpenEtherCATsociety/SOEM/issues/487#issuecomment-786245585
