### ISSUE TITLE
No packets sent from master (Ubuntu 20.04)

### ISSUE THREAD

**Issue by xmuller** [OpenEtherCATsociety/SOEM#506]
Hi,

I was trying to run `slaveinfo` on my machine (root), but no packets seems to be sent (nothing on wireshark).

Command;
```bash
 ./slaveinfo eth0
 ```

Response: 
 ``` 
SOEM (Simple Open EtherCAT Master)
Slaveinfo
Starting slaveinfo
ec_init on eth0 succeeded.
No slaves found!
End slaveinfo, close socket
End program
```

Does anyone have a similar issue on Ubuntu 20.04 ?

**Comment by ArthurKetels** [comment]
It is unlikely you have eth0 as a network interface name on ubuntu 20.04 (with default install). What is your ifconfig output?

**Comment by xmuller** [comment]
Sorry for this late reply... I wasn't able identify a repeatable issue but it seems to be only related to my Ubuntu configuration. Nothing to do with SOEM. Also I don't know why I wrote `eth0`, i was using the correct interface `enx00e04c681e57` also sorry for that.
