### ISSUE TITLE
ec_receive_processdata() fails after all slaves reach EC_STATE_OPERATIONAL

### ISSUE THREAD

**Issue by hsyis** [OpenEtherCATsociety/SOEM#509]
We are trying to control an `Elmo platinum drive` with SOEM on Ubuntu 20.04.
As a result of running simple_test, `ec_receive_processdata()` fails after all slaves reach `EC_STATE_OPERATIONAL`.

Seeing that the `ec_config_init()` call succeeds, there seems to be no problem finding the slave.
But we can't find the cause of the `ec_receive_processdata()` failing.

We referenced the past issues and applied the patch posted on #224, and tried calling `ec_dcsync01()` on #468, but none of them worked.
Please give us some advice on what else to do. Thank you very much for your help.

slaveinfo output:
[slaveinfo_map.txt](https://github.com/OpenEtherCATsociety/SOEM/files/6446018/slaveinfo_map.txt)

simple_test output:
[simple_test.txt](https://github.com/OpenEtherCATsociety/SOEM/files/6446017/simple_test.txt)

wireshark capture:
[simple_test_pcapng.zip](https://github.com/OpenEtherCATsociety/SOEM/files/6446016/simple_test_pcapng.zip)

**Comment by ArthurKetels** [comment]
Can you post the ESI XML file?

**Comment by hsyis** [comment]
Thanks for the quick reply.
I requested the ESI XML file from the manufacturer, so I will upload it soon and let you know.

**Comment by hsyis** [comment]
@ArthurKetels Thank you for your help. Here is the ESI file.

ESI file:
[ElmoPlatinum_12_V60025.zip](https://github.com/OpenEtherCATsociety/SOEM/files/6449050/ElmoPlatinum_12_V60025.zip)

**Comment by ArthurKetels** [comment]
We had a similar question before: #377
This slave has a TI microcontroller with PRU's that emulate an EtherCAT ESC. They exhibit some quirks. The solution is to use overlapped PDO mapping.  See also tutorial.txt in the doc folder. 
The mapping function to use:
`int ec_config_overlap_map(void *pIOmap);`

**Comment by hsyis** [comment]
@ArthurKetels Thanks for your guide. I added the mapping function `ec_config_overlap_map()` and it works fine.

And I have some questions.

1. How can I check if the slave has TI ESC? The product manual doesn't seem to have that content. Is there any way to check with the `slaveinfo` tool?
2. Looking at the TI manual ([PRU-ICSS EtherCAT Slave Troubleshooting Guide.pdf](https://github.com/OpenEtherCATsociety/SOEM/files/6451536/PRU-ICSS.EtherCAT.Slave.Troubleshooting.Guide.pdf)), it is said that the more slaves, the greater the delay when using legacy iomap. In general, can I think that overlapping iomap is essential?

**Comment by hsyis** [comment]
Thanks for the answer. It was a great help.
