### ISSUE TITLE
elmo drive warning in status word doesnot move

### ISSUE THREAD

**Issue by 2-infinityandbeyond** [OpenEtherCATsociety/SOEM#518]
hi i have been trying to run a elmo drive with soem. was able to run 2 at a time before.
now i have got new drive and it return 0x12b7 as the status word. the drive doesnot accept any command after that.
when  using the elmo software it runs given that i ahve not run my code before that on the other hand if we restart the drive the elmo drive is runnable with the elmo software.
need help urgent

**Comment by ArthurKetels** [comment]
If you could first explain how this is a SOEM issue and not an Elmo issue? What does the returned status code mean?

**Comment by nakarlsson** [comment]
@2-infinityandbeyond , can this issue be closed?

**Comment by nakarlsson** [comment]
close due to inactivity
