### ISSUE TITLE
some problems with "the linux sync point 50us later than DC sync"

### ISSUE THREAD

**Issue by huyu168** [OpenEtherCATsociety/SOEM#519]
I have seen that the example red_test.c set the linux sync point 50us later than DC sync

void ec_sync(int64 reftime, int64 cycletime , int64 *offsettime)
{
   static int64 integral = 0;
   int64 delta;
   /* set linux sync point 50us later than DC sync, just as example */
   delta = (reftime - 50000) % cycletime;
   if(delta> (cycletime / 2)) { delta= delta - cycletime; }
   if(delta>0){ integral++; }
   if(delta<0){ integral--; }
   *offsettime = -(delta / 100) - (integral / 20);
   gl_delta = delta;
}
I would know can i set the linux sync point before than  DC sync? Or the reasons for the  50us later than DC sync?
and i find the picture below:
![image](https://user-images.githubusercontent.com/22394422/120188624-ecba5380-c248-11eb-8ebf-d80ac271a10f.png)
i think the sm2 event  is the linux sync point.
it seems that "set the linux sync point before than  DC sync" works.

**Comment by ArthurKetels** [comment]
From the code: 
/ set linux sync point 50us later than DC sync, _just as example_
You can set the sync point as you like. F.e. if the cycle time is 1000us, you can set it at 0, 50, 500, 999. Of course -200 is equal to +800, it is a relative time. It is up to you to find the optimal offset.

The Linux sync point is slightly earlier than SM2 event. The packet first has to be assembled, transferred over the wire and accepted by the EtherCAT slave (delay depending on number of slaves before and wire length).

**Comment by huyu168** [comment]
Thank you very much for your reply！
