### ISSUE TITLE
Need assistance to Beckhoff EL3681

### ISSUE THREAD

**Issue by Frank-1964** [OpenEtherCATsociety/SOEM#545]
Does anyone have experience with the Beckhoff EL3681?
It's a multimeter card and I like to disable the autorange function.
The manual says: The Autorange function is deactivated if the measuring range is not transferred (Tx PDO 0x1A00] selected) and "scaled" view is not active.
I have no idea how to do this with SOEM.
Anybody out there who can help me?

**Comment by nakarlsson** [comment]
@Frank-1964 , can we close this issue?

**Comment by nakarlsson** [comment]
Clsoe due to inactivity
