### ISSUE TITLE
Non First Slave errors out on some brands.

### ISSUE THREAD

**Issue by VitalSys** [OpenEtherCATsociety/SOEM#547]
Hello

Having another peculiar issue on some slave brands the non first slaves error out. The only peculiar thing I noticed was the EtherCAT frame where it errors out, dc time is off by 4 micro seconds which is not that much. Is there a tolerance for EtherCAT comms? I'm sure some jitter is acceptable as most slaves have no issue with it.
Cycle time is 1ms. 1 slaves works good all by itself. 
Attaching the Wireshark capture spent quite some time trying to diagnose the problem any help is appreciated.

[wireshark.zip](https://github.com/OpenEtherCATsociety/SOEM/files/7069555/wireshark.zip)

**Comment by ArthurKetels** [comment]
Please read https://github.com/OpenEtherCATsociety/SOEM/issues/487#issuecomment-786245585 .

You have assigned a SYNC0 pulse generator to both slaves but you did not first synchronize slave 2 to slave 1. And probably did not synchronize the master to slave 1. In this scenario master and slaves run at slightly different clock rates and are bound to cross the maximum jitter threshold. Slave to slave synchronization is automatic and will lock after a while of sending clock distributions (but can take many seconds). But master to slave synchronization is up to you. Have a look at the red_test example.

**Comment by nakarlsson** [comment]
Closed due to inactivity
