### ISSUE TITLE
EtherCat EoE.c

### ISSUE THREAD

**Issue by Caney-McStotts** [OpenEtherCATsociety/SOEM#549]
Where can I find help implementing EtherCat EoE. I have everything else working perfectly, just can't find any help on the EoE...

**Comment by Caney-McStotts** [comment]
https://github.com/OpenEtherCATsociety/SOEM/blob/master/test/linux/eoe_test/eoe_test.c

-Thank you for providing me with this link. I am posting it here, increase anyone else search's for it here. If wrong place to post pls delete.

**Comment by nakarlsson** [comment]
Can we close this issue? We'll work on making EoE solutions more available

**Comment by Caney-McStotts** [comment]
Yes please 

Thanx,
Caney McStotts
