### ISSUE TITLE
Problem with ec_init() under VxWorks

### ISSUE THREAD

**Issue by HolgerNie** [OpenEtherCATsociety/SOEM#57]
I am trying to start the SOEM software under VxWorks 6.9. Compilation works fine I am using the Linux version. I do not have any undefined symbols after loading and starting the application. After starting the application I always have a problem with the bind() function in ecx_setupnic( in nicdrv.c) which returns with error 45 (S_errno_EOPNOTSUPP). Any ideas?

**Comment by nakarlsson** [comment]
Best guess is VxWorks don't support some socket option, PF_PACKET? We have a not yet released VxWork port that use the L2 mux API, I believe that is the easiest way.

**Comment by HolgerNie** [comment]
I was in contact with WRS and after installing 6.9.4 the bind() works. However I am not able to see a slave with slaveinfo.c. I will test in the next days with wireshark if data are going out and something is coming back from my WAGO slave.

**Comment by HolgerNie** [comment]
My master does now send data but I do not have any response form the slave. Any idea what the probl is?

![ethercat_01](https://cloud.githubusercontent.com/assets/12135505/18171469/71d58834-7062-11e6-868b-36e4450d91df.PNG)

**Comment by ArthurKetels** [comment]
From your screen capture I can see you have a good receive. All packets shown are received packages (WC = 1). Somehow they are not fed into the SOEM stack.

**Comment by nakarlsson** [comment]
I don't think VxWorks and sockets are the way to go, look into muxLib.

**Comment by HolgerNie** [comment]
@ArthurKetels This is a wireshark sreenshot are you shure that these packages are the answer from the salve? 

@nakarlsson Do you have a example code with the muxLib? I have never used that lib before.

**Comment by nakarlsson** [comment]
Yes it is answers from an EtherCAT slave, the WC = 1 so it is a response.

**Comment by HolgerNie** [comment]
Yes, it is the answer form the slave my fault. Attched waht the master send out. I will check with WRS why I do not receive the date on the socket the next days.

![ethercat_02](https://cloud.githubusercontent.com/assets/12135505/18193719/92900a62-70e0-11e6-8ef5-890ea3907c11.PNG)

**Comment by HolgerNie** [comment]
I have now the EtherCAT running with VxWorks 6.9 target. I used all Linux version files. What is needed is VxWorks 6.9.4.9 as a minimum because from that version on bind() is supporting raw sockets. I have update the nicdriv.c(Linux version) so that it is running with VxWorks. 

To let VxWorks transfer receive EtherCAT raw packages a change in ..\components\ip_net2-6.9\ipcom\port\src\ipcom_drv_eth.c must be done too.

See attached files

[VxWorks_nicdrv.zip](https://github.com/OpenEtherCATsociety/SOEM/files/456390/VxWorks_nicdrv.zip)
