### ISSUE TITLE
Tutorial.txt

### ISSUE THREAD

**Issue by msevnctkn** [OpenEtherCATsociety/SOEM#587]
is there any work on tutorial.txt to improve? Because when some things are clear but some things are not clear. For example, cyclic position control for any servo motor, etc.
thanks a lot.

**Comment by ArthurKetels** [comment]
Well, you are welcome to write a few chapters :-)

**Comment by msevnctkn** [comment]
If I was capable of doing this, I would definitely do it. :)

**Comment by nakarlsson** [comment]
It will happen when it happens
