### ISSUE TITLE
CMakeLists.txt error

### ISSUE THREAD

**Issue by ArunbAk** [OpenEtherCATsociety/SOEM#591]
Hi everyone,

I am trying to run an EtherCAT motor using the package 
I am using Melodic 18.04 and cloned the package in the following path

_~/catkin_ws/src/SOEM_ 

then I ran `sudo ./simple_test.c eno1`  
where eno1 is the port where I connected my Drive and PC 

but I am facing the errors ( I have attached the screenshot) 

```
./simple_test.c: 1: ./simple_test.c: /bin: Permission denied
./simple_test.c: 2: ./simple_test.c: CMakeLists.txt: not found
./simple_test.c: 3: ./simple_test.c: CMakeLists.txt: not found
./simple_test.c: 4: ./simple_test.c: CMakeLists.txt: not found
./simple_test.c: 5: ./simple_test.c: CMakeLists.txt: not found
./simple_test.c: 6: ./simple_test.c: CMakeLists.txt: not found
./simple_test.c: 7: ./simple_test.c: CMakeLists.txt: not found
./simple_test.c: 8: ./simple_test.c: CMakeLists.txt: not found
./simple_test.c: 9: ./simple_test.c: Syntax error: word unexpected (expecting ")")
```

![Screenshot from 2022-02-17 21-26-39](https://user-images.githubusercontent.com/59391363/154519917-b1497ea5-94be-4247-a55d-4aa65775ce97.png)

Kindly help me to solve this issue. 

Regards,
Arunkumar

**Comment by ArthurKetels** [comment]
Did you follow the README.md? From your description it looks like you tried to import the repo as a ROS package. For ROS there is a separately maintained fork of SOEM.

**Comment by ArunbAk** [comment]
Yes I am.
I followed  the instructions in Readme.md

I cloned the package in my workspace.
Is that right??
Correct me if I am wrong



Regards,
ARUNKUMAR B

**Comment by ArthurKetels** [comment]
Well, if you followed the readme then you would have compiled the lib and test executables. The executables are in the build directory. You can not execute a source file as you are trying. simple_test.c needs to be compiled before you can run it.

**Comment by ArunbAk** [comment]
Yeah thank you. 
I have been trying to run the source file.
I ran the executable in the build directory.

But Still my motor is not moving ( using Sanyodenki drive and motor)

**Comment by ArthurKetels** [comment]
> But Still my motor is not moving ( using Sanyodenki drive and motor)

No of course not. Simple_test does not do anything with your slave, it is just a minimal example of how to use some basic functions of SOEM. SOEM is a library, and you are responsible to program an actual useful application. Your program needs to address all set-up requirements of the slave, the computer synchronisation, the control logic, etc.

I recommend reading up on the subject. EtherCAT in general, your slave manual, comments from other users on this site, etc.

**Comment by nakarlsson** [comment]
Close due to inactivity
