### ISSUE TITLE
How to use a device with garbage data in read-only 0x160x and 0x1A0x?

### ISSUE THREAD

**Issue by pingplug** [OpenEtherCATsociety/SOEM#598]
I got an EtherCAT IO module recently.
but this device failed to work after running `slaveinfo`.
I found `ecx_config_map_group` returned a wrong size of PDO.

[slaveinfo.txt](https://github.com/OpenEtherCATsociety/SOEM/files/8198500/slaveinfo.txt)

the data in 0x160x and 0x1A0x is garbage, and they are read only.
the right data is in this XML file

[SC-MD1616E.xml.zip](https://github.com/OpenEtherCATsociety/SOEM/files/8198522/SC-MD1616E.xml.zip)

how can I set right PDO mapping?

**Comment by ArthurKetels** [comment]
The output from slaveinfo shows a very broken slave firmware. The ESI file shows it has CompleteAccess bit set. Can your retry with CA bit for this slave disabled? Then also post a wireshark capture.

The proper way to handle this is to ask the vendor for a firmware update.

**Comment by pingplug** [comment]
I contacted to vendor, they said 1600 and 1a00 store values for their proprietary protocol, and told me just set the map size to 2I+2O.
Is there any functions to set this?

**Comment by ArthurKetels** [comment]
SDO 1600 and 1A00 are not proprietary, they are to be defined as in the official EtherCAT protocol. A slave conformance test to these standards is mandatory for each vendor that wants to sell slaves. A slave that does not pass this conformance test is not allowed to be sold or the vendor is in breach with the EtherCAT license he has signed with Beckhoff.

I would personally stop buying from those vendors. But it is your choice. 

You can remap a slave manually. Just set the correct SM and FMMU values. Have a look at the mapping functions in the source code. SOEM is very flexible, and can work around almost any issue, but is it worth it? The whole idea of EtherCAT is that we have a uniform way of discovering and configuring slaves. If you find this issue, have no vendor support, work around it yourself, how many times do you have to do this in the future? There is no end. If you try to build your house with mud...... Someday it will rain.
