### ISSUE TITLE
Sync Manager 7 does not get configurated 

### ISSUE THREAD

**Issue by lbckmnn** [OpenEtherCATsociety/SOEM#617]
Hello,
I tried to use a slave which uses Sync Manager 7 for inputs.
Unfortunately no FMMU seems to be assigned to this Sync Manager.

I tracked this down to the following lines in ecx_config_create_input_mappings:

```/* search for SM that contribute to the input mapping */
while ((SMc < (EC_MAXSM - 1)) && (FMMUdone < ((context->slavelist[slave].Ibits + 7) / 8)))
{
     ...
     /* do configuration */
     ...
}
 ```
What is the reasoning for the `(EC_MAXSM - 1)`?
When I change this to just `EC_MAXSM` a free FMMU is correctly assigned to the Sync Manger.

**Comment by nakarlsson** [comment]
@lbckmnn , please create a PR and we can fix it.

**Comment by lbckmnn** [comment]
@nakarlsson Yes but unfortunately I don't have access to the slave which needs sync manager 7 any more. 
Therefore I cannot be completely sure that the PR works.

**Comment by lbckmnn** [comment]
It worked as i just changed the first 
`while ((SMc < (EC_MAXSM - 1)) && (FMMUdone < ((context->slavelist[slave].Ibits + 7) / 8)))` 
to
`while ((SMc < EC_MAXSM ) && (FMMUdone < ((context->slavelist[slave].Ibits + 7) / 8)))` 
but there are some other places where `(EC_MAXSM - 1)` is used as condition which i don't quite fully understand yet.
Should i change these too?

**Comment by nakarlsson** [comment]
Hi,
No, only those ones, one for inputs and one for outputs.
Please acivate "EC_PRINT" and run slaveinfo and post the console, it will help to verify the result of the change.

while ((SMc < EC_MAXSM) && (FMMUdone < ((context->slavelist[slave].Ibits + 7) / 8)))

while ((SMc < EC_MAXSM)) && (FMMUdone < ((context->slavelist[slave].Obits + 7) / 8)))

Thanks
