### ISSUE TITLE
possible bug in ec_readstate and ec_statecheck

### ISSUE THREAD

**Issue by lbckmnn** [OpenEtherCATsociety/SOEM#626]
I was curios how SOEM determines the states of the slaves and read the implementation of ec_readstate and ec_statecheck.
I might have found a possible bug there.
When either of these function is used with slavenumber 0 (= whole network) the AL Status code (and therefore, the ethercat state) is read with an BRD frame. 

The BRD frame seems to apply a bitwise OR.
So if slaves have different states their state is basically ORed. 
The ethercat States are mostly collision free in this regard, but apparently not entirely:

| State   | hex/dec | bin  |
|---------|---------|------|
| INIT    | 1       | 0001 |
| PRE_OP  | 2       | 0010 |
| BOOT    | 3       | 0011 |
| SAFE_OP | 4       | 0100  |
| OP      | 8       | 1000 |

As far as i can tell, if one slave is in INIT and another in PRE_OP, reading the AL Status code with a BRD would result in 0x3 which is also the State for BOOT. Is this correct?

Code from  ecx_readstate
```C

//read state of all slaves with BRD and put this in variable "bitwisestate"
...
switch (bitwisestate)
   {
      case EC_STATE_INIT:
      case EC_STATE_PRE_OP:
      case EC_STATE_BOOT:
      case EC_STATE_SAFE_OP:
      case EC_STATE_OPERATIONAL:
         allslavessamestate = TRUE;
         context->slavelist[0].state = bitwisestate;
         break;
      default:
         allslavessamestate = FALSE;
         break;
   }
    
   if (noerrorflag && allslavessamestate && allslavespresent)
   {
      /* No slave has toggled the error flag so the alstatuscode
       * (even if different from 0) should be ignored and
       * the slaves have reached the same state so the internal state
       * can be updated without sending any datagram. */
      for (slave = 1; slave <= *(context->slavecount); slave++)
      {
         context->slavelist[slave].ALstatuscode = 0x0000;
         context->slavelist[slave].state = bitwisestate;
      }
      lowest = bitwisestate;
   }

```
Wouldn't this code set the state of all slaves to BOOT if one slave is in Init and one in PRE_OP?
A similiar problem exists in ec_statecheck.

**Comment by nakarlsson** [comment]
You’re right. BOOT should be removed from the case in ecx_readstate(ecx_contextt *context) for slave == 0.


And statecheck för BOOT does not, as you mention , guarantee all slaves in BOOT. That would need to be re-worked to handle BOOT for slave == 0.

**Comment by ArthurKetels** [comment]
I think it is more of a documentation issue. I have always intended to have slavelist[0].state to be the bitwise or of all slaves combined. Boot state is special and only used for firmware updates. And they are per definition per slave so, a statecheck for all slaves makes no sense there. So the proper thing to do is to remove EC_STATE_BOOT from the switch.

**Comment by lbckmnn** [comment]
Isn't it a use case to update the firmware of all slaves? In this case, I would expect that the user writes all slaves to BOOT first and than uploads the firmware. 

Another thing that might need documentation/handling is the return value of readstate:

The return value is the "lowest state found". 
Intuitively, I would rank BOOT lower than INIT or PRE_OP but BOOT is actually higher.

**Comment by nakarlsson** [comment]
I’d say BOOT state is per slave, ex https://github.com/OpenEtherCATsociety/SOEM/blob/master/test/linux/firm_update/firm_update.c

- BOOT MBX handling is per slave, must be setup before going to BOOT
- Firmware file is per slave
- FoE transfer is per file and slave

So, fixing the case BOOT is a fix needed.

Second, lowest state found is what it is. I’d say it is more nice to have info. To me BOOT is a special state outside the regulare state machine. It is optional.

**Comment by lbckmnn** [comment]
Yes this sounds reasonable. 
It might still be a good idea to mention the boot state in the documentation.
