### ISSUE TITLE
When Master  is will  Check State's Slaves?

### ISSUE THREAD

**Issue by tuhai711** [OpenEtherCATsociety/SOEM#640]
Hello,
I have problem when make Master to control Salves.
I see in simple_test had function ecatcheck, master allaway check status state's slave.
I have a question, when master need check state's slave?

**Comment by nakarlsson** [comment]
For that particular case it will "check" if the expected working counter differ from the actual working counter.

https://github.com/OpenEtherCATsociety/SOEM/blob/42ec9bf238ae617068a3adafd4c659573bdf29ec/test/linux/simple_test/simple_test.c#L153

**Comment by tuhai711** [comment]
Hello.
Does the master need to constantly check Salve status?

**Comment by nakarlsson** [comment]
Yes that is best practice if you implement your own master. But how you implement it can be done differently.

**Comment by tuhai711** [comment]
Yes, thank you.

**Comment by tuhai711** [comment]
Hello again,
How to send  output ec_send_processdata only one slave?

**Comment by tuhai711** [comment]
Yes, Thank you

**Comment by tuhai711** [comment]
Hello again.
If i want only received ec_receive_processdata from slave, How to implement? Because i see need use both  ec_send_processdata then ec_receive_processdata, we will receive data from slave.

**Comment by nakarlsson** [comment]
As I answered in https://github.com/OpenEtherCATsociety/SOES/issues/132#issuecomment-1247656800.
All traffic is driven by the master-

**Comment by tuhai711** [comment]
Yes. Thank you.
