### ISSUE TITLE
Is EOE not implemented yet or am i initializing the device incorrectly 

### ISSUE THREAD

**Issue by rohithsantosh13** [OpenEtherCATsociety/SOEM#641]
Hi i am using Twin CAT to configure the EtherCAT master to use EOE , but when in run the Pysoem script to read  the data the EOE-configurations made from TWINCAT are being removed can anyone suggest a solution or workaround for this issue

**Comment by GARBAGE-WALL-E** [comment]
@rohithsantosh13 

Hi, Rohit
Can you please help me out with this [PYSOEM issue](https://github.com/bnjmnp/pysoem/issues/83). 

You are the only Indian I could find in here. 
That would  be really helpful if you can provide me your contact details, and get actively involved, I can compensate you for your efforts.

(if you don't want to share your contact details here I can create temporary email Id and we will go from there)
