### ISSUE TITLE
how to clear the slave error?

### ISSUE THREAD

**Issue by yanzhang920817** [OpenEtherCATsociety/SOEM#648]
hello,
for example，in the follow code，the result of rval & 0x000f is the slave status, the result of  **rval  & 0x00f0**  is the slave error code，how to clear the error?

```
`     slstat.alstatus = 0;
      slstat.alstatuscode = 0;
      ecx_FPRD(context->port, configadr, ECT_REG_ALSTAT, sizeof(slstat), &slstat, EC_TIMEOUTRET);
      rval = etohs(slstat.alstatus);
      context->slavelist[slave].ALstatuscode = etohs(slstat.alstatuscode);
      state = rval & 0x000f; /* read slave status */
```
`

**Comment by nakarlsson** [comment]
The master acknowledges the Error Indication flag of the slave by setting the Error Ind Ack flag (0x0120.4).

**Comment by nakarlsson** [comment]
@yanzhang920817 , can this issue be closed?
