### ISSUE TITLE
finding out the problem using wireshark

### ISSUE THREAD

**Issue by parinaz6** [OpenEtherCATsociety/SOEM#659]
[en90.zip](https://github.com/OpenEtherCATsociety/SOEM/files/9924841/en90.zip)
Hi guys,
this is my wireshark file when I run the motor. The motor reaches the OP state but it does not move. Can someone please help me figure the problem?

**Comment by ArthurKetels** [comment]
see post #657

**Comment by nakarlsson** [comment]
@parinaz6 , can we close this issue?

**Comment by nakarlsson** [comment]
close due to inactivity
