### ISSUE TITLE
Optimizing controlling drive DS402 by velocity(position)

### ISSUE THREAD

**Issue by nkt17** [OpenEtherCATsociety/SOEM#673]
Hello everyone, i'm not expert with EtherCAT.

I've managed to launch drive by executing Elmo legacy commands JV(PA) and BG (e. g. JV=111111: ec_SDOwrite(slave, 0x30ff, 0x01, FALSE, 4, 111111, TIMEOUTSAFE), BG: ec_SDOwrite(slave, 0x3020, 0x01, FALSE, 2, 0x0000, TIMEOUTSAFE). This 2 commands spend approximately 20ms. Then i can't set velocity more than 50 times per second, but i want set velocity(position) around 500 times per second for more precise motor controlling by velocity(position). Can I execute velocity setting command (like JV) and launching motor (like BG) faster (around 1-2 ms for these 2 commands)? 
I've heard that PDO is mush more faster than SDO. I've found function (int ecx_RxPDO(ecx_contextt *context, uint16 Slave, uint16 RxPDOnumber , int psize, const void *p);) but i don't understand what is RxPDOnumber. My drive is DC402.

I will be grateful for your help.

**Comment by nkt17** [comment]
Also i've tried to connect to drives via TwinCAT. I've pushed to scan button but there is no devices were found.

**Comment by ArthurKetels** [comment]
Perhaps a read of tutorial.txt is in order. Then have a look how simple_slave (from the test programs) works then have a look here on dozens of post that show how to do that. Also the ETG is you friend when you want to gather more knowledge about how EtherCAT actually works. SOEM is a library that assumes the user knows about basic EtherCAT things.

**Comment by nkt17** [comment]
Hello again.

I've made custom mapping PDO and tried to send pdo commands to slave. I notices that target velocity (0x60ff) value changed but motor didn't start moving, although doing the same sequence of commands via SDO made motor moving. I guess that happens because the motor for some reasons falls in SAFE_OP mode while sending process_data. Here is my modified simple_test code:

/** \file
 * \brief Example code for Simple Open EtherCAT master
 *
 * Usage : simple_test [ifname1]
 * ifname is NIC interface, f.e. eth0
 *
 * This is a minimal test.
 *
 * (c)Arthur Ketels 2010 - 2011
 */

#include <stdio.h>
#include <string.h>
#include <inttypes.h>

#include "ethercat.h"

#define EC_TIMEOUTMON 500

#define pe printError()

PACKED_BEGIN
typedef struct PACKED
{
    int32 tg_vel; // Target velocity (60ff)
    uint16 ctrl_w; // Control word (6040)
    int8 op; // modes of operation (6060)
} out_motor_t;
PACKED_END

char IOmap[4096];
OSAL_THREAD_HANDLE thread1;
int expectedWKC;
boolean needlf;
volatile int wkc;
boolean inOP;
uint8 currentgroup = 0;

void printError()
{
    ec_errort err;
    while (ec_poperror(&err))
    {
        printf("Slave %d error!!! AbortCode is %8.8X\n", 1, err.AbortCode);
        printf("\t%s", ecx_err2string(err));
        int32_t p;
        int psize = sizeof(p);
        ec_SDOread(1, 0x306a, 0x01, FALSE, &psize, &p, EC_TIMEOUTSAFE); //EC
        printf("\t\tError code: %d\n", p);
    }
}

void SDOchDebug8u(uint16 slave, uint16 index, uint8 subindex, uint8 value)
{
    printf("_______________________________________________________________________________________________\n");

    uint8 p = 0x88;
    int psize = sizeof(p);
    ec_SDOread(slave, index, subindex, FALSE, &psize, &p, EC_TIMEOUTSAFE);
    printf("0x%4.4X before setting: 0x%2.2X\n", index, p);

    printf("setting 0x%4.4X: %d\n", index, value);
    uint8 u8val = value;
    ec_SDOwrite(slave, index, subindex, FALSE, sizeof(u8val), &u8val, EC_TIMEOUTSAFE);

    p = 0x88;
    ec_SDOread(slave, index, subindex, FALSE, &psize, &p, EC_TIMEOUTSAFE);
    printf("0x%4.4X after setting: 0x%2.2X\n", index, p);

    printf("_______________________________________________________________________________________________\n\n");
}

void SDOchDebug8(uint16 slave, uint16 index, uint8 subindex, int8 value)
{
    printf("_______________________________________________________________________________________________\n");

    int8 p = 0x88;
    int psize = sizeof(p);
    ec_SDOread(slave, index, subindex, FALSE, &psize, &p, EC_TIMEOUTSAFE);
    printf("0x%4.4X before setting: 0x%2.2X\n", index, p);

    printf("setting 0x%4.4X: %d\n", index, value);
    int8 u8val = value;
    ec_SDOwrite(slave, index, subindex, FALSE, sizeof(u8val), &u8val, EC_TIMEOUTSAFE);

    p = 0x88;
    ec_SDOread(slave, index, subindex, FALSE, &psize, &p, EC_TIMEOUTSAFE);
    printf("0x%4.4X after setting: 0x%2.2X\n", index, p);

    printf("_______________________________________________________________________________________________\n\n");
}

void SDOchDebug16u(uint16 slave, uint16 index, uint8 subindex, uint16 value)
{
    printf("_______________________________________________________________________________________________\n");

    uint16 p = 0x0088;
    int psize = sizeof(p);
    ec_SDOread(slave, index, subindex, FALSE, &psize, &p, EC_TIMEOUTSAFE);
    printf("0x%4.4X before setting: 0x%4.4X\n", index, p);

    printf("setting 0x%4.4X: %d\n", index, value);
    uint16 u16val = value;
    ec_SDOwrite(slave, index, subindex, FALSE, sizeof(u16val), &u16val, EC_TIMEOUTSAFE);

    p = 0x0088;
    ec_SDOread(slave, index, subindex, FALSE, &psize, &p, EC_TIMEOUTSAFE);
    printf("0x%4.4X after setting: 0x%4.4X\n", index, p);

    printf("_______________________________________________________________________________________________\n\n");
}

void SDOchDebug16(uint16 slave, uint16 index, uint8 subindex, int16 value)
{
    printf("_______________________________________________________________________________________________\n");

    int16 p = 0x0088;
    int psize = sizeof(p);
    ec_SDOread(slave, index, subindex, FALSE, &psize, &p, EC_TIMEOUTSAFE);
    printf("0x%4.4X before setting: 0x%4.4X\n", index, p);

    printf("setting 0x%4.4X: %d\n", index, value);
    int16 u16val = value;
    ec_SDOwrite(slave, index, subindex, FALSE, sizeof(u16val), &u16val, EC_TIMEOUTSAFE);

    p = 0x0088;
    ec_SDOread(slave, index, subindex, FALSE, &psize, &p, EC_TIMEOUTSAFE);
    printf("0x%4.4X after setting: 0x%4.4X\n", index, p);

    printf("_______________________________________________________________________________________________\n\n");
}

void SDOchDebug32u(uint16 slave, uint16 index, uint8 subindex, uint32 value)
{
    printf("_______________________________________________________________________________________________\n");

    uint32 p = 0x00000088;
    int psize = sizeof(p);
    ec_SDOread(slave, index, subindex, FALSE, &psize, &p, EC_TIMEOUTSAFE);
    printf("0x%4.4X before setting: %d\n", index, p);

    printf("setting 0x%4.4X: %d\n", index, value);
    uint32 u32val = value;
    ec_SDOwrite(slave, index, subindex, FALSE, sizeof(u32val), &u32val, EC_TIMEOUTSAFE);

    p = 0x00000088;
    ec_SDOread(slave, index, subindex, FALSE, &psize, &p, EC_TIMEOUTSAFE);
    printf("0x%4.4X after setting: %d\n", index, p);

    printf("_______________________________________________________________________________________________\n\n");
}

void SDOchDebug32(uint16 slave, uint16 index, uint8 subindex, int32 value)
{
    printf("_______________________________________________________________________________________________\n");

    int32 p = 0x00000088;
    int psize = sizeof(p);
    ec_SDOread(slave, index, subindex, FALSE, &psize, &p, EC_TIMEOUTSAFE);
    printf("0x%4.4X before setting: %d\n", index, p);

    printf("setting 0x%4.4X: %d\n", index, value);
    int32 u32val = value;
    ec_SDOwrite(slave, index, subindex, FALSE, sizeof(u32val), &u32val, EC_TIMEOUTSAFE);

    p = 0x00000088;
    ec_SDOread(slave, index, subindex, FALSE, &psize, &p, EC_TIMEOUTSAFE);
    printf("0x%4.4X after setting: %d\n", index, p);

    printf("_______________________________________________________________________________________________\n\n");
}

void SDOstatusDebug(uint16 slave, uint16 index, uint8 subindex, uint8 hex)
{
    
    int32 p = 0;
    int psize = sizeof(p);
    ec_SDOread(slave, index, subindex, FALSE, &psize, &p, EC_TIMEOUTSAFE);

    if (hex == 0x00)
        printf("0x%4.4X: %d\n", index, p);
    else if (hex == 0x01)
        printf("0x%4.4X: 0x%2.2X\n", index, (uint8)p);
    else if (hex == 0x02)
        printf("0x%4.4X: 0x%4.4X\n", index, (uint16)p);
    else
        printf("0x%4.4X: 0x%8.8X\n", index, (uint32)p);


}

void status(uint16 slave)
{
    printf("#################################################################################################\n");

    printf("control word:\t"); SDOstatusDebug(slave, 0x6040, 0x00, 0x02);
    printf("status word:\t"); SDOstatusDebug(slave, 0x6041, 0x00, 0x02);
    printf("modes of operation:\t"); SDOstatusDebug(slave, 0x6060, 0x00, 0x01);
    printf("profile acceleration:\t"); SDOstatusDebug(slave, 0x6083, 0x00, 0x00);
    printf("profile deceleration:\t"); SDOstatusDebug(slave, 0x6084, 0x00, 0x00);
    printf("profile velocity:\t"); SDOstatusDebug(slave, 0x6081, 0x00, 0x00);
    printf("target position:\t"); SDOstatusDebug(slave, 0x607a, 0x00, 0x00);
    printf("target velocity:\t"); SDOstatusDebug(slave, 0x60ff, 0x00, 0x00);

    printf("#################################################################################################\n\n");
}

void resetFault(uint16 slave)
{
    //reading status
    uint16 p = 0;
    int psize = sizeof(p);
    ec_SDOread(slave, 0x6041, 0x00, FALSE, &psize, &p, EC_TIMEOUTSAFE);

    while ((p & 0x0f) == 0x0f)
    {
        printf("fault reaction is executing now!!!\n");
    }
    
    if ((p & 0x08) == 0x08)
    {
        printf("fault occured. Transition to switch on disabled state!\n\n");
        SDOchDebug16u(1, 0x6040, 0x00, 0x0080);
    }
}

//for sending target velocity via PDO
void PDOtgVel(uint16 slave, int32 val)
{
    out_motor_t* out_motor = (out_motor_t*)ec_slave[slave].outputs;
    out_motor->tg_vel = val;
    ec_send_processdata();
    osal_usleep(10000);
}

//for sending control word via PDO
void PDOctrlW(uint16 slave, uint16 val)
{
    out_motor_t* out_motor = (out_motor_t*)ec_slave[slave].outputs;
    out_motor->ctrl_w = val;
    ec_send_processdata();
    osal_usleep(10000);
}

//for sending operational modes via PDO
void PDOop(uint16 slave, int8 val)
{
    out_motor_t* out_motor = (out_motor_t*)ec_slave[slave].outputs;
    out_motor->op = val;
    ec_send_processdata();
    osal_usleep(10000);
}

//custom mapping
int PDOmapping(uint16 slave)
{
    uint16 map_1c12[2] = { 0x0001, 0x1607 };
    uint16 map_1607[7] = { 0x0003, 0x0020, 0x60ff, 0x0010, 0x6040, 0x0008, 0x6060 };
    ec_SDOwrite(slave, 0x1c12, 0x00, TRUE, sizeof(map_1c12), &map_1c12, EC_TIMEOUTSAFE);
    ec_SDOwrite(slave, 0x1607, 0x00, TRUE, sizeof(map_1607), &map_1607, EC_TIMEOUTSAFE);

    return 1;
}

void simpletest(char *ifname)
{
    int i, oloop, iloop, chk;
    needlf = FALSE;
    inOP = FALSE;
    int slc;

   printf("Starting simple test\n");

   /* initialise SOEM, bind socket to ifname */
   if (ec_init(ifname))
   {
      printf("ec_init on %s succeeded.\n",ifname);
      /* find and auto-config slaves */


      //if (ec_config_init(FALSE) > 0)
      if (ec_config_init(TRUE) > 0)
      {
          printf("%d slaves found and configured.\n", ec_slavecount);

          for (slc = 1; slc <= ec_slavecount; slc++)
          {
              ec_slave[slc].PO2SOconfig = &PDOmapping;
          }

          status(1);
          ec_config_map(&IOmap);

          ec_configdc();

          if (ec_slave[0].eep_man)

          printf("Slaves mapped, state to SAFE_OP.\n");
          /* wait for all slaves to reach SAFE_OP state */
          ec_statecheck(0, EC_STATE_SAFE_OP, EC_TIMEOUTSTATE * 4);

          oloop = ec_slave[0].Obytes;
          if ((oloop == 0) && (ec_slave[0].Obits > 0)) oloop = 1;
          if (oloop > 8) oloop = 8;
          iloop = ec_slave[0].Ibytes;
          if ((iloop == 0) && (ec_slave[0].Ibits > 0)) iloop = 1;
          if (iloop > 8) iloop = 8;

          printf("segments : %d : %d %d %d %d\n", ec_group[0].nsegments, ec_group[0].IOsegment[0], ec_group[0].IOsegment[1], ec_group[0].IOsegment[2], ec_group[0].IOsegment[3]);

          printf("Request operational state for all slaves\n");
          expectedWKC = (ec_group[0].outputsWKC * 2) + ec_group[0].inputsWKC;
          printf("Calculated workcounter %d\n", expectedWKC);
          ec_slave[0].state = EC_STATE_OPERATIONAL;
          /* send one valid process data to make outputs in slaves happy*/
          ec_send_processdata();
          ec_receive_processdata(EC_TIMEOUTRET);
          /* request OP state for all slaves */
          ec_writestate(0);
          chk = 200;
          /* wait for all slaves to reach OP state */
          do
          {
              ec_send_processdata();
              ec_receive_processdata(EC_TIMEOUTRET);
              ec_statecheck(0, EC_STATE_OPERATIONAL, 50000);
          } while (chk-- && (ec_slave[0].state != EC_STATE_OPERATIONAL));
          if (ec_slave[0].state == EC_STATE_OPERATIONAL)
          {
              printf("Operational state reached for all slaves.\n");
              inOP = TRUE;
              /* cyclic loop */

              status(1);

              SDOchDebug8(1, 0x6060, 0x00, 0x01);

              //status(1);

              SDOchDebug32u(1, 0x6083, 0x00, 10000000);
              SDOchDebug32u(1, 0x6084, 0x00, 10000000);
              resetFault(1);

              //status(1);


              SDOchDebug32(1, 0x607a, 0x00, 111111111);
              SDOchDebug32u(1, 0x6081, 0x00, 30000000);

              //SDOchDebug16u(1, 0x6040, 0x00, 0x0006);
              //SDOchDebug16u(1, 0x6040, 0x00, 0x0007);
              //SDOchDebug16u(1, 0x6040, 0x00, 0x000f);
              PDOtgVel(1, 12112211);
              PDOctrlW(1, 0x0006);
              PDOctrlW(1, 0x0007);
              PDOctrlW(1, 0x000f);

              //status(1);

              PDOctrlW(1, 0x003f);
              PDOctrlW(1, 0x000f);

              status(1);

              //status(1);
              //
              //
              //SDOchDebug32(1, 0x607a, 0x00, 111111111);
              //SDOchDebug32u(1, 0x6081, 0x00, 30000000);
              //
              //status(1);
              //
              //SDOchDebug16u(1, 0x6040, 0x00, 0x003f);
              //SDOchDebug16u(1, 0x6040, 0x00, 0x000f);
              //SDOchDebug32(1, 0x607a, 0x00, 222222222);
              //SDOchDebug32u(1, 0x6081, 0x00, 10000000);
              //SDOchDebug16u(1, 0x6040, 0x00, 0x003f);
              //SDOchDebug16u(1, 0x6040, 0x00, 0x000f);
              //
              //
              //status(1);
              
              inOP = FALSE;
          }
          else
          {
              printf("Not all slaves reached operational state.\n");
              ec_readstate();
              for (i = 1; i <= ec_slavecount; i++)
              {

                  if (ec_slave[i].state != EC_STATE_OPERATIONAL)
                  {

                      printf("Slave %d State=0x%2.2x StatusCode=0x%4.4x : %s\n",
                          i, ec_slave[i].state, ec_slave[i].ALstatuscode, ec_ALstatuscode2string(ec_slave[i].ALstatuscode));
                  }
              }
          }
          printf("\nRequest init state for all slaves\n");
          ec_slave[0].state = EC_STATE_INIT;
          /* request INIT state for all slaves */
          ec_writestate(0);
      }
      else
      {
          printf("No slaves found!\n");
      }
      printf("End simple test, close socket\n");
      /* stop SOEM, close socket */
      ec_close();
    }
    else
    {
        printf("No socket connection on %s\nExecute as root\n", ifname);
    }
}

OSAL_THREAD_FUNC ecatcheck( void *ptr )
{
    int slave;
    (void)ptr;                  /* Not used */

    while(1)
    {
        if( inOP && ((wkc < expectedWKC) || ec_group[currentgroup].docheckstate))
        {
            if (needlf)
            {
               needlf = FALSE;
               printf("\n");
            }
            /* one ore more slaves are not responding */
            ec_group[currentgroup].docheckstate = FALSE;
            ec_readstate();
            for (slave = 1; slave <= ec_slavecount; slave++)
            {
               if ((ec_slave[slave].group == currentgroup) && (ec_slave[slave].state != EC_STATE_OPERATIONAL))
               {
                  ec_group[currentgroup].docheckstate = TRUE;
                  if (ec_slave[slave].state == (EC_STATE_SAFE_OP + EC_STATE_ERROR))
                  {
                     printf("ERROR : slave %d is in SAFE_OP + ERROR, attempting ack.\n", slave);
                     ec_slave[slave].state = (EC_STATE_SAFE_OP + EC_STATE_ACK);
                     ec_writestate(slave);
                  }
                  else if(ec_slave[slave].state == EC_STATE_SAFE_OP)
                  {
                     printf("WARNING : slave %d is in SAFE_OP, change to OPERATIONAL.\n", slave);
                     ec_slave[slave].state = EC_STATE_OPERATIONAL;
                     ec_writestate(slave);
                  }
                  else if(ec_slave[slave].state > EC_STATE_NONE)
                  {
                     if (ec_reconfig_slave(slave, EC_TIMEOUTMON))
                     {
                        ec_slave[slave].islost = FALSE;
                        printf("MESSAGE : slave %d reconfigured\n",slave);
                     }
                  }
                  else if(!ec_slave[slave].islost)
                  {
                     /* re-check state */
                     ec_statecheck(slave, EC_STATE_OPERATIONAL, EC_TIMEOUTRET);
                     if (ec_slave[slave].state == EC_STATE_NONE)
                     {
                        ec_slave[slave].islost = TRUE;
                        printf("ERROR : slave %d lost\n",slave);
                     }
                  }
               }
               if (ec_slave[slave].islost)
               {
                  if(ec_slave[slave].state == EC_STATE_NONE)
                  {
                     if (ec_recover_slave(slave, EC_TIMEOUTMON))
                     {
                        ec_slave[slave].islost = FALSE;
                        printf("MESSAGE : slave %d recovered\n",slave);
                     }
                  }
                  else
                  {
                     ec_slave[slave].islost = FALSE;
                     printf("MESSAGE : slave %d found\n",slave);
                  }
               }
            }
            if(!ec_group[currentgroup].docheckstate)
               printf("OK : all slaves resumed OPERATIONAL.\n");
        }
        osal_usleep(10000);
    }
}

int main(int argc, char *argv[])
{
   printf("SOEM (Simple Open EtherCAT Master)\nSimple test\n");

   printf("\n %s \n", argv[0]);
   if (argc > 1)
   {
      /* create thread to handle slave error handling in OP */
//      pthread_create( &thread1, NULL, (void *) &ecatcheck, (void*) &ctime);
      osal_thread_create(&thread1, 128000, &ecatcheck, (void*) &ctime);
      /* start cyclic part */
      simpletest(argv[1]);
   }
   else
   {
      ec_adaptert * adapter = NULL;
      printf("Usage: simple_test ifname1\nifname = eth0 for example\n");

      printf ("\nAvailable adapters:\n");
      adapter = ec_find_adapters ();
      while (adapter != NULL)
      {
         printf ("    - %s  (%s)\n", adapter->name, adapter->desc);
         adapter = adapter->next;
      }
      ec_free_adapters(adapter);
   }

   printf("End program\n");
   return (0);
}

**Comment by nkt17** [comment]
Here is how PDO mapping looks like in slave_info.c
![image](https://user-images.githubusercontent.com/26310928/207631307-40e11957-48c7-4a7d-8a24-f54e1032f4f0.png)

**Comment by nkt17** [comment]
there is how status params look like before and after PDO commands
![image](https://user-images.githubusercontent.com/26310928/207633752-66c3ad1f-ced9-40bc-bba5-91755db4061d.png)
![image](https://user-images.githubusercontent.com/26310928/207633878-8de63573-4dd1-420c-b483-40cda5fbfd12.png)
