### ISSUE TITLE
netpacket/packet.h: no such file or directory

### ISSUE THREAD

**Issue by Mavnus04** [OpenEtherCATsociety/SOEM#68]
I am trying to make a library for QNX momentics IDE 5.0 and got the following:

Installing the build libraries
Scanning dependencies of target soem
[  4%] Building C object CMakeFiles/soem.dir/C_/SOEM-master/oshw/linux/nicdrv.c.o
**C:/SOEM-master/oshw/linux/nicdrv.c:80:30: fatal error: netpacket/packet.h: No such file or directory**
compilation terminated.
cc: C:/qnx660/host/win32/x86//usr/lib/gcc/i486-pc-nto-qnx6.6.0/4.7.3/cc1 caught signal 1
make[2]: *** [CMakeFiles/soem.dir/C_/SOEM-master/oshw/linux/nicdrv.c.o] Error 1
make[1]: *** [CMakeFiles/soem.dir/all] Error 2
make: *** [all] Error 2
sh-3.1$

**Comment by nakarlsson** [comment]
You're facing a plattform/porting issue. Create a qnx folder and remove and replace non existing items and objects from the Linux port.

**Comment by Mavnus04** [comment]
I cannot seem to find this missing file "packet.h" for QNX.  I have found other packet.h files, but they do not contain all/correct definitions and functions required.

**Comment by nakarlsson** [comment]
no, you have to look within your Qnx plattform for the support you need.

Since you use the Linux port you'll find the originals there.

**Comment by nakarlsson** [comment]
Any update?

**Comment by Mavnus04** [comment]
Yes, I was able to find a build for QNX.  There was a lot more than just 1 missing file.  Can I upload/send the changes somewhere?

**Comment by nakarlsson** [comment]
Not sure, will you provide a QNX port?

**Comment by mheden** [comment]
If you have written an QNX port and want to contribute it, you'll have to submit a CLA as well: https://openethercatsociety.github.io/cla/cla_soem_soes.pdf

**Comment by nakarlsson** [comment]
Create a PR when the QNX port is ready

**Comment by briansoe66** [comment]
@Mavnus04 -  Could you share the QNX port in a public SOEM fork? I'd love to try it.
