### ISSUE TITLE
The slave is lost with SOEM, but found with Twincat

### ISSUE THREAD

**Issue by SKTTelephoneFaker** [OpenEtherCATsociety/SOEM#687]
I have the same phenomenon as original
```
int ecx_recover_slave(ecx_contextt *context, uint16 slave, int timeout)
{
   int rval;
   int wkc;
   uint16 ADPh, configadr, readadr;

   rval = 0;
   configadr = context->slavelist[slave].configadr;
   ADPh = (uint16)(1 - slave);
   /* check if we found another slave than the requested */
   readadr = 0xfffe;
   wkc = ecx_APRD(context->port, ADPh, ECT_REG_STADR, sizeof(readadr), &readadr, timeout);
   if (wkc < 0) {
       printf("wkc < 0 in recover");
   }
```

- It happened when I unplugged the Internet cable
- wkc will always <0
- But when I used twincat, everything worked fine

// windows : Using WIndows11 (64Bit)
// WinPCap :  4.1.3
// Slave       :  Ax58100
// SOEM     :  master
// Twincat   : 3.15
//soem wireshark caps:    I started soem and then hot plug the network cable
[save.zip](https://github.com/OpenEtherCATsociety/SOEM/files/11013146/save.zip)
//twincat wireshark caps:    I started twincat and then hot plug the network cable
[twincat_recover.zip](https://github.com/OpenEtherCATsociety/SOEM/files/11013162/twincat_recover.zip)

_Originally posted by @SKTTelephoneFaker in https://github.com/OpenEtherCATsociety/SOEM/issues/99#issuecomment-1475508215_

**Comment by ArthurKetels** [comment]
This is not a SOEM issue but something lower in the network stack. Either WinPCap or the windows network stack. As seen in the wireshark trace there is not a single return packet from the slave. If you can verify that the ACT led on your PC or the slave is blinking then you know there is a physical link. One thing that you might try is to use Npcap instead of WinPcap.

**Comment by SKTTelephoneFaker** [comment]
Thanks for the quick response, I'll try

**Comment by SKTTelephoneFaker** [comment]
![image](https://user-images.githubusercontent.com/38111228/226859415-74c8c93a-00c9-40d9-b1e0-d77833d1c433.png)
i changed this line and problem seems solved!
@ArthurKetels
