### ISSUE TITLE
General question about ports

### ISSUE THREAD

**Issue by bhargavah** [OpenEtherCATsociety/SOEM#688]
Can an external adaptor be used to convert the USB port into an Ethernet port and do EtherCat protocol programming? Since Ethercat protocol works only with the Ethernet port and mac air does not have an Ethernet port, how is it possible to do EtherCat programming on mac air otherwise?

**Comment by ArthurKetels** [comment]
Modern USB to Ethernet adapters work fine with SOEM. Just do not expect the same real-time performance as native network cards. The USB part adds quite a bit of timing jitter and latency.

**Comment by bhargavah** [comment]
Thanks, Arthur. This answer would help many fellow developers who believe that an Ethernet port is a must which is not the case.
