### ISSUE TITLE
sample for data_transfer

### ISSUE THREAD

**Issue by Edphoenixmax** [OpenEtherCATsociety/SOEM#690]
Is there anyone knows how to use the ec_SDOread and ec_SDOwrite funtions ?
Do u guys have the example for transfering data with slaves under linux ?
thanks a lot for your help

**Comment by ArthurKetels** [comment]
Did you read doc/tutorial.txt? Also have a look in the test programs. And of course the SOEM code itself.

**Comment by Edphoenixmax** [comment]
yes ,I have read these ,and I try to use ec_SDOwrite to write data in frame, but when I try to check my woreshark trace,there is no data in the frame. I cannot figure it out
