### ISSUE TITLE
Release version bump

### ISSUE THREAD

**Issue by omarhogni** [OpenEtherCATsociety/SOEM#707]
Hi,

are there any plans to release a new version of this library?

**Comment by ArthurKetels** [comment]
At the moment versions are just tags along a continuous update path. Just pull the latest from the main branch and you are set. Any specific patches that you need to be stable?

**Comment by omarhogni** [comment]
Not looking for feature stability currently. 
I am consuming soem through vcpkg https://github.com/microsoft/vcpkg/tree/master/ports/soem 

Personally i would like to update the port to include the cmake rewrite.
