### ISSUE TITLE
tutorial_8txt file  ，where is  offline.h？

### ISSUE THREAD

**Issue by zouzhe1** [OpenEtherCATsociety/SOEM#709]
SOEM has now discovered and configured the network it is connected to. Now we can verify that all slaves are present as expected. These definitions could be generated by an external tool in an **offline .h** file. The definitions could be replaced by a struct keeping slave number.

**Comment by nakarlsson** [comment]
It is an example, not to be taken literally.

offline means it is generated/crafted offline by some tool or the user
