### ISSUE TITLE
The writing of the XML was successful, and the reading was also successful, but the comparison is different

### ISSUE THREAD

**Issue by yanzhang920817** [OpenEtherCATsociety/SOEM#714]
Writing XML from eeprom was successful, and then reading it was also successful. However, the comparison between the written file axml.bin and the read file bxml.bin is different, and it occasionally appears. May I ask what may be the reason? If there is a problem with axml.bin, will it cause this problem to occasionally occur?

**Comment by ArthurKetels** [comment]
There is very little information about what exactly you have done, and what exactly is the reference and read_back file. So it is hard to be specific in my answer.

As a rule you may assume that if the eeprom read and write functions do not return an error the operation has succeeded. So from a SOEM point of view there is no bug or error. 

A slave has the freedom to filter or modify the eeprom content by itself. This to protect from erroneous data. Also some slaves have only eeprom emulation, and trying to overwrite those fields will fail even when the transmission protocol reports no errors. An other possible cause can be hardware issues in the slave (f.e. malfunctioning eeprom).
