### ISSUE TITLE
Interface eth0 couldn't open with pcap

### ISSUE THREAD

**Issue by bereketeshete** [OpenEtherCATsociety/SOEM#717]
I am trying to get slaveinfo on my "TwinCAT-Intel PCI Ethernet Adapter (Gigabit)". I don't how to retrieve this adapter's ifname, so I used the tutorial default `> ./slaveinfo eth0` and SOEM returns with `Interface eth0 couldn't open with pcap` and `No socket connection on eth0`. How can I get slaveinfo on my TwinCAT ethernet adapter?

![issue_1](https://github.com/OpenEtherCATsociety/SOEM/assets/40177156/43d4baa0-7f6f-4adb-afc3-09cdc96e60bd)
![issue_2](https://github.com/OpenEtherCATsociety/SOEM/assets/40177156/a070a89d-0bdb-473d-9388-f8b0d54c567c)

**Comment by nakarlsson** [comment]
on windows use the \DEVICE sting instead
Try ./slaveinfo \DEVICE\NPF_{the GUID
}

**Comment by bereketeshete** [comment]
Seems like that doesn't solve the issue, SOEM still returns `interface \Device\NPF_ could not open with pcap`

![issue of SOEM on windows](https://github.com/OpenEtherCATsociety/SOEM/assets/40177156/eb25892d-f246-4a88-9898-167a79b856ab)

**Comment by ArthurKetels** [comment]
Can you actually get WireShark running on that interface? If not then there is something wrong on the windows driver side.

You could also try the wireless interface. Of course it would not detect any slaves, But it would open the socket, and give you other text output on screen,

**Comment by mheden** [comment]
I'll think you need to quote your argument when running from power shell.

Den tors 22 juni 2023 18:00Bereket Eshete ***@***.***> skrev:

**Comment by bereketeshete** [comment]
> Can you actually get WireShark running on that interface? If not then there is something wrong on the windows driver side.
> 
> You could also try the wireless interface. Of course it would not detect any slaves, But it would open the socket, and give you other text output on screen,

Thank you, I have currently paused this project. I will try your suggestion when I get back to it.

**Comment by nakarlsson** [comment]
question completed
