### ISSUE TITLE
how to change weidemuller slave's output range

### ISSUE THREAD

**Issue by Edphoenixmax** [OpenEtherCATsociety/SOEM#724]
there are 3 parmeters we can configure before we start the slave. 
![image](https://github.com/OpenEtherCATsociety/SOEM/assets/103910444/4175945b-42ea-4276-8d01-82394b6e11a2)
Is there any way we can change the value of these parameters by SOEM ?
Thanks for your answer!

**Comment by ArthurKetels** [comment]
Perhaps, but how can I know without further information? If there is a CoE parameter, then you can access that via SOEM. But sometimes you need other methods. It should be in your manual.

**Comment by Edphoenixmax** [comment]
thanks for your reply! I have already figured it out! Thanks!
