### ISSUE TITLE
When upgrading firmware to a slave station, the slave station returns an error of 0x8003. What is the general reason?

### ISSUE THREAD

**Issue by yanzhang920817** [OpenEtherCATsociety/SOEM#729]
When upgrading firmware to a slave station, the slave station returns an error of 0x8003. What is the general reason?thanks.

**Comment by nakarlsson** [comment]
#define FOE_ERR_DISKFULL               0x8003

**Comment by yanzhang920817** [comment]
So we need to check what caused the disk to be full?

**Comment by yanzhang920817** [comment]
I have another question to ask, which error indicates that the upgraded firmware name does not match between 0x8005 and 0x8009? I think the ST chip and Renesas chip are different.

**Comment by nakarlsson** [comment]
It is in software, from the standard I'd say non of the above.

0x8005 or 0x0005 Packet number wrong ETG.1000.6
0x8009 or 0x0009 Not Bootstrap ETG.1000.6

Check ETG 1020 for more info, 15.2 FoE error Codes
