### ISSUE TITLE
Porting SOEM Code on RTOS

### ISSUE THREAD

**Issue by brentonchris** [OpenEtherCATsociety/SOEM#732]
Has the SOEM code been ported on RTOS?

**Comment by nakarlsson** [comment]
All non *nix and Win32 targets in HW/AL layers are RTOSs

**Comment by brentonchris** [comment]
I want to port the SOEM code on the ThreadX RTOS.
Are there any successful cases of transplantation that can be referred to?

**Comment by nakarlsson** [comment]
I don't know any.

**Comment by awolf-illumina** [comment]
@brentonchris Any luck? I'm looking to do a port for ThreadX as well

**Comment by brentonchris** [comment]
> @brentonchris Any luck? I'm looking to do a port for ThreadX as well

We already run SOEM without an operating system, but now we want to port it to threadx. However, there is a large error between the time of sending data and the target time point, it is the ec_sync in the SOEM code.

**Comment by WillyTuring** [comment]
> 

Hi chris, "However, there is a large error between the time of sending data and the target time point" what is this problem exaclty? I am considering migrating from Linux OS to MCU or possibly combining with FPGA as well for my application here.

**Comment by nakarlsson** [comment]
@brentonchris , can we close this issue?

**Comment by brentonchris** [comment]
> Guess we can close it

OK,close it.
