### ISSUE TITLE
some conflicts between set physical address and sdowrite

### ISSUE THREAD

**Issue by Edphoenixmax** [OpenEtherCATsociety/SOEM#735]
Hello ,recently I met a difficult issue that I cannot figure it out, so I come here for help.
 I try to  study some knowledge about Ethercat, so I use codesys to know how the ENI works. I find a ENI information,
<InitCmd>
                    <Transition>IP</Transition>
                    <Transition>IB</Transition>
                    <Comment>set physical address</Comment>
                    <Requires>cycle</Requires>
                    <Cmd>2</Cmd>
                    <Adp>0</Adp>
                    <Ado>16</Ado>
                    <Data>E903</Data>
                    <Cnt>1</Cnt>
                    <Retries>3</Retries>
 </InitCmd>
When I try to follow this Initcmd and then I try to use SDOwrite to configure startupparameter ,but error occurres, I cannot get the right wkc value ,the value is 0, so I cannot configure these startup parameters
So I am little confused,is there some lock so that sync manager cannot work or some other reasons that cause this conflict
Thanks for your reply!

**Comment by ArthurKetels** [comment]
I can not parse you ENI example above. The ENI specification is a standard document of the ETG. Get it there and then ask the question again with an example that can be reproduced.
