### ISSUE TITLE
ADO 502

### ISSUE THREAD

**Issue by Edphoenixmax** [OpenEtherCATsociety/SOEM#737]
I have caught .pcap, they are always stuck in FPRD cmd for ADP 0x1001, ADO 0x502, it returns wkc 0,
Do u know what it that means?And how to solve this problem.
Thanks for your reply!

**Comment by Edphoenixmax** [comment]
I figured it out it was stuck in ecx_eeprom_waitnotbusyFP function in ethercatmain.c , and how to solve this problem?

**Comment by ArthurKetels** [comment]
I left a commend in your other thread. Please do not open new issues for the same question. It is hard to track.
