### ISSUE TITLE
How to use SOEM on stm32?

### ISSUE THREAD

**Issue by tom9672** [OpenEtherCATsociety/SOEM#746]
1. I'm new to SOEM, Is it possible to use SOEM on a stm32 with w5500 without any OS? 

2. If SOEM can be use on a stm32, I'm not sure whether my understand is right, using the code from soem folder, and modify osal and oshw for hardware stm32+w5500, it can be work after that?

**Comment by ArthurKetels** [comment]
1. Yes.
2. Yes.

**Comment by nakarlsson** [comment]
Question completed
