### ISSUE TITLE
Any suggestions for optimizing NIC drivers？

### ISSUE THREAD

**Issue by casinia** [OpenEtherCATsociety/SOEM#747]
We use the red_test.c from the SOEM test/linux directory with a cycle 1kHz and modified it to measure some timing behaviour.And i know we must optimize the NIC driver(Intel I210) for real-time latency, but we‘re at a loss. Can you give us some suggestions？

**Comment by nakarlsson** [comment]
Make sure "Interrupt throttling" is disabled.

**Comment by nakarlsson** [comment]
@casinia , can we close this issue?

**Comment by casinia** [comment]
yes，thanks------------------ Original ------------------From: nakarlsson  ***@***.***>Date: Wed,Oct 25,2023 6:26 PMTo: OpenEtherCATsociety/SOEM ***@***.***>Cc: casinia ***@***.***>, Mention ***@***.***>Subject: Re: [OpenEtherCATsociety/SOEM] Any suggestions for optimizing NIC drivers？ (Issue #747)
@casinia , can we close this issue?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/OpenEtherCATsociety/SOEM/issues/747#issuecomment-1778964139",
"url": "https://github.com/OpenEtherCATsociety/SOEM/issues/747#issuecomment-1778964139",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
