### ISSUE TITLE
What does ec_OElist.ObjAccess represent?

### ISSUE THREAD

**Issue by IDLEtranger** [OpenEtherCATsociety/SOEM#748]
I'm having some difficulty understanding the object access bits representation in slaveinfo.c. Specifically, the line that prints object access:
"Obj.access: %4.4x", OElist.ObjAccess[j];
This results in an output like Obj.access: 003f. However, when referring to the ESI file under /EtherCATInfo/Descriptions/Devices/Device/Profile/Dictionary/Objects/Object/Flags/Access, the values are expressed as ro, rw, or wo, not as a number.

Upon further investigation, I looked into the ecx_readOEsingle() function in ethercatcoe.c and found the following line:
pOElist->ObjAccess[SubI] = etohs(aSDOp->wdata[4]);
Can someone explain what OElist.ObjAccess precisely represents? Additionally, how does SOEM interpret and retrieve this value via CoE?

**Comment by nakarlsson** [comment]
According to ETG1000.6.

Object Access WORD Bit 0: read access in Pre-Operational state
Bit 1: read access in Safe-Operational state
Bit 2: read access in Operational state
Bit 3: write access in Pre-Operational state
Bit 4: write access in Safe-Operational state
Bit 5: write access in Operational state
Bit 6: object is mappable in a RxPDO
Bit 7: object is mappable in a TxPDO
Bit 8: object can be used for backup
Bit 9: object can be used for settings
Bit 10-15: reserved

**Comment by IDLEtranger** [comment]
> According to ETG1000.6.
> 
> Object Access WORD Bit 0: read access in Pre-Operational state Bit 1: read access in Safe-Operational state Bit 2: read access in Operational state Bit 3: write access in Pre-Operational state Bit 4: write access in Safe-Operational state Bit 5: write access in Operational state Bit 6: object is mappable in a RxPDO Bit 7: object is mappable in a TxPDO Bit 8: object can be used for backup Bit 9: object can be used for settings Bit 10-15: reserved

@nakarlsson Thank you so much！

**Comment by nakarlsson** [comment]
Why did you re-open?
