### ISSUE TITLE
Slave wont go to SAFE OP instead goes to PRE OP + ERROR

### ISSUE THREAD

**Issue by IceTea2** [OpenEtherCATsociety/SOEM#758]
Hey guys,

really hope you can help me.
My problem is, that the motor driver AZD KED wont go into SAFE OP state. Instead i get an error stating invalid output mapping.
I used slaveinfo from the SOEM Lib, using Windows 11 64 Bit and Visual Studio 2022.
The slave reaches pre op just fine, but as soon as the master sends the command to go into SAFE OP, its LEDs "run" and "err "just start blinking red and green. (0x001D)
I included the wireshark data. The problem starts at line 452. (or maybe sooner, as i dont know)
Could it possibly be a timing issue or a problem with the Syncmanager(s)?

I didnt change any code from slave info file...
Tried debugging and understanding every code line, but i couldnt really figure it out...

I also included the slaveinfo from terminal and the XML/ESI File provided from oriental motor.

Really just started out with ethercat and trying to get into this.

If you need any further info, i would be more than happy to provide.
Thanks in advance!

![slaveinfoterminal](https://github.com/OpenEtherCATsociety/SOEM/assets/149606544/054494a3-def5-4486-bd86-ad60cda545e3)
[info.zip](https://github.com/OpenEtherCATsociety/SOEM/files/13232365/info.zip)

**Comment by prasaanthLvk** [comment]
Hi.., @IceTea2 Can you please let me know how you solved this ?I am also getting the same error the Device is not going to Safe_op and is showing error.If you could help me out it would really be a great help to me.

**Comment by IceTea2** [comment]
> Hi.., @IceTea2 Can you please let me know how you solved this ?I am also getting the same error the Device is not going to Safe_op and is showing error.If you could help me out it would really be a great help to me.

Which device do you have exactly? in my case, i needed to assign the pdo mapping via sdo_write for both receiving and transmitting pdo.
And that right before going to safe op

**Comment by prasaanthLvk** [comment]
Device :: ClipX BM40IE from HBM 

Thank you so much,for your info

**Comment by prasaanthLvk** [comment]
Hi @IceTea2 is it possible for you to share your pdo mapping I have tried mapping my pdo but it is failing with both my and soem example code stating that it's a read only not   writable
