### ISSUE TITLE
Wrong IOmapSize reported in overlapped mapping mode?

### ISSUE THREAD

**Issue by pdematteis** [OpenEtherCATsociety/SOEM#761]
ecx_config_overlap_map_group() in ethercatconfig.c reports 
`IOmapSize = context->grouplist[group].Obytes + context->grouplist[group].Ibytes`

Shouldn't it be something like:
`IOmapSize = max(context->grouplist[group].Obytes, context->grouplist[group].Ibytes)`

With one slave, 32 inputs + 32 outputs, IOmapSize is 64 bytes, but in the transmitted frame they occupy only 32 bytes, that is correct.

What's wrong?

Thanks

**Comment by nakarlsson** [comment]
They are not overlapped in the IOmap only in the frame.

**Comment by pdematteis** [comment]
Understood, it makes sense.
Thanks.
