### ISSUE TITLE
Is there an API or any method that can erase the entire eeprom?

### ISSUE THREAD

**Issue by yanzhang920817** [OpenEtherCATsociety/SOEM#762]
I encountered a problem where I wrote a slave firmware (approximately 400k) as XML to eeprom and used the eepromtool to update the XML (approximately 2k). On the surface, it was successful, but the restart was still incorrect. I had to use a burning cable to burn, but this was too annoying. Is there any way to solve this problem? For example, is there an API that can erase the entire eeprom?

**Comment by ArthurKetels** [comment]
Just use a 2K binary file filled with 0xFF, and transfer that to the eeprom with the eepromtool.

**Comment by yanzhang920817** [comment]
> Just use a 2K binary file filled with 0xFF, and transfer that to the eeprom with the eepromtool.

thanks.
