### ISSUE TITLE
Sdo read and write mutual exclusion question

### ISSUE THREAD

**Issue by Lambo0604** [OpenEtherCATsociety/SOEM#767]
Hello, sir！
        Do we need to add lock operation for reading and writing different SDOs（ec_SDOwrite、ec_SDOread）by two threads ？
        Thanks~

**Comment by nakarlsson** [comment]
To same slave yes. 
To two different slaves no.

Slaves will not serve two SDO requests simultaniously.

**Comment by Lambo0604** [comment]
Ok， thanks~
