### ISSUE TITLE
I tried to port SOEM to STM32F407, but the RAM overflowed

### ISSUE THREAD

**Issue by fyyxxm** [OpenEtherCATsociety/SOEM#771]
STM32F407 only has 128K RAM, it seems that the RAM used by SOEM is much larger than 128K. How can I modify the configuration of SOEM to reduce RAM usage?

**Comment by nakarlsson** [comment]
Decrease number of frames, EC_MAXBUF.

We’ve run SOEM in 48k.

**Comment by fyyxxm** [comment]
> Decrease number of frames, EC_MAXBUF

Thank you for your reply. I will make the necessary modifications and try again

**Comment by nakarlsson** [comment]
You can also decrease the number of pre-allocated slaves,

/** max. number of slaves in array */
#define EC_MAXSLAVE       200

**Comment by fyyxxm** [comment]
> You can also decrease the number of pre-allocated slaves,
> 
> /** max. number of slaves in array */ #define EC_MAXSLAVE 200

Thanks, after trying both of these modifications, they are effective. Thank you for your help.
