### ISSUE TITLE
invalid requested state change

### ISSUE THREAD

**Issue by LiuyanHuang12** [OpenEtherCATsociety/SOEM#793]
Hi,
i am new using SOEM for my EtherCAT Master implementation. I hope i could get some help here.
I have added the PO2SO config for my Slave1 AKD and Slave2 BK1120. Howerver for Slave 2 BK1120 i got the error "Attempt to write to a read only object". 
And when i run the simple_test for 1st time, i get an error for Slave2 "Slave 2 State=0x11 StatusCode=0x0011 : Invalid requested state change".
But for 2nd time, all slaves can get to the OP state and i can also get the processdata cycle run.
For 3rd time, again "Slave 2 State=0x11 StatusCode=0x0011 : Invalid requested state change".
4th time,"Operational state reached for all slaves."
I have no clue how to debug this problem. Could someone please guide me to this theme?
I have also attached the wireshark file.

[Wireshark.zip](https://github.com/OpenEtherCATsociety/SOEM/files/14605659/Wireshark.zip)

~/SOEM-master/build/test/linux/simple_test$ sudo ./simple_test enp7s0
SOEM (Simple Open EtherCAT Master)
Simple test
Starting simple test
ec_init on enp7s0 succeeded.
3 slaves found and configured.
AKD Slave 1 set, retval = 40
BK1120 Slave 2 set, retval = 0
Slaves mapped, state to SAFE_OP.
segments : 1 : 217 0 0 0
Request operational state for all slaves
Calculated workcounter 6
Not all slaves reached operational state.
Slave 2 State=0x11 StatusCode=0x0011 : Invalid requested state change

Request init state for all slaves
End simple test, close socket
End program

~/SOEM-master/build/test/linux/simple_test$ sudo ./simple_test enp7s0
SOEM (Simple Open EtherCAT Master)
Simple test
Starting simple test
ec_init on enp7s0 succeeded.
3 slaves found and configured.
AKD Slave 1 set, retval = 40
Time:1710434469.516 SDO slave:2 index:1a05.03 error:06010002 Attempt to write to a read only object
Time:1710434469.517 SDO slave:2 index:1a05.04 error:06010002 Attempt to write to a read only object
Time:1710434469.518 SDO slave:2 index:1a05.05 error:06010002 Attempt to write to a read only object
Time:1710434469.520 SDO slave:2 index:1a05.06 error:06010002 Attempt to write to a read only object
Time:1710434469.521 SDO slave:2 index:1a05.00 error:06010002 Attempt to write to a read only object
Time:1710434469.522 SDO slave:2 index:1c13.01 error:06010002 Attempt to write to a read only object
Time:1710434469.523 SDO slave:2 index:1c13.02 error:06010002 Attempt to write to a read only object
Time:1710434469.525 SDO slave:2 index:1c13.03 error:06010002 Attempt to write to a read only object
Time:1710434469.526 SDO slave:2 index:1c13.04 error:06010002 Attempt to write to a read only object
Time:1710434469.527 SDO slave:2 index:1c13.05 error:06010002 Attempt to write to a read only object
Time:1710434469.529 SDO slave:2 index:1c13.00 error:06010002 Attempt to write to a read only object
Time:1710434469.530 SDO slave:2 index:1c12.00 error:06010002 Attempt to write to a read only object
Time:1710434469.531 SDO slave:2 index:1601.00 error:06010002 Attempt to write to a read only object
Time:1710434469.532 SDO slave:2 index:1602.00 error:06010002 Attempt to write to a read only object
Time:1710434469.534 SDO slave:2 index:1603.00 error:06010002 Attempt to write to a read only object
Time:1710434469.535 SDO slave:2 index:1604.00 error:06010002 Attempt to write to a read only object
Time:1710434469.536 SDO slave:2 index:1605.00 error:06010002 Attempt to write to a read only object
Time:1710434469.538 SDO slave:2 index:16ff.00 error:06010002 Attempt to write to a read only object
Time:1710434469.539 SDO slave:2 index:1701.00 error:06010002 Attempt to write to a read only object
Time:1710434469.540 SDO slave:2 index:1601.01 error:06010002 Attempt to write to a read only object
Time:1710434469.541 SDO slave:2 index:1601.02 error:06010002 Attempt to write to a read only object
Time:1710434469.543 SDO slave:2 index:1601.03 error:06010002 Attempt to write to a read only object
Time:1710434469.544 SDO slave:2 index:1601.04 error:06010002 Attempt to write to a read only object
Time:1710434469.545 SDO slave:2 index:1601.05 error:06010002 Attempt to write to a read only object
Time:1710434469.546 SDO slave:2 index:1601.06 error:06010002 Attempt to write to a read only object
Time:1710434469.548 SDO slave:2 index:1601.07 error:06010002 Attempt to write to a read only object
Time:1710434469.549 SDO slave:2 index:1601.08 error:06010002 Attempt to write to a read only object
Time:1710434469.550 SDO slave:2 index:1601.00 error:06010002 Attempt to write to a read only object
Time:1710434469.552 SDO slave:2 index:1602.01 error:06010002 Attempt to write to a read only object
Time:1710434469.553 SDO slave:2 index:1602.02 error:06010002 Attempt to write to a read only object
Time:1710434469.554 SDO slave:2 index:1602.00 error:06010002 Attempt to write to a read only object
Time:1710434469.555 SDO slave:2 index:1603.01 error:06010002 Attempt to write to a read only object
Time:1710434469.557 SDO slave:2 index:1603.02 error:06010002 Attempt to write to a read only object
Time:1710434469.558 SDO slave:2 index:1603.03 error:06010002 Attempt to write to a read only object
Time:1710434469.559 SDO slave:2 index:1603.04 error:06010002 Attempt to write to a read only object
Time:1710434469.561 SDO slave:2 index:1603.05 error:06010002 Attempt to write to a read only object
Time:1710434469.562 SDO slave:2 index:1603.06 error:06010002 Attempt to write to a read only object
Time:1710434469.563 SDO slave:2 index:1603.00 error:06010002 Attempt to write to a read only object
Time:1710434469.564 SDO slave:2 index:1604.01 error:06010002 Attempt to write to a read only object
Time:1710434469.566 SDO slave:2 index:1604.02 error:06010002 Attempt to write to a read only object
Time:1710434469.567 SDO slave:2 index:1604.03 error:06010002 Attempt to write to a read only object
Time:1710434469.569 SDO slave:2 index:1604.04 error:06010002 Attempt to write to a read only object
Time:1710434469.570 SDO slave:2 index:1604.05 error:06010002 Attempt to write to a read only object
Time:1710434469.571 SDO slave:2 index:1604.06 error:06010002 Attempt to write to a read only object
Time:1710434469.573 SDO slave:2 index:1604.00 error:06010002 Attempt to write to a read only object
Time:1710434469.574 SDO slave:2 index:1605.01 error:06010002 Attempt to write to a read only object
Time:1710434469.575 SDO slave:2 index:1605.02 error:06010002 Attempt to write to a read only object
Time:1710434469.576 SDO slave:2 index:1605.03 error:06010002 Attempt to write to a read only object
Time:1710434469.578 SDO slave:2 index:1605.04 error:06010002 Attempt to write to a read only object
Time:1710434469.579 SDO slave:2 index:1605.05 error:06010002 Attempt to write to a read only object
Time:1710434469.580 SDO slave:2 index:1605.06 error:06010002 Attempt to write to a read only object
Time:1710434469.582 SDO slave:2 index:1605.00 error:06010002 Attempt to write to a read only object
Time:1710434469.583 SDO slave:2 index:16ff.01 error:06010002 Attempt to write to a read only object
Time:1710434469.584 SDO slave:2 index:16ff.00 error:06010002 Attempt to write to a read only object
Time:1710434469.585 SDO slave:2 index:1701.01 error:06010002 Attempt to write to a read only object
Time:1710434469.587 SDO slave:2 index:1701.00 error:06010002 Attempt to write to a read only object
Time:1710434469.588 SDO slave:2 index:1c12.01 error:06010002 Attempt to write to a read only object
Time:1710434469.589 SDO slave:2 index:1c12.02 error:06010002 Attempt to write to a read only object
Time:1710434469.591 SDO slave:2 index:1c12.03 error:06010002 Attempt to write to a read only object
Time:1710434469.592 SDO slave:2 index:1c12.04 error:06010002 Attempt to write to a read only object
Time:1710434469.593 SDO slave:2 index:1c12.04 error:06010002 Attempt to write to a read only object
Time:1710434469.594 SDO slave:2 index:1c12.04 error:06010002 Attempt to write to a read only object
Time:1710434469.596 SDO slave:2 index:1c12.05 error:06010002 Attempt to write to a read only object
Time:1710434469.597 SDO slave:2 index:1c12.00 error:06010002 Attempt to write to a read only object
BK1120 Slave 2 set, retval = 0
Slaves mapped, state to SAFE_OP.
segments : 1 : 273 0 0 0
Request operational state for all slaves
Calculated workcounter 9
Operational state reached for all slaves.
Processdata cycle    1, WKC 9 , O: 00 00 00 00 00 00 00 00 I: 88 03 00 00 00 00

**Comment by LiuyanHuang12** [comment]
Hi, i have solved the problem.😀

**Comment by gzovermas** [comment]
can you tell me how to solve this problem? I had the same problem.thx a lot
