### ISSUE TITLE
PDO Adresse do not match between output of slaveinfo -map and in ethercat-sdk

### ISSUE THREAD

**Issue by LiuyanHuang12** [OpenEtherCATsociety/SOEM#796]
Hi,

i am wondering why my PDO Adresse of the 2nd Slave(BK1120) do not match between the output of slaveinfo -map and in the Software ethercat-sdk. 

Could anyone please tell me why or guide me how to debug it? 

wenn the end Position of Slave1 (AKD) 17 is, then plus 8 bit, we should get the beginning Position of Slave2 as 18, right? But why in Ethercat-sdk it is 20?

if anyother data is needed, please tell and i will post it.
many many thanks!
![PDO Adresse](https://github.com/OpenEtherCATsociety/SOEM/assets/147640457/33b3a1f5-fe73-46a4-b503-218a575774ee)

**Comment by ArthurKetels** [comment]
I am not sure what your question is? SOEM seems to generate a reasonable mapping. Does it work?
What is the software ethercat-sdk? If that piece of software gives the wrong answer ask them for a solution.

You have to remember there are many ways of mapping the slave FMMU's to the logical address space. And one is not better or worse than the other. It also depends on your optimization goal. If you look in the source code of SOEM you will find the algorithm is very simple. It is also not mandatory to use the slave mapping functions of SOEM, you can use your own. As long as you fill in the the result in the SOEM slave table it all works just fine.

**Comment by LiuyanHuang12** [comment]
Thank you for the really fast reply. 
ethercat-sdk is a software from the RT-Labs, we can also use it to control the slave.

**Comment by ArthurKetels** [comment]
OK, but I still do not know what your question is. Two different software solutions, two different slave mappings. I do not see any problem. If your questions is answered, please close the issue. If not, rephrase the question.

**Comment by LiuyanHuang12** [comment]
Thank you, i will close the issur.

**Comment by nakarlsson** [comment]
@LiuyanHuang12 , 
EtherCAT SDK is a GUI ontop of SOEM. Default EtherCAT SDK use SOEM overlapping IO config to support TI ESCs out of the box.

So, as Artur pointed out, just a different way of setting up things.

**Comment by LiuyanHuang12** [comment]
Thank you, I have read more and have a better understanding now. :D
