### ISSUE TITLE
ERROR information in ecx_err2string() function

### ISSUE THREAD

**Issue by 1GuoHaiTong1** [OpenEtherCATsociety/SOEM#797]
When I used  the SOEM to configure the ethercat slave  to run, I added the ecx_err2string() function in ecatcheck to detect the master-slave communication status. It was discovered that the Ec.ErrorCode = 0xff01 error was reported in case EC_ERR_TYPE_EMERGENCY during the communication process. How can I find the relevant documents for this event?

**Comment by ArthurKetels** [comment]
This is a response from a slave. You should read the slave documentation about the meaning of the error.

**Comment by 1GuoHaiTong1** [comment]
OK, thanks for your reply and suggestion.

**Comment by nakarlsson** [comment]
Please close if no more open questions
