### ISSUE TITLE
Communicate with arduino UNO

### ISSUE THREAD

**Issue by Bipin903** [OpenEtherCATsociety/SOEM#798]
Hello everyone, I am using an Arduino UNO as a slave, and I want to control its pins using SOEM EtherCAT. Could you please guide me through the basics, as I am new to EtherCAT .

**Comment by ArthurKetels** [comment]
Do you have an EtherCAT slave controller (ESC) hat connected to your UNO? Otherwise you are missing an important piece of hardware.

**Comment by Bipin903** [comment]
I have LAN9252 EasyCAT by AB&T

**Comment by ArthurKetels** [comment]
I am sorry, but this place is not for free education about EtherCAT basics. My suggestion is to have a look at:
www.ethercat.org
Lots of information available there.

**Comment by Bipin903** [comment]
ok thanks for your information
