### ISSUE TITLE
SOEM and Slave communication issue 

### ISSUE THREAD

**Issue by Bipin903** [OpenEtherCATsociety/SOEM#803]
Hi all , I have written a SOEM master code and my slave is working fine that is blinking LED with Arduino but the problem I m facing is like when I close my SOEM program or terminate the code and again restart the program the LED attached to my slave not blinking till I won't reprogram my EEPROM.

**Comment by ArthurKetels** [comment]
Looks more like an issue with your slave code. When a master commands a slave to INIT state it should reset completely (with respect to EtherCAT).  And I do not understand what you mean by  

> the LED attached to my slave not blinking till I won't reprogram my EEPROM

**Comment by Bipin903** [comment]
Problem solved
