### ISSUE TITLE
the meaning of alia address

### ISSUE THREAD

**Issue by Edphoenixmax** [OpenEtherCATsociety/SOEM#810]
I donnot know what is the meaning of alia address , can anyone give me an example for how to use this alia address?
Thanks a lot!

**Comment by nakarlsson** [comment]
Reading the documentations provided by ESC vendors is sufficient.

ET1100 datasheet > 2.3 EtherCAT Addressing Modes

**Comment by Edphoenixmax** [comment]
Thanks  for your answer! That helps me a lot!
