### ISSUE TITLE
Narrowing conversion / integer overlfow in slaveinfo.c ebus current calculation from SII

### ISSUE THREAD

**Issue by kj4tmp** [OpenEtherCATsociety/SOEM#816]
With an EK1100, the following lines in slaveinfo.c have the following effect:

```c
ec_slave[cnt].Ebuscurrent = ec_siigetbyte(cnt, ssigen + 0x0e); // assigns 48 to int16 ebuscurrent
ec_slave[cnt].Ebuscurrent += ec_siigetbyte(cnt, ssigen + 0x0f) << 8; // adds 63488 to int16 ebuscurrent, overflow!

```

Is this ok?

I do not currently have access to the SII ethercat specifications so its difficult for me to verify if this is the correct math here.

**Comment by ArthurKetels** [comment]
The SII specification states the Ebuscurrent as int16 type. It can be either positive or negative. C integer math allows this assignment of bytes. But perhaps |= would be easier to understand than the current +=. To put it simply, C does not care about numbers, just bits.

**Comment by kj4tmp** [comment]
Thank you for the explanation, when re-writing this example for python, I was unaware of the differences between C and python with this operator. Closing.
