### ISSUE TITLE
Multiple device reading errors using SDO

### ISSUE THREAD

**Issue by Tomisacats** [OpenEtherCATsociety/SOEM#817]
First, the device name is garbled
Second, when I connect 20 devices, the seventh and tenth devices can't read data using SDO, but separate connections can
The above issues only occur in versions above V1.3.3-beta.1
I hope the author can fix it, thank you very much

**Comment by ArthurKetels** [comment]
Making a wireshark capture and posting it here would allow to investigate the cause. As it stands now there is not much information to work with.

**Comment by Tomisacats** [comment]
This is a screenshot. I hope it helps to understand the problem. Thank you
<img width="944" alt="Snipaste_2024-06-04_10-10-06" src="https://github.com/OpenEtherCATsociety/SOEM/assets/145944395/ea95b7b8-2b75-4e27-8ba5-e10735093119">

**Comment by ArthurKetels** [comment]
Thanks for the screenshot, however this is not very helpful. I need a full .pcap file from init to OP (or as far as you get). The capture files compress very well so even large ones can be posted here. I need to see all interaction from SOEM with the slaves as well as any timing of the packets.

**Comment by Tomisacats** [comment]
This is the captured communication package please check, thank you
[test.zip](https://github.com/user-attachments/files/15580294/test.zip)

**Comment by Tomisacats** [comment]
Sorry, we cannot provide the communication data related to initialization. Thank you for your answer
