### ISSUE TITLE
How to get driver ready?

### ISSUE THREAD

**Issue by PhamTuTai** [OpenEtherCATsociety/SOEM#846]
Hi everyone.
I have OP status driver now.
Can anyone tell me which register I have to write value to for driver ready?
Thanks.

**Comment by ArthurKetels** [comment]
First have a look at the tutorial. It explains the basic steps.

**Comment by PhamTuTai** [comment]
> First have a look at the tutorial. It explains the basic steps.
When using PLC connected by EtherCAT. After configuring slave into OP mode. Then call Axis enable function to ready driver.
I don't know if there is any document describing this issue or not?
For example, A_PWR (Axis enable), what value will the master send to which register for slave?
![image](https://github.com/user-attachments/assets/ecac6e42-b853-41f9-ac13-711f5f5115f2)

**Comment by ArthurKetels** [comment]
This looks like a question for the slave manufacturer, not for SOEM. It seems you have the manual, so that explains how to do it?

**Comment by PhamTuTai** [comment]
These are PLC commands. And it is master to control slave.
This document is user manual for PLC Xinje. Connect to slave by EtherCAT standard.
So I want to ask if anyone here knows about this issue?
For example how will the A_PWR function be executed from master to slave. It will have common rules for all slave manuals.
