### ISSUE TITLE
writing to an eRob motor and communication consistency issues

### ISSUE THREAD

**Issue by jennhhw** [OpenEtherCATsociety/SOEM#853]
Hello Everyone, 

I am student who has recently begun working with EtherCAT and am currently working on a research project involving communication with an eRob motor using the EtherCAT protocol. However, I have encountered a few challenges that I am finding difficult to resolve.

**Issue 1**:
I am experiencing difficulties consistently getting the motor into Operational mode. I have been referring to the suggestions provided in a previous issue (#712) and have been testing the recommended code alongside 'simple_test'. Despite these efforts, I have been unable to achieve consistent results.

**Issue 2**:
On the occasions when the motor does successfully enter Operational mode, I am able to read data from the motor; however, I am unable to send write commands effectively. I have been utilizing the code referenced in issue (#712). Although the issue has been marked as closed, I am particularly interested in the comments made after its closure, which discuss approaches to writing commands to the motor.

**Additional Context**:
The motor in use is a ZeroErr eRob motor, which can be found [here](https://www.zeroerr.cn/d/file/download/eRob%20CANopen%20and%20EtherCAT用户手册v1.9.pdf). I have been working to understand the EtherCAT protocol over the past few months and have been facing these issues for some time. The [code](https://github.com/VModugno/ether_motor_test) I am testing is largely based on the final version referenced in the aforementioned issue (#712).

Any guidance or suggestions that could assist in addressing these challenges would be greatly appreciated.

**Comment by Rohithossain007** [comment]
I am also trying to turn the motor on using etherCAT I know I don't have answer for your question but could you please tell me how did you approach? Turning on the motor?

**Comment by jennhhw** [comment]
To turn on the motor I referred to the documentation. My motor turned on once I had plugged in the power supply. If you mean turning the motor on and off via EtherCAT, this wasn't an option with my motor.

**Comment by ZeroErrControl** [comment]
You can refer to this link: [https://github.com/ZeroErrControl/eRob_SOEM_linux/blob/main/test/linux/simple_test/eRob_test.cpp](https://github.com/ZeroErrControl/eRob_SOEM_linux/blob/main/test/linux/simple_test/eRob_test.cpp). I hope it will be helpful to you.
