### ISSUE TITLE
Configure with ENI file

### ISSUE THREAD

**Issue by joeization** [OpenEtherCATsociety/SOEM#88]
Hi,
I'm using AXE5904 slave which use CiA402  to control 4 servo.
But SOEM can't detect the slave.
NEXCOM(manufacture of AXE5904) has a program use ENI file to control the slave.
Can SOEM use ENI to configure the connection?
Thanks

**Comment by joeization** [comment]
Another question, can I use SOEM to perform PDO setup?
Because I need to build a motion control system.

**Comment by joeization** [comment]
Thanks for your help!

**Comment by nakarlsson** [comment]
Her is an example for a drive, https://github.com/hefloryd/SOEM/commit/22d8f5d2a23f42b795357fadfd05ea03cff49350

**Comment by nakarlsson** [comment]
Ser the example
