### ISSUE TITLE
Configuration and control AX5000

### ISSUE THREAD

**Issue by chimeno86** [OpenEtherCATsociety/SOEM#96]
Does anyone know how to handle the beckhoff AX5000 using soem? I do not find much information on the internet on how to make it work, thanks

**Comment by nakarlsson** [comment]
Do you have the ESI?

**Comment by chimeno86** [comment]
Hello, if I configure the AX5206 servodrive with the AM3031 engine with twincat3 and it works perfectly the file this XML extension.


[AX5206.zip](https://github.com/OpenEtherCATsociety/SOEM/files/888562/AX5206.zip)

**Comment by nakarlsson** [comment]
If you got the ESI and can configure it with TwinCAT then you can find a Moog sample how to configure a drive with SOEM here, hefloryd@22d8f5d

**Comment by chimeno86** [comment]
Hello Nakarlsson, thank you very much for the link, I will study it if I can control it, thanks Albert

**Comment by nakarlsson** [comment]
No update so fixed I guess
