### ISSUE TITLE
Acyclic data processing

### ISSUE THREAD

**Issue by lukasfolle** [OpenEtherCATsociety/SOEM#97]
Hi,

I am trying to transmitt and receive data over the ethercat frame, that do not need to be updated every microsecond. 
The implementation on the slave was relatively easy, but how is it possible to send e.g. a single bit every ten seconds from the master to the slave via the frame?

With regards,
Lukas Folle

**Comment by nakarlsson** [comment]
If it is the entire processdata of one slave you can look at groups, if you want to have fast and slow processdata per slave it is not possible with SOEM as it is designed today.

**Comment by lukasfolle** [comment]
Thanks for the fast reply!
I will have to look into that.
